### ISSUE TITLE
S3_Generator fails to correctly build batch_kwargs with reader_method specified

### ISSUE THREAD

**Issue by jcampbell** [fivetran/great_expectations#1000]
When using an S3_Generator, a config specifying a reader_method, such as the following:

```
datasources:
  first_test:
    class_name: SparkDFDatasource
    data_asset_type:
      class_name: SparkDFDataset
    generators:
      my_s3_generator:
        class_name: S3Generator
        bucket: my_bucket
        reader_method: delta
```

will fail with the error "ValueError: 'delta' is not a valid ReaderMethods"

The S3 Generator is trying to map to an enum too early, and should just return the string-based reader_method.
