### ISSUE TITLE
Data Docs > S3 > Links to runs are access Denied

### ISSUE THREAD

**Issue by troxil** [fivetran/great_expectations#1235]
Hi All!

When I use GE to create data docs through either `docs build` or the API `context.build_data_docs()` I find that the created files arrive fine in S3, however the index.html page does not link to them properly and I get 403 S3 errors. 

I find that if I navigate to the created html in the docs/validations prefix on S3 it is fine. After comparing the link provided by the index.html and the direct link available in S3 UI - they are identical except that the one from S3 is url encoded.

This is otherwise fine if running locally.

```yaml
data_docs_sites:
  s3_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: mybucket.org.com
      prefix: docs/
```

Cheers,
