### ISSUE TITLE
config_variables.yml does not support environment variables

### ISSUE THREAD

**Issue by ian-whitestone** [fivetran/great_expectations#1258]
In the default setup created through `great_expectations init` for a SQL datasource, an uncommitted `config_variables.yml` file is created. This file stores all things required to establish a database connection. By default, this file is designed to **not** be committed to source control. However, there are some cases where it would be beneficial to have this file committed. In this case, you would want to be able to have some keys specified as environment variables, for example:

`great_expectations.yml`

```yaml
config_version: 1

datasources:
  domi:
    class_name: SqlAlchemyDatasource
    module_name:
    data_asset_type:
      module_name:
      class_name: SqlAlchemyDataset
    credentials: ${my-example-db}
```

`config_variables.yml`

```yaml
ge_comment_preservation_key: 1

my-example-db:
  drivername: postgres
  host: host-endpoint-to-use
  port: '5432'
  username: ${USER}
  password: ${PASSWORD}
  database: database_name
```

In this example, I have the host, port and database name exposed but the username/password kept as secrets that should live in environment variables. Unfortunately, this doesn't work.

I recognize I could just move this all into the `great_expectations.yml`, and then it would work, but I like the idea of having datasource configurations stored separately, so I think it would be nice to support this eventually.
