### ISSUE TITLE
QueryBatchKwargsGenerator should accept name in recognized_batch_parameters

### ISSUE THREAD

**Issue by ian-whitestone** [fivetran/great_expectations#1289]
I am using the `QueryBatchKwargsGenerator` to generate `BATCH_KWARGS` using a SQL file I have stored on disk. My `great_expectations.yml` looks like:

```yaml
datasources:
    domi:
      class_name: SqlAlchemyDatasource
      module_name:
      data_asset_type:
        class_name: SqlAlchemyDataset
      credentials:
        drivername: postgres
        host: ${HOST}
        port: ${PORT}
        username: ${USER}
        password: ${PASSWORD}
        database: ${DBNAME}
      generators:
        apartments-generator:
          class_name: QueryBatchKwargsGenerator
          name: apartments
```

I am running the following:

```python
>>> import great_expectations as get

>>> context = ge.data_context.DataContext()
>>> context.get_available_data_asset_names()
{'domi': {'apartments-generator': {'names': [('listings', 'query')]}}}

>>> context.build_batch_kwargs(datasource='domi', generator='apartments-generator', name=('listings',))
2020-04-10T14:05:41-0400 - WARNING - Unrecognized batch_parameter(s): {'name'}
{'query_parameters': None,
 'query': "SELECT * from listings where created_at > date'2020-01-01'",
 'datasource': 'domi'}
```

You can see this warning `Unrecognized batch_parameter(s): {'name'}` gets raised, but the `_build_batch_kwargs` method is clearly looking for a parameter named `name` [source](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/datasource/generator/query_generator.py#L101-L103):

```python
    def _build_batch_kwargs(self, batch_parameters):
        """Build batch kwargs from a partition id."""
        generator_asset = batch_parameters.pop("name")
```

Therefore I believe `name` should be added to the `recognized_batch_parameters` property here:

```python
class QueryBatchKwargsGenerator(BatchKwargsGenerator):
    """Produce query-style batch_kwargs from sql files stored on disk
    """
    recognized_batch_parameters = {'query_parameters', 'partition_id'}
```
