### ISSUE TITLE
QueryBatchKwargsGenerator._get_raw_query produces incorrect filepath

### ISSUE THREAD

**Issue by ian-whitestone** [fivetran/great_expectations#1290]
I am using the `QueryBatchKwargsGenerator` to generate `BATCH_KWARGS` using a SQL file I have stored on disk. My `great_expectations.yml` looks like:

```yaml
datasources:
    domi:
      class_name: SqlAlchemyDatasource
      module_name:
      data_asset_type:
        class_name: SqlAlchemyDataset
      credentials:
        drivername: postgres
        host: ${HOST}
        port: ${PORT}
        username: ${USER}
        password: ${PASSWORD}
        database: ${DBNAME}
      generators:
        apartments-generator:
          class_name: QueryBatchKwargsGenerator
          name: apartments
```

I am running the following:

```python
>>> import great_expectations as get

>>> context = ge.data_context.DataContext()
>>> context.get_available_data_asset_names()
{'domi': {'apartments-generator': {'names': [('listings', 'query')]}}}

>>> context.build_batch_kwargs(
    datasource='domi', generator='apartments-generator', name='listings'
)
```

Which raises this error:

![image](https://user-images.githubusercontent.com/11096727/79018747-8e14b080-7b42-11ea-9564-7b35b23dac72.png)

This happens because `_get_raw_query` is doing `tuple('listings')` which returns: `('l', 'i', 's', 't', 'i', 'n', 'g', 's')`)

```python
    def _get_raw_query(self, generator_asset):
        return self._store_backend.get(tuple(generator_asset))
```

I believe this should just be replaced with:

```python
    def _get_raw_query(self, generator_asset):
        return self._store_backend.get((generator_asset,))
```

Currently I can get around this by providing a tuple instead of a string, i.e.

```python
context.build_batch_kwargs(
    datasource='domi',
    generator='apartments-generator',
    name=('listings', )
)
```

But that goes against what the docs are saying [here](https://docs.greatexpectations.io/en/latest/module_docs/data_context_module.html#great_expectations.data_context.BaseDataContext.build_batch_kwargs):

![image](https://user-images.githubusercontent.com/11096727/79018985-30cd2f00-7b43-11ea-962c-3a563f19acc6.png)
