### ISSUE TITLE
What happened to InMemoryGenerator?

### ISSUE THREAD

**Issue by josh-cooper** [fivetran/great_expectations#1348]
Was present in 0.8 but there's no equivalent under batch_kwargs_generators. Documentation still mentions it.

**Comment by jcampbell** [comment]
@josh-cooper  -- I'll try to purge references from the docs.

Short answer is that InMemoryGenerator is just no longer needed, and can always be safely removed completely from a configuration.

For example, if before you had:

Config:
```
datasources:
  my_datasource:
    class_name: PandasDatasource
    generators:
      my_generator:
        class_name: InMemoryGenerator
```

Usage:
```
context = DataContext()
batch = context.get_batch("my_datasource/my_generator/my_asset",
  expectation_suite_name="my_asset.warning",
  batch_kwargs={"dataset": my_pandas_data}
)
```

Then in the new (0.9+) API, that would be updated to:
Config:
```
datasources:
  my_datasource:
    class_name: PandasDatasource

```

Usage:
```
context = DataContext()
batch = context.get_batch(
  expectation_suite_name="my_asset.warning",
  batch_kwargs={"datasource": "my_datasource", "dataset": my_pandas_data}
)
```
