### ISSUE TITLE
Data Docs url does not include GCS prefix if configured

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1398]
**Describe the bug**

**To Reproduce**

1. Configure a backend like this:
```yaml
data_docs_sites:
  gcs_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleGCSStoreBackend
      bucket: ge-support
      prefix: bar
      project: my-project
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```
2. run `great_expectations docs build`
3. Note the url `https://storage.googleapis.com/ge-support/index.html` that does not include the `prefix` set to `bar` in this case.

**Expected behavior**
I would expect the url to be `https://storage.googleapis.com/ge-support/bar/index.html`

**Environment (please complete the following information):**
 - OS: macOS
 - GE Version: version 0.10.8+8.g45e7dc06

**Additional context**
