### ISSUE TITLE
Configuring GCS for Data Docs `prefix` key should be optional

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1399]
**Describe the bug**
Configuring a data docs site on GCS requires the `prefix`.

**To Reproduce**

1. Configure a backend like this (note the lack of `prefix` key):
```yaml
data_docs_sites:
  gcs_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleGCSStoreBackend
      bucket: ge-support
      project: my-project
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```
2. run `great_expectations docs build`
3. Note the stacktrace:
```bash
Couldn't instantiate class : TupleGCSStoreBackend with config : 
	filepath_prefix		expectations
	filepath_suffix		.html
	bucket		ge-support
	project		my-project
 
__init__() missing 1 required positional argument: 'prefix'
```

**Expected behavior**
I would expect the `prefix` key to be optional.

Note as a workaround you can include the key with an empty string like this:

```yaml
data_docs_sites:
  gcs_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleGCSStoreBackend
      bucket: ge-support
      prefix: ""
      project: my-project
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```

**Environment (please complete the following information):**
 - OS: macOS
 - GE Version: version 0.10.8+8.g45e7dc06
