### ISSUE TITLE
GCS data docs urls sometimes malformed

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#1528]
**Describe the bug**
Some GCS hosted data docs links are malformed and do not work.

**To Reproduce**
1. Configure a data docs site as follows:
```yaml
  gcs_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleGCSStoreBackend
      bucket: "super_secret_bucket"
      prefix: ""
      project: super_secret_project
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```
2. ensure you have some validations
3. `great_expectations docs build` on GCS
4. navigate to the bucket browser and note the index is viewable via a working link like https://storage.cloud.google.com/super_secret_bucket/index.html which resolves to a link like https://big-long-hash-apidata.googleusercontent.com/download/storage/v1/b/super_secret_bucket/o/index.html?qk=secret_key&isca=1
5. Click on any validation link or expectation link and note the `Not Found` result.

**Expected behavior**
I expect links in data docs hosted on GCS to work.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] 0.11.1

**Additional context**
