### ISSUE TITLE
Extend env var/config_variables.yml support in checkpoint files

### ISSUE THREAD

**Issue by lauralorenz** [fivetran/great_expectations#1565]
**Is your feature request related to a problem? Please describe.**
My problem was that I wanted to be able to use the same great_expectations **checkpoint** config in different environments, in my specific case in a CI environment and a local development environment, for which some details regarding filepaths for data batches may be deterministically different. 

**Describe the solution you'd like**
I'd like to be able to do variable substitution in checkpoint files like you can in great_expectations.yml.

For example:
```
# warning_npi_checkpoing.yml
validation_operator_name: action_list_operator
batches:
  - batch_kwargs:
      path: ${my_special_path}/data/npidata/npidata_pfile_20190902-20190908.csv
      datasource: npidata__dir
      data_asset_name: npidata_pfile_20190902-20190908
    expectation_suite_names:
      - npidata_pfile_20190902-20190908.warning
```

Right now even if `my_special_path` is described in an env var or in my config file (ex `uncommitted/config_variables.yml`), it is not interpolated here for when I try to run the checkpoint, for example with `great_expectations checkpoint run warning_npi_checkpoint`:

```
great_expectations git:(issue-2489-great-expectations-task) ✗ my_special_path='..' great_expectations checkpoint run warning_npi_checkpoint
Heads up! This feature is Experimental. It may change. Please give us your feedback!
There was a problem loading a batch:
  - Batch: {'path': '${my_special_path}/data/npidata/npidata_pfile_20190902-20190908.csv', 'datasource': 'npidata__dir', 'data_asset_name': 'npidata_pfile_20190902-20190908'}
  - [Errno 2] File ${my_special_path}/data/npidata/npidata_pfile_20190902-20190908.csv does not exist: '${my_special_path}/data/npidata/npidata_pfile_20190902-20190908.csv'
  - Please verify these batch kwargs in the checkpoint file: `great_expectations/checkpoints/warning_npi_checkpoint.yml`
```

**Describe alternatives you've considered**
- Always write different checkpoints for every environment. This is what I'm doing now.

**Additional context**
Maybe this is a bit extra in terms of additional context but FYI I'm opening this due to the experience I had writing an integration to Prefect with GE checkpoints (specifically here: https://github.com/PrefectHQ/prefect/pull/2625#discussion_r434899794)
