### ISSUE TITLE
Local Spark not utilizing spark_config parameter from great_expectations.yml

### ISSUE THREAD

**Issue by WesRoach** [fivetran/great_expectations#1603]
**Describe the bug**

Running Spark in local mode.

I've added the `spark_config` key-value dict to my Spark datasource in great_expectations.yml.

- Setting environment variable SPARK_DRIVER_MEMORY will be used by GE's Spark session
- Removing env var SPARK_DRIVER_MEMORY and setting `spark.driver.memory` in yaml results in java heap space error.

Using the semi-example from https://docs.greatexpectations.io/en/latest/how_to_guides/configuring_datasources/how_to_configure_a_spark_filesystem_datasource.html

```yaml
datasources:
  my_data.parquet__dir:
    data_asset_type:
      module_name: great_expectations.dataset
      class_name: SparkDFDataset
    module_name: great_expectations.datasource
    spark_config: {
        "spark.local.dir": "/u01/data/spark-tmp",
        "spark.driver.memory": "16g"
    }
    class_name: SparkDFDatasource
    batch_kwargs_generators:
      subdir_reader:
        class_name: SubdirReaderBatchKwargsGenerator
        base_directory: <path-to-directory>
```

Also tried:

```yaml
...
    spark_config: 
        spark.local.dir: /u01/data/spark-tmp
        spark.driver.memory: 16g
...
```

**To Reproduce**

1. Start GE Spark job (profiling, checkpoint, etc)
1. Check Spark's Environment (typically http://localhost:4040/environment/)
1. Observe Spark's Environment variables

**Expected behavior**

Expected GE's Spark Session to utilize spark_config from great_expectations.yml.

**Environment (please complete the following information):**
 - OS: RHEL7
 - GE Version: 0.11.1
 - PySpark: 2.4.5
 - Conda: 4.8.2

Edit: Added pyspark, conda versions.
