### ISSUE TITLE
WarningAndFailureExpectationSuitesValidationOperator failing when warning suite fails

### ISSUE THREAD

**Issue by villoro** [fivetran/great_expectations#1800]
## Describe the bug
I am running `WarningAndFailureExpectationSuitesValidationOperator` and I have two expectations with the following results:
* table.failure: success
* table.warning: fails

And the overall result is `success=False`:

```json
{
  "success": false,
  "run_results": {
    "ValidationResultIdentifier::table/failure/20200814_102416/20200814T082416.292789Z/109cf409fe64ccc5669145980c35b1c0": {
      "expectation_suite_severity_level": "failure",
      "validation_result": {
        "results": [...],
        "success": true,
        "evaluation_parameters": {},
        "meta": {...},
        "statistics": {...},
      },
      "actions_results": {
        "store_validation_result": {},
        "store_evaluation_params": {},
        "update_data_docs": {}
      }
    },
    "ValidationResultIdentifier::table/warning/20200814_102416/20200814T082416.292789Z/109cf409fe64ccc5669145980c35b1c0": {
      "expectation_suite_severity_level": "warning",
      "validation_result": {
        "results": [...],
        "success": false,
        "evaluation_parameters": {},
        "meta": {...},
        "statistics": {...},
      },
      "actions_results": {
        "store_validation_result": {},
        "store_evaluation_params": {},
        "update_data_docs": {}
      }
    }
  },
  "evaluation_parameters": null,
  "run_id": {
    "run_name": "20200814_102416",
    "run_time": "2020-08-14T08:24:16.292789+00:00"
  },
  "validation_operator_config": {
    "class_name": "WarningAndFailureExpectationSuitesValidationOperator",
    "module_name": "great_expectations.validation_operators",
    "name": "warning_and_failure_operator",
    "kwargs": {...},
  }
}
```

## Expected behavior
As stated in the [documentation](https://docs.greatexpectations.io/en/v0.11.x/reference/validation_operators/warning_and_failure_expectation_suites_validation_operator.html#warning-and-failure-expectation-suites-validation-operator) the value of “success” should be `true` if no critical expectation suites (`.failure`) failed to validate (non-critical `.warning`) expectation suites are allowed to fail without affecting the success status of the run.

## To Reproduce
Here you have some of the files that should represent the error:

### Checkpoint `table.yml`
```yaml
validation_operator_name: warning_and_failure_operator
batches:
  - batch_kwargs:
      query: SELECT * FROM table
      datasource: redshift
      data_asset_name: table

    expectation_suite_names:
      - table.warning
      - table.failure
```

### Config `great_expectations.yml`
```yaml
validation_operators:
  warning_and_failure_operator:
    class_name: WarningAndFailureExpectationSuitesValidationOperator

    action_list:
      - name: store_validation_result
        action:
          class_name: StoreValidationResultAction
      - name: store_evaluation_params
        action:
          class_name: StoreEvaluationParametersAction
      - name: update_data_docs
        action:
          class_name: UpdateDataDocsAction
```

### Test code
```python
import os
from datetime import datetime
from great_expectations import DataContext

context = DataContext(os.getcwd())

# checkpoint configuration
checkpoint = context.get_checkpoint("table")

# load batches of data
batches_to_validate = []
for batch in checkpoint["batches"]:
    batch_kwargs = batch["batch_kwargs"]
    for suite_name in batch["expectation_suite_names"]:
        suite = context.get_expectation_suite(suite_name)
        batch = context.get_batch(batch_kwargs, suite)
        batches_to_validate.append(batch)

# run the validation operator
results = context.run_validation_operator(
    checkpoint["validation_operator_name"],
    assets_to_validate=batches_to_validate,
    base_expectation_suite_name="table",
)

print(results)
```

## Environment:
 - OS: windows
 - GE Version: 0.12.0

## Additional context
I don't belive more information is needed, but feel free to ask if it can help.
