### ISSUE TITLE
Expectations html documentation is not generated with S3 doc site as backend 

### ISSUE THREAD

**Issue by HugoManoMano** [fivetran/great_expectations#1860]
**Describe the bug**
Expectations html documentation is not generated with S3 doc site as backend 

**To Reproduce**
1. Use a data context that has an S3 doc site
2. Have an update data doc action with UpdateDataDocsAction in a validation operator
3. Validate data with the data context
4. Expectations part of the documentation not being sent to S3 bucket (while validations are)
5. Have a 404 not found when clicking on the suite name in index.html
6. Making `great_expectations docs build` seems to generate the expectations key in the doc subdirectory

**Expected behavior**
Shoud have expectations generated in the doc in S3

**Environment (please complete the following information):**
 - OS: Ubuntu
 - GE Version: 0.12.0

**Additional context**
great_expectations.yml as referenced by GREAT_EXPECTATIONS_CONF_FILE_PATH in the Python code above
```yaml
validation_operators:
  action_list_operator:
    class_name: ActionListValidationOperator
    action_list:
      - name: store_validation_result
        action:
          class_name: StoreValidationResultAction
      - name: store_evaluation_params
        action:
          class_name: StoreEvaluationParametersAction
      - name: update_data_docs
        action:
          class_name: UpdateDataDocsAction

(...)

data_docs_sites:
  s3_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: my-bucket
      prefix: ${ENV_VAR}/doc
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
 ```

test.py
```python
import great_expectations as ge
context = ge.data_context.DataContext(GREAT_EXPECTATIONS_CONF_FILE_PATH)
suite = context.get_expectation_suite(ge_suite_name)
batch = context.get_batch(ge_batch_kwargs, suite)
results = context.run_validation_operator(
    validation_operator_name=action_list_operator_name,
    assets_to_validate=[batch],
    run_id=run_id
)
 ```

Content of my-bucket/${ENV_VAR}/doc
![Capture d’écran de 2020-08-28 19-24-34](https://user-images.githubusercontent.com/61005730/91595689-3dbcb480-e964-11ea-9914-15c77ae3bf79.png)
