### ISSUE TITLE
Obtaining queries from query stores in checkpoints and expectation suites

### ISSUE THREAD

**Issue by lukedyer-peak** [fivetran/great_expectations#1948]
**Is your feature request related to a problem? Please describe.**
I would like to be able to specify the batch of data to use during a checkpoint or expectation suite using the `SqlAlchemyQueryStore`.  This is currently possible when generating the expectations in a notebook from this [example the docs](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/creating_batches/how_to_load_a_database_table_view_or_query_result_as_a_batch.html).  I had expected that this would also be possible for running checkpoints.  I had also expected it to be able to be saved in the `citations` of an expectation_suite so it would dynamically load the file if it has changed in the days/weeks between creating an expectations suite and editing it later on.

**Describe the solution you'd like**
Following on from the example above in the docs (slightly modifying the query to not use parameters):

`great_expectations.yml`
```yaml
my_db:
  class_name: SqlAlchemyDatasource
  credentials: ${rds_movies_db}
  data_asset_type:
    class_name: SqlAlchemyDataset
    module_name: great_expectations.dataset
  batch_kwargs_generators:
    tables:
      class_name: TableBatchKwargsGenerator
    queries:
      class_name: QueryBatchKwargsGenerator
      query_store_backend:
        class_name: TupleFilesystemStoreBackend
        filepath_suffix: .sql
        base_directory: queries
```
Directory structure:
```
great_expectations/
    queries/
        movies_by_date.sql
```
`movies_by_date.sql`:
```sql
SELECT * FROM movies WHERE '1988-01-01'::date <= release_date AND release_date <= '1989-01-01'::date;
```
I would then like to be able to specify a checkpoint by:
```yaml
batches:
  - batch_kwargs:
      query_store_key: movies_by_date
      datasource: my_db
    expectation_suite_names:
      - my_expectation_suite
```

**Describe alternatives you've considered**
As suggested on [slack](https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1601564621051300) one could save all the queries as views on the database.  Depending on the database, this could cause issues if you can use late binding views and underlying tables are dropped.  This also can clutter up the database with views only used for checking data via great expectations.

**Additional context**
- [Slack conversation](https://greatexpectationstalk.slack.com/archives/CUUMYDJAX/p1601564621051300)
- [`SqlAlchemyQueryStore`](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/data_context/store/query_store.py), which I had imaged would be able to be used from config files
