### ISSUE TITLE
validations directory getting deleted in new run

### ISSUE THREAD

**Issue by eattogether2020** [fivetran/great_expectations#1985]
**[Build Doc]: validations directory getting deleted in second run**
 The validations document (hosted on S3) getting deleted when we run the test case from a new directory or server 

**To Reproduce**
1. Initialise great_expectations project (Folder structure will be created locally)
2. Set the s3_site in great_expectations.yml file (All the document folder structure will be created on S3)
3. Validate the test suite 
	Sample command - 
		rs = context.run_validation_operator("action_list_operator", assets_to_validate=[my_df])
		validation_result_identifier = rs.list_validation_result_identifiers()[0]

4. It will write the data validation files into S3 

5. Now copy the great_expectations directory to another server or another parent directory
6. Run step-3, that will delete everything from S3 path, also it won’t create any validations 

1. To make it work -
    1. Again you have to build the document by following command from the same path 
		great_expectations docs build --site-name s3_site 
	 2. Run step-3 that will write new files, however the problem is that old validations files are gone

**Expected behavior**
Ideally it should not delete my historical validation files 

**Environment (please complete the following information):**
 -  Amazon Linux
 - GE Version:  0.12.4

**Additional context**
I did bit debug and found that - this may be the cause - 
skip_and_clean_missing param is set as true and that probably causing the issue.

I saw in the following pull request this functionality has been added, but its no where defined in either test-cases or documents about how to set it up through config file (At least I did not find)

https://github.com/great-expectations/great_expectations/pull/1786/files

Here is my site config -

```
s3_site:  
  class_name: SiteBuilder
  store_backend:
    class_name: TupleS3StoreBackend
    bucket: ge-eu-c-2
    prefix: great_expectations
  site_index_builder:
    class_name: DefaultSiteIndexBuilder
    skip_and_clean_missing: False     <===== That's not working
    show_cta_footer: true
```

**Comment by eugmandel** [comment]
@eattogether2020 I suspect that your great_expectations.yml file is configured in a way that the validation results are stored locally as JSON files and the Data Docs site is hosted on S3.
If this is the case, the behavior that you described is "as designed". Every time you run your project from a new directory or a server Great Expectations sees an empty directory with validation results. Then it overwrites the Data Docs on S3.

If you change the `validations_store_name` config property in your great_expectations.yml to store the JSON validation results files on S3 (as described in this [how-to guide](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_s3.html)), the validation results and their HTML representation will be in sync regardless which directory/server your project runs in.


Please comment if this resolves the issue so that we know if we can close it or a further action is needed.

**Comment by eattogether2020** [comment]
@eugmandel  thank you very much for your response - I just had a quick look.

This is my current configuration which was created by default  and I replaced only S3 site as I wanted the validations on S3 -If you see, there is one main element called `store` and child element `validations_store`
then, there is another key called `validations_store_name: validations_store`
As per the document - It should be like following (If its S3)
```
validations_store_name: validations_S3_storestores:
    validations_S3_store:
        class_name: ValidationsStore
        store_backend:
            class_name: TupleS3StoreBackend
            bucket: '<your_s3_bucket_name>'
            prefix: '<your_s3_bucket_folder_name>'

I hope, I need not to change anything in store/validation_store element or do I ?

config_version: 2.0datasources:
  mydata:
    class_name: PandasDatasource
    batch_kwargs_generators:
      subdir_reader:
        class_name: SubdirReaderBatchKwargsGenerator
        base_directory: /Users/smruti.sahoo/great_expectations/
    module_name: great_expectations.datasource
    data_asset_type:
      class_name: PandasDataset
      module_name: great_expectations.datasetconfig_variables_file_path: uncommitted/config_variables.ymlplugins_directory: plugins/validation_operators:
  action_list_operator:
    class_name: ActionListValidationOperator
    action_list:
    - name: store_validation_result
      action:
        class_name: StoreValidationResultAction
    - name: store_evaluation_params
      action:
        class_name: StoreEvaluationParametersAction
    - name: update_data_docs
      action:
        class_name: UpdateDataDocsActionstores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/  evaluation_parameter_store:
    class_name: EvaluationParameterStoreexpectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_storedata_docs_sites:  s3_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: ge-eu-c-2
      prefix: great_expectations
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
      show_cta_footer: trueanonymous_usage_statistics:
  enabled: true
  data_context_id: b578de73-0152-41a4-b75b-e3b2552d1782
notebooks:
```
