### ISSUE TITLE
UpdateDataDocsAction ignores site_names parameter

### ISSUE THREAD

**Issue by anthonyburdi** [fivetran/great_expectations#1991]
**Describe the bug**
When creating data docs sites, the UpdateDataDocsAction ignores the site_names parameter and tries to build all sites anyway. It also tries to get urls for all sites. This leads to errors when sites may not be accessible. For example, some users use the following pattern to identify an active site depending on the environment (e.g. dev / prod):
```
    - name: update_data_docs
      action:
        class_name: UpdateDataDocsAction
        site_names:
          - ${ACTIVE_SITE}
```

**To Reproduce**
1. Create 2 data docs sites, one that you can connect to (e.g. `local_site`) and one you cannot (e.g. make up an invalid s3 bucket).
2. set the site_names parameter to the site you can connect to
3. see the errors from Great Expectations trying to connect to the invalid site

**Expected behavior**
I expect Great Expectations to not attempt to connect to sites not listed in the site_names parameter.

**Environment (please complete the following information):**
 - OS: osx 10.15.6
 - GE Version: 0.12.4

**Additional context**
See also this thread: https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1602782817160500
