### ISSUE TITLE
password skipping config substitution

### ISSUE THREAD

**Issue by EliMorato** [fivetran/great_expectations#2005]
**Describe the bug**
When using environment variables to provide datasource credentials in great_expectations.yml, example:
```
    credentials:
      drivername: postgresql+psycopg2
      host: ${GE_REDSHIFT_HOST}
      port: ${GE_REDSHIFT_PORT}
      username: ${GE_REDSHIFT_USER}
      password: ${GE_REDSHIFT_PASSWORD}
      database: ${GE_REDSHIFT_DB}

```
the password is reading "${GE_REDSHIFT_PASSWORD}" as the `password` value due to [this bugfix](https://github.com/great-expectations/great_expectations/commit/9d85b7e0543d170e73df99dcc985c649a0f395bb).

**To Reproduce**
1. Use an environment variable in your datasource credentials' password
2. Run anything that needs to connect to the datasource. For example, you can create a new suite or edit an old one and run the first Jupyter Notebook cell. You'll get an authentication error like this:
<img width="1198" alt="Captura de pantalla 2020-10-21 a las 18 11 02" src="https://user-images.githubusercontent.com/40449560/96747904-28df2900-13c9-11eb-901b-c1c01ffcc1bd.png">

<img width="1396" alt="Captura de pantalla 2020-10-21 a las 18 11 55" src="https://user-images.githubusercontent.com/40449560/96747889-2381de80-13c9-11eb-8771-933e218c435f.png">

**Expected behavior**
Not to crash and also read the value of the environment variable (${GE_REDSHIFT_PASSWORD} in this case) as the `password` value for the datasource credentials.

**Environment (please complete the following information):**
 - OS: All
 - GE Version: 0.12.6

**Additional context**
@anthonyburdi
