### ISSUE TITLE
Is it possible for pandas_s3_generator to include all files under one s3 folder

### ISSUE THREAD

**Issue by sunjiajing0815** [fivetran/great_expectations#2065]
**Is your feature request related to a problem? Please describe.**
My data source folder in s3 contains multiple parquet files under one partition, e.g:
```
s3://my_bucket/my_prefix/key1.parquet
s3://my_bucket/my_prefix/key2.parquet
s3://my_bucket/my_prefix/key3.parquet
```
I have tried to use pandas_s3_generator in data source configuration to generate the batch_kwargs for scaffold and checkpoints. i.e.
``` 
pandas_s3:
    class_name: PandasDatasource
    batch_kwargs_generators:
      pandas_s3_generator:
        class_name: S3GlobReaderBatchKwargsGenerator
        bucket: my_bucket # Only the bucket name here (i.e., no prefix)
        assets:
          my_data_asset:
            prefix: my_prefix/ # trailing slash is important
            regex_filter: .*\.parquet
```
but only can get the first key in the folder in scaffold:
```
context = DataContext()
batch_kwargs = {
    "datasource": "pandas_s3",
    "path": "s3a://my_bucket/my_prefix/key1.parquet",
}
batch = context.get_batch(batch_kwargs, "existing_expectation_suite_name")
```
and in checkpoint
```
batches:
  - batch_kwargs:
      s3: s3a://my_bucket/my_prefix/key1.parquet
      reader_options: {}
      datasource: pandas_s3
      data_asset_name: my_data_asset
    expectation_suite_names: # one or more suites may validate against a single batch
      - my_expectation_suite
```
Have I missed anything here?
