### ISSUE TITLE
show_cta_footer: false has no effect

### ISSUE THREAD

**Issue by Aylr** [fivetran/great_expectations#2120]
**Describe the bug**
When building data docs the footer with buttons is not disable-able.

**To Reproduce**
1. configure GE to not build footer
2. build docs
3. see footer

**Expected behavior**
I'd expect the footer to respect the disabling.

**Environment (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - GE Version: [e.g. 0.10.0] seen as old as 0.12.6? and as new as 0.13.1

**Comment by eugmandel** [comment]
@Aylr Which browser do you see this issue with? Asking to make sure that the browser does not ignore cookies.

**Comment by Aylr** [comment]
both Safari and Chrome

**Comment by anthonyburdi** [comment]
@Aylr - it looks like `show_cta_footer` was deprecated in favor of setting `show_how_to_buttons = false` in this commit https://github.com/great-expectations/great_expectations/commit/516ac7d792c1aad0afc7a7dc95258151389f36ef #1249 which works, e.g.:
```
  local_site:
    class_name: SiteBuilder
    # set to false to hide how-to buttons in Data Docs
    show_how_to_buttons: false
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```
I'll submit a PR to remove the mentions of `show_cta_footer` from data_context/types/base.py
I'll also take a look at the `data_docs_site_anonymizer` where `show_cta_footer` is mentioned.
If this was some hazing e.g. a senior telling a freshman to go check out the pool on the roof of the school well then well played sir 😂
