### ISSUE TITLE
How to pass reader_method to ConfiguredAssetFilesystemDataConnector

### ISSUE THREAD

**Issue by jcampbell** [fivetran/great_expectations#2201]
I am unable to find instructions on how to configure reader_method or other batch_spec parameters using a ConfiguredAssetFilesystemDataConnector.

I have tried variations similar to the following:

```
class_name: Datasource
execution_engine:
  class_name: SparkDFExecutionEngine
data_connectors:
  stats:
    class_name: ConfiguredAssetFilesystemDataConnector
    base_directory: base_directory
    glob_directive: "**/"
    assets:
      logo_events:
        pattern: subdir/subdir/year=(\d{4})/week=(\d{2})
        group_names:
          - year
          - week
 #       batch_spec_passthrough:
 #          reader_method: parquet
```

Because I am using Spark, it is important to me to be able to provide full directories as my path parameter, which understandably foils the reader_method detection. I'm observing: `BatchKwargsError: Unable to determine reader method from path: subdir/subdir/year=2020/week=18`

I can't seem to provide the passthrough.
