### ISSUE TITLE
Bug: WarningAndFailureExpectationSuitesValidationOperator isn't passed all arguments needed

### ISSUE THREAD

**Issue by luke321321** [fivetran/great_expectations#2569]
**Describe the bug**
The `WarningAndFailureExpectationSuitesValidationOperator` needs to be passed `base_expectation_suite_name`.  However, when running from the CLI (v12) on a checkpoint this is never passed and indeed looking at the source code can never be passed by the ` run_validation_operator()` function:
https://github.com/great-expectations/great_expectations/blob/f71b61de74e136f7eef1d527471649b77f520282/great_expectations/data_context/data_context.py#L1233
https://github.com/great-expectations/great_expectations/blob/f71b61de74e136f7eef1d527471649b77f520282/great_expectations/data_context/data_context.py#L1284

Has the support for this validation operator been removed?

**To Reproduce**
I've used the examples here: https://docs.greatexpectations.io/en/latest/autoapi/great_expectations/validation_operators/validation_operators/index.html#great_expectations.validation_operators.validation_operators.ActionListValidationOperator

```yml
validation_operators:
  run_warning_and_failure_expectation_suites:
      class_name: WarningAndFailureExpectationSuitesValidationOperator
  
      # the following two properties are optional - by default the operator looks for
      # expectation suites named "failure" and "warning".
      # You can use these two properties to override these names.
      # e.g., with expectation_suite_name_prefix=boo_ and
      # expectation_suite_name_suffixes = ["red", "green"], the operator
      # will look for expectation suites named "boo_red" and "boo_green"
      expectation_suite_name_prefix="",
      expectation_suite_name_suffixes=["failure", "warning"],
  
      # optional - if true, the operator will stop and exit after first failed validation. false by default.
      stop_on_first_error=False,
  
      # put the actual webhook URL in the uncommitted/config_variables.yml file
      slack_webhook: ${validation_notification_slack_webhook}
      # optional - if "all" - notify always, "success" - notify only on success, "failure" - notify only on failure
      notify_on="all"
  
      # the operator will call the following actions on each validation result
      # you can remove or add actions to this list. See the details in the actions
      # reference
      action_list:
        - name: store_validation_result
          action:
            class_name: StoreValidationResultAction
            target_store_name: validations_store
        - name: store_evaluation_params
          action:
            class_name: StoreEvaluationParametersAction
            target_store_name: evaluation_parameter_store
```

with the checkpoint configured as:
```yml
validation_operator_name: run_warning_and_failure_expectation_suites

batches:
      table: vw_live_product_information
      schema: ge
      data_asset_name: ge.vw_live_product_information
      datasource: database
    expectation_suite_names:
      - live_products_info.warning
      - live_products_info.failure
```

Running via the CLI:
```shell
great_expectations checkpoint run input_data
```
raises the `ValueError` from here: 
https://github.com/great-expectations/great_expectations/blob/6dc3f732826fe427b66de26d93b424302e929c23/great_expectations/validation_operators/validation_operators.py#L734

**Expected behavior**
To be able to use the `WarningAndFailureExpectationSuitesValidationOperator` example in the docs.

**Environment (please complete the following information):**
 - Operating System:  MacOS
 - Great Expectations Version: 0.13.14
