### ISSUE TITLE
[ENHANCEMENT] Add all partitions to checkpoint.

### ISSUE THREAD

**Issue by peterdhansen** [fivetran/great_expectations#2578]
If I define a data source using partitions, e.g.
```yml

  db:
    module_name: great_expectations.datasource
    connection_string: mssql+pyodbc://SERVER/DATABASE?driver=ODBC+Driver+17+for+SQL+Server&charset=utf&autocommit=true&Trusted_Connection=yes
    tables:
      TABLENAME:
        partitioners:
          random:
            splitter_method: _split_on_mod_integer
            splitter_kwargs:
              column_name: RandomId
              mod: 7
    class_name: SimpleSqlalchemyDatasource
```

It would be very useful if a SimpleCheckpoint can add all partitions since the number and definitions of partitions is sometimes unknown:

## Possible Syntax:

```yml
name: my_checkpoint
config_version: 1
class_name: SimpleCheckpoint
validations:
  - batch_request:
      datasource_name: db
      data_connector_name: random
      data_asset_name: TABLE_NAME
      partition_request: all

    expectation_suite_name: my_suite
```
