### ISSUE TITLE
Asset Name is not populated in Data Docs for SimpleSqlalchemy data source

### ISSUE THREAD

**Issue by xaniasd** [fivetran/great_expectations#2585]
**Describe the bug**
When using a SimpleSqlalchemy data source, the Asset Name column is not populated in the Validations index of the data docs. SImilarly, the Data Asset entry in the corresponding Validation result is None. 

**To Reproduce**
1. Configure a SimpleSqlalchemy datasource
```yaml
datasources:
  db:
    credentials: ${my_postgres_db}
    class_name: SimpleSqlalchemyDatasource
    introspection:
      whole_table: {}
``` 
2. Configure an expectation suite
3. Configure a SimpleCheckpoint  
```yaml
name: my_simple_checkpoint
config_version: 1.0
class_name: SimpleCheckpoint
expectation_suite_name: ge_validations_store.warning
validations:
  - batch_request:
      datasource_name: db
      data_connector_name: whole_table
      data_asset_name: ge_validations_store
      partition_request:
        index: -1
```
4. Run checkpoint my_simple_checkpoint
5. The generated data docs do not contain properly populated data asset entries

**Expected behavior**
The generated data docs should be populated the same way when using the v3 API as when using the v2 API

**Environment (please complete the following information):**
 - Operating System: Linux, MacOS
 - Great Expectations Version: develop branch
