### ISSUE TITLE
Automatically created datasource name gives KeyError (v3-api, CLI)

### ISSUE THREAD

**Issue by balexander** [fivetran/great_expectations#2740]
**Describe the bug**
The `data_asset_name` that is automatically created from the user-entered schema and table name is incorrect when creating a v3 suite via the CLI.

**To Reproduce**
1. Create a Redshift data source called `rs` via CLI. The output will look like this:
```
  rs:
    class_name: SimpleSqlalchemyDatasource
    introspection:
      whole_table:
        data_asset_name_suffix: __whole_table
    credentials: ${rs}
    module_name: great_expectations.datasource
```
2. Create a new expectation suite using the v3 api (`great_expectations --v3-api suite new`)
3. Select `Interactively, with a sample batch of data` when prompted
4. Select the data source
5. Select `Enter a table name and schema`. Enter `some_schema` and `content_table`.
6. A notebook opens with code to get print column names of the table. The batch request is 
```
batch_request = {'datasource_name': 'rs', 'data_connector_name': 'whole_table', 'data_asset_name':'some_schema.content_table', 'limit': 1000}
```
Execute that cell and there is a KeyError raised:
```
KeyError: 'data_asset_name some_schema.content_table is not recognized.'
```

**Expected behavior**
The BatchRequest should have the correct `data_asset_name`, in this case "content_table__whole_table".

**Environment (please complete the following information):**
 - MaxOS
 - Great Expectations Version 0.13.19

**Additional context**
I'm not sure if the data connector is returning the wrong data asset name or if the name generated in the notebook is incorrect.
