### ISSUE TITLE
Extremely slow initialization when using AWS Secrets Manager 

### ISSUE THREAD

**Issue by if-gh** [fivetran/great_expectations#2794]
**Describe the bug**
According to documentation [here](https://docs.greatexpectations.io/en/latest/guides/how_to_guides/configuring_data_contexts/how_to_populate_credentials_from_a_secrets_store.html) it is possible to use AWS SecretsManager as secret store, but when using this feature it becomes extremely slow even only running `context = great_expectations.get_context()`

**To Reproduce**
1. Defined `SimpleSqlalchemyDatasource` in `great_expectations.yml`:
    ```yaml
    config_version: 3
    datasources:
      my_datasource:
        introspection:
          whole_table:
            data_asset_name_suffix: __whole_table
        class_name: SimpleSqlalchemyDatasource
        module_name: great_expectations.datasource
        data_asset_type:
          class_name: CustomSqlAlchemyDataset
          module_name: custom_module.custom_dataset
        credentials:
          host: secret|arn:aws:secretsmanager:XX-XXXX-X:XXXXXXXXXXXX:secret:my_secret|host
          port: secret|arn:aws:secretsmanager:XX-XXXX-X:XXXXXXXXXXXX:secret:my_secret|port
          username: secret|arn:aws:secretsmanager:XX-XXXX-X:XXXXXXXXXXXX:secret:my_secret|username
          password: secret|arn:aws:secretsmanager:XX-XXXX-X:XXXXXXXXXXXX:secret:my_secret|password
          database: secret|arn:aws:secretsmanager:XX-XXXX-X:XXXXXXXXXXXX:secret:my_secret|database
          drivername: secret|arn:aws:secretsmanager:XX-XXXX-X:XXXXXXXXXXXX:secret:my_secret|drivername
    ```
2. Python script I ran:
    ```python
    import great_expectations as ge
    context = ge.get_context()
    ```
4. It took 4-5mins to even finish these two lines...

**Expected behavior**
Should have comparable speed comparing with putting plaintext credentials in `great_expectations.yml` or `config_variables.yml`

**Environment (please complete the following information):**
 - Operating System: MacOS, Python 3.7.10
 - Great Expectations Version: `0.13.19`

**Additional context**
I've tried profiling the scripts with `python -m cProfile my_script.py > profiling.txt`
when using plaintext credentials:
```
1926333 function calls (1875707 primitive calls) in 1.861 seconds
...
```
when using AWS Secrets Manager:
```
15270280 function calls (14827161 primitive calls) in 247.842 seconds
...
```
