### ISSUE TITLE
Leftover table on public schema when runing `expect_column_values_to_be_unique` expectation

### ISSUE THREAD

**Issue by shpolina** [fivetran/great_expectations#2843]
**Describe the bug**
After running an expectation suite with a single `expect_column_values_to_be_unique` expectation against RS table, there is a leftover table that is created on a public schema and remains there indefinitely.

On top of the inconvenience of having leftover tables, this has also a concern of unintended data exposure since the table goes to public schema.

Few notes:
* Even though these tables have `tmp` in their name, I am not sure they are actually temp tables. See [slack discussion](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1622571258136600?thread_ts=1622562094.136200&cid=CUTCNHN82)
* My batch request sets `"create_temp_table": False`, so I wouldn't expect temp tables to be created

<img src="https://user-images.githubusercontent.com/14918053/119748520-0fbcc000-be63-11eb-9340-829f4a9bde2c.png" width=20% height=20%>

**To Reproduce**
1. 
 Datasource config 
```
rs_datasource:
    class_name: Datasource
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      connection_string: ${connection_str}
      module_name: great_expectations.execution_engine
    module_name: great_expectations.datasource
    data_connectors:
      my_dc:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - some_identifier
  ```

Checkpoint config

```
name: my_cp
config_version: 1.0
module_name: great_expectations.checkpoint
class_name: Checkpoint
runtime_configuration: 
  result_format:
        result_format: COMPLETE
````

Batch request

Note: the table I am validating  is not on a default schema, hence I am passing the schema name to batch request. The passed schema is not `public`

```python
def create_runtime_batch_request(self, table: str, schema: str) -> RuntimeBatchRequest:
        table_w_schema = f"{str(schema)}.{table}"
        runtime_parameters = {"query": table_w_schema}  # note: this query looks wrong, but this is a workaround for issue #2821 
        batch_identifiers = {some_identifier: "my_id"}
        batch_spec_passthrough = {"create_temp_table": False, "table_name": table, "schema_name": schema}

        return RuntimeBatchRequest(
            datasource_name="rs_datasource",
            data_connector_name="my_dc",
            data_asset_name=table_w_schema,
            runtime_parameters=runtime_parameters,
            batch_identifiers=batch_identifiers,
            batch_spec_passthrough=batch_spec_passthrough,
        )
```

Expectation suite has a single expectation 
```
 {
      "expectation_type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "id"
      },
      "meta": {}
    },
```
2. run ```context.run_checkpoint(checkpoint_name="my_cp")```
3. Observe new table created on public schema of RS database which stays there indefinitely

**Expected behavior**
Nothing should be created on public schema

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.13.19

**Additional context**
This issue appears to be specific to expectations of a certain type that have method `_sqlalchemy_map_condition_unexpected_count_value,` set  as [metric provider](https://github.com/great-expectations/great_expectations/blob/4a08b90d080b1c5e03dbec88ace9f2a1a7bbb611/great_expectations/expectations/metrics/map_metric.py#L1312-L1321). The table creation occurs here
https://github.com/great-expectations/great_expectations/blob/4a08b90d080b1c5e03dbec88ace9f2a1a7bbb611/great_expectations/expectations/metrics/map_metric.py#L853-L860
