### ISSUE TITLE
BigQuery - expect.column_values_unique - module 'pybigquery.sqlalchemy_bigquery' has no attribute 'dialect' 

### ISSUE THREAD

**Issue by juan-meister** [fivetran/great_expectations#2978]
**Describe the bug**
When I try to launch a checkpoint using a BigQuery SQL Batch, there's an error related to `pybigquery`

**To Reproduce**
1. Create an expectation like this
```json
{
  "data_asset_type": null,
  "expectation_suite_name": "hubspot_company_suite",
  "expectations": [
    {
      "expectation_type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "name"
      },
      "meta": {
        "notes": {
          "content": "Test if the there are duplicates names in hubspot companies view",
          "format": "markdown"
        }
      }
    },
    {
      "expectation_type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "hs_object_id"
      },
      "meta": {
        "notes": {
          "content": "Test if the there are duplicates ids in hubspot companies view",
          "format": "markdown"
        }
      }
    }
  ],
  "meta": {
    "great_expectations_version": "0.13.20"
  }
}
```

2. Create a checkpoint, with this configuration
```yaml
name: hubspot_companies_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-my-run-name-template'
expectation_suite_name:
batch_request:
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: bq_prod
      data_connector_name: runtime_data_connector_meister_prod_connector
      data_asset_name: custom_sql_query
      runtime_parameters:
        query: SELECT * FROM `meister-bi-prod.dbt_juan.hubspot_companies`
      batch_identifiers:
        batch_meister_prod: 20210701-e3df29a8-d83d-4e3b-bada-9e9d88d841f0
    expectation_suite_name: hubspot_company_suite
profilers: []
ge_cloud_id:
````
```batch
File "<path>/site-packages/great_expectations/expectations/metrics/column_map_metrics/column_values_unique.py", line 66, in _sqlalchemy_window
    if sql_engine and dialect and dialect.dialect.name == "mysql":
AttributeError: module 'pybigquery.sqlalchemy_bigquery' has no attribute 'dialect'
```

**How to avoid the error**
Edit line 63 and put `dialect = None`
This allows GE to finish the checkpoint correctly

**Expected behavior**
Run the checkpoint correctly

**Environment (please complete the following information):**
 - MacOS Big Sur
 - Great Expectations Version: 0.13.21
