### ISSUE TITLE
S3 InvalidKeyError when S3 prefix for an Expectation Store is at the top level for the prefix

### ISSUE THREAD

**Issue by talagluck** [fivetran/great_expectations#3054]
**Describe the bug**
This is describing the bug found in #2993 . With the following error

> On S3 path looks like
> test_configless2/20210705T133824.449268Z/20210705T133824.449268Z/some_string.json
> 
> But I get an error
> 
> Unable to retrieve object from TupleS3StoreBackend with the following Key: test_configless2/20210705T133824/449268Z/20210705T133824/449268Z/some_string.json

If you specify the prefix of an ExpectationStore as purely the top level prefix, without a delimiter and another name afterward, this causes a failure, e.g.:

```yaml
# this will not work
  expectations_s3_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: "test_bucket"
      prefix: "my_prefix/" # does not have an additional word after the delimiter of the prefix

# this will work 
 expectations_s3_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: "test_bucket"
      prefix: "my_prefix/foo" # has an additional word after the delimiter of the prefix
```

This is the case whether the DataContext is being instantiated from a YAML or from an in-memory config. This may require S3 stores for Validations and DataDocs as well, though when these other stores lack the final word after the delimiter, this error does not occur.

**To Reproduce**
1. Create a Great Expectations project
2. Specify S3 Stores for Expectations, Validations, and Data Docs
3. Only include the top level "directory" in the prefix for the Expectations Store - ensure that there is nothing after the first delimiter.

**Expected behavior**
There should not be substitution happening between "." and "/" which appears to be causing an error.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.13.21
