### ISSUE TITLE
Not able to save Datasource Configuration

### ISSUE THREAD

**Issue by rremani** [fivetran/great_expectations#3097]
**Describe the bug**
While creating a new datasource connection using mysql dolt, the final saving yaml command is getting hanged "sanitize_yaml_and_save_datasource(context, example_yaml, overwrite_existing=False)", no issues with "context.test_yaml_config(yaml_config=example_yaml)" command.

**To Reproduce**
example yaml:
```
name: motor_datasource
class_name: Datasource
execution_engine:
  class_name: SqlAlchemyExecutionEngine
  connection_string: mysql+pymysql://root:@localhost:8765/motor_master
data_connectors:
  default_runtime_data_connector_name:
    class_name: RuntimeDataConnector
    batch_identifiers:
      - default_identifier_name
  default_inferred_data_connector_name:
    class_name: InferredAssetSqlDataConnector
    name: whole_table
```
