### ISSUE TITLE
Index page hosted on GCS failed to include the result of validations

### ISSUE THREAD

**Issue by tebesfinwo** [fivetran/great_expectations#3307]
**Describe the bug**

The index page hosted on GCS failed to include the result of validations with the following action list operator (`gcs_action_list_operators`). However, the result of the validations did get uploaded to the correct path in GCS when I ran the following action operators using `checkpoint run`.

Based on the modified and created timestamp of the index page in GCS, the index page itself did get refreshed but without the validation results. 

```
validation_operators:
  gcs_action_list_operators:
    class_name: ActionListValidationOperator
    action_list:
    - name: store_validation_result
      action:
        class_name: StoreValidationResultAction
        target_store_name: validations_store_gcs
    - name: update_data_docs
      action:
        class_name: UpdateDataDocsAction
        site_names:
        - gcs_site
    - name: send_slack_notification_on_validation_result
      action:
        class_name: SlackNotificationAction
        slack_webhook: foo_hook
        notify_on: all
        notify_with:
        - gcs_site
        renderer:
          module_name: great_expectations.render.renderer.slack_renderer
          class_name: SlackRenderer

stores:
  validations_store_gcs:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleGCSStoreBackend
      project: foo_project
      bucket: foo_bucket
      prefix: bar/validations

data_docs_sites:
  gcs_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleGCSStoreBackend
      project: foo_project
      bucket: foo_bucket
      prefix: bar
      base_public_path: www.foo.com
    site_index_builder:
      class_name: DefaultSiteIndexBuilder    
```

**To Reproduce**
1. Configure a checkpoint similar to the above example.
2. `great_expectations checkpoint run foo_checkpoint`

**Expected behavior**
I expect the index page to include the results of the validations. 

**Environment (please complete the following information):**
 - MacOS
 - 0.13.30

**Additional context**
I also suspect that the issue which may cause the result of validations not including in the index page also causes `data_docs` not getting included in the Slack notification.

**Comment by talagluck** [comment]
Hi @tebesfinwo - thank you for raising this issue! To clarify, is the validation `json` created and saved in the appropriate Validations Store, and just not linked on the index page? Or is it not getting created at all?

**Comment by tebesfinwo** [comment]
@talagluck 
Thanks for the response! 
Yes, the validation `json` did get created and saved in the appropriate Validation Store, and just not linked on the index page.

**Comment by talagluck** [comment]
Thanks, @tebesfinwo ! A couple of follow-ups If you rebuild data-docs again after seeing the validation `json` in the Validation Store, is it still not linked on the index page? 

Are validations other than the most recent one linked on the index page, or are they all missing?

**Comment by tebesfinwo** [comment]
@talagluck 
Thanks for the follow-up. 

> If you rebuild data-docs again after seeing the validation json in the Validation Store, is it still not linked on the index page?

Yes

> Are validations other than the most recent one linked on the index page, or are they all missing?

They are all missing from the index page despite they (the validations) are in the bucket.

The command which I used:
```
great_expectations docs build -y --site-name gcs_sit
```

**Comment by NathanFarmer** [comment]
@tebesfinwo I am looking into this and I will follow up in the next day or two.

**Comment by NathanFarmer** [comment]
Hi @tebesfinwo! In GCS `foo_bucket/bar/validations` do you see `html` files that should be generated when you build the data docs? I think there is some confusion here about the `validation store` versus the `data docs`. You seem to have pointed to the same directory for both. Data docs builds and updates a directory called `validations` that would be hosted in `foo_bucket/bar/validations` this is intended to host the `html` files. The `validation store` would typically be in a directory at `foo_bucket/validations` and the `json` validation results would be hosted there. I suspect due to the identical naming conventions directories are being overwritten. Try changing the prefix in your validation store config like this:
```
stores:
  validations_store_gcs:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleGCSStoreBackend
      project: foo_project
      bucket: foo_bucket
      prefix: validations
```
