### ISSUE TITLE
V3 API:  Default schema for Redshift not available

### ISSUE THREAD

**Issue by lifeofabit** [fivetran/great_expectations#3561]
**Describe the bug**
I'm not able to define a default schema for use with the Redshift SQLAlchemy data source. This is available in V2, so I'm not sure if this is a bug or a new feature request for the V3 API. There's no option to specify the schema when utilizing `great_expectations --v3-api datasource new`.  When creating new expectations, it seems like the profiler picks a schema at random (or maybe the first available) and chooses databases from there.  I had also tried a workaround by adding `schema_name` in the `great_expectations.yml` file based on metadata I found in the data docs, but I was getting a warning telling me to make a database level change.  I talked to Ben on Slack about this and he suggested I post this warning in the issue.  Additionally, per a suggestion from Ben, tried to set up the config in `great_expectations.yml` like a Snowflake SQLAlchemy data source, but it wouldn't register properly (stated no datasource available after the change).

**To Reproduce**
Steps to reproduce the warning:
1. Create a new Redshift datasource with `great_expectations --v3-api datasource new`
2. Insert `schema_name` as a key under datasource credentials in the `great_expectations.yml` file.  Config looks like the following:
```
datasources:
  my_redshift_cluster:
    class_name: Datasource
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      credentials:
        host: my_host_name
        port: '5439'
        username: my_username
        password: my_password
        database: my_database
        query:
          sslmode: prefer
        drivername: postgresql+psycopg2
        schema_name: my_schema
      module_name: great_expectations.execution_engine
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
    module_name: great_expectations.datasource
```
3. Run any great expectations command from the CLI like `great_expectations --v3-api suite list`
4. See warning in the request:
```
$ great_expectations --v3-api suite list
Using v3 (Batch Request) API
schema_name specified creating a URL with schema is not supported. Set a default schema on the user connecting to your database.
1 Expectation Suites found:
 - dim.test
```

**Expected behavior**
Default schema to be applied when creating expectations, checkpoints, etc.  The warning makes sense if trying to assemble the connection string with the schema.  But I figured this would be possible since it can be done in the V2 API

**Environment (please complete the following information):**
 - Operating System: MacOS Big Sur
 - Great Expectations Version: 0.13.37
 - Other Package Versions:
```
SQLAlchemy          1.4.25
sqlalchemy-redshift 0.8.6 
```

**Comment by jcampbell** [comment]
Hey @lifeofabit  -- I think the issue is that the message is really confusing, but the problem is that sqlalchemy doesn't support setting a schema using the piecemeal URL construction. So, I think you should be able to make this work by changing your configuration to provide a connection string instead: 

```
datasources:
  my_redshift_cluster:
    class_name: Datasource
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      credentials:
        connection_string: postgresql+psycopg2://user:pass@host:port/db/schema?sslmode=prefer
      module_name: great_expectations.execution_engine
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
    module_name: great_expectations.datasource
```

Do you have an example of the previous config that worked in v2? I wonder if it was just building the connection string and using that...

Does this config work for you?
