### ISSUE TITLE
pyspark.sql.utils.AnalysisException: "Table or view not found:  when creating an expectations suite

### ISSUE THREAD

**Issue by jpoullet2000** [fivetran/great_expectations#3575]
**Describe the bug**
Hive metastore is not found, and so the hive table is not found.

**To Reproduce**
When running 
```
great_expectations suite scaffold ge_demo_tbl.warning
```
I always get `pyspark.sql.utils.AnalysisException: "Table or view not found:`

**Expected behavior**
It seems that it cannot connect to the hive metastore. 

I tried to set up the environment variables `HADOOP_CONF_DIR`, `SPARK_HOME` and `HIVE_CONF_DIR` (using `export` in bash, or even using os.environ[VAR] = path) in vain. 

I also tried to replace the line `builder = SparkSession.builder` in `core/util.py` by `builder = SparkSession.builder.enableHiveSupport()` without more success.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.13.37

**Additional context**
My `great_expectations.yml` file 

```
datasources:
  spark_dataframe:
    data_asset_type:
      class_name: SparkDFDataset
      module_name: great_expectations.dataset
    batch_kwargs_generators:
      spark_sql_query:
        class_name: QueryBatchKwargsGenerator
        queries:
          'explanation_table': 'select count(*) from mydb.mytable' 
    module_name: great_expectations.datasource
    class_name: SparkDFDatasource
```
