### ISSUE TITLE
Incorrect stdout for ConfiguredAssetFilesystemDataConnector "Unmatched data_references" with multiple configured Data Assets

### ISSUE THREAD

**Issue by NathanFarmer** [fivetran/great_expectations#3589]
**Describe the bug**
When multiple Data Assets are configured using `ConfiguredAssetFilesystemDataConnector` the stdout produced incorrectly references all files as being `Unmatched data_references`.

```
Data Connectors:
  default_configured_data_connector_name : ConfiguredAssetFilesystemDataConnector

  Available data_asset_names (2 of 2):
    green_tripdata (3 of 3): ['green_tripdata_2019-01.csv', 'green_tripdata_2019-02.csv', 'green_tripdata_2019-03.csv']
    yellow_tripdata (3 of 3): ['yellow_tripdata_2019-01.csv', 'yellow_tripdata_2019-02.csv', 'yellow_tripdata_2019-03.csv']

  Unmatched data_references (3 of 6):['yellow_tripdata_2019-01.csv', 'yellow_tripdata_2019-02.csv', 'yellow_tripdata_2019-03.csv']
```

**To Reproduce**
1. Given the following files in `<MY DIRECTORY>/`:

```
<MY DIRECTORY>/yellow_tripdata_2019-01.csv
<MY DIRECTORY>/green_tripdata_2019-01.csv
<MY DIRECTORY>/yellow_tripdata_2019-02.csv
<MY DIRECTORY>/green_tripdata_2019-02.csv
<MY DIRECTORY>/yellow_tripdata_2019-03.csv
<MY DIRECTORY>/green_tripdata_2019-03.csv
```

2. Configure a new datasource with either of these configurations:

YAML:
```
datasource_yaml = """
name: taxi_datasource
class_name: Datasource
module_name: great_expectations.datasource
execution_engine:
  module_name: great_expectations.execution_engine
  class_name: PandasExecutionEngine
data_connectors:
  default_configured_data_connector_name:
    class_name: ConfiguredAssetFilesystemDataConnector
    base_directory: <MY DIRECTORY>/
    assets:
      yellow_tripdata:
        pattern: yellow_tripdata_(\d{4})-(\d{2})\.csv
        group_names:
          - year
          - month
      green_tripdata:
        pattern: green_tripdata_(\d{4})-(\d{2})\.csv
        group_names:
          - year
          - month        
"""
```

Python:
```
datasource_config = {
    "name": "taxi_datasource",
    "class_name": "Datasource",
    "module_name": "great_expectations.datasource",
    "execution_engine": {
        "module_name": "great_expectations.execution_engine",
        "class_name": "PandasExecutionEngine",
    },
    "data_connectors": {
        "default_configured_data_connector_name": {
            "class_name": "ConfiguredAssetFilesystemDataConnector",
            "base_directory": "<MY DIRECTORY>/",
            "assets": {
                "yellow_tripdata": {
                    "pattern": "yellow_tripdata_(\d{4})-(\d{2})\.csv",
                    "group_names": ["year", "month"],
                },
                "green_tripdata": {
                    "pattern": "green_tripdata_(\d{4})-(\d{2})\.csv",
                    "group_names": ["year", "month"],
                }
            },
        },
    },
}
```

3. Run:
`context.test_yaml_config(yaml.dump(datasource_config))`
or
`context.test_yaml_config(datasource_yaml)`
4. Observe stdout

**Expected behavior**
Stdout should read:
```
Data Connectors:
  default_configured_data_connector_name : ConfiguredAssetFilesystemDataConnector

  Available data_asset_names (2 of 2):
    green_tripdata (3 of 3): ['green_tripdata_2019-01.csv', 'green_tripdata_2019-02.csv', 'green_tripdata_2019-03.csv']
    yellow_tripdata (3 of 3): ['yellow_tripdata_2019-01.csv', 'yellow_tripdata_2019-02.csv', 'yellow_tripdata_2019-03.csv']

  Unmatched data_references (0 of 0):[]
```

**Environment (please complete the following information):**
 - macOS Big Sur 11.6
 - Great Expectations 0.13.38
