### ISSUE TITLE
`$` in yaml password read as variable needing substitution

### ISSUE THREAD

**Issue by justin-mlbrry** [fivetran/great_expectations#3820]
**Describe the bug**
I am trying to initialize a new database connection using the provided notebook `datasource_new`. My password has a `$` in it, and this is being interpreted as a need to insert a variable. 

**To Reproduce**
YAML looks like this:
```
name: training_db
class_name: Datasource
execution_engine:
  class_name: SqlAlchemyExecutionEngine
  credentials:
    host: ${HOST}
    port: '5432'
    username: ${USER}
    password: ${PASSWORD}
    database: ${DB}
    drivername: postgresql
data_connectors:
  default_runtime_data_connector_name:
    class_name: RuntimeDataConnector
    batch_identifiers:
      - default_identifier_name
  default_inferred_data_connector_name:
    class_name: InferredAssetSqlDataConnector
    name: whole_table
```

`PASSWORD` is an environment variable. Error is:
```
Unable to find a match for config substitution variable: `{removing since part of my password}`.
Please add this missing variable to your `uncommitted/config_variables.yml` file or your environment variables.
```

**Expected behavior**
Once the environment variable has been read, there should be no further substitution. The password should be used as is.

**Environment (please complete the following information):**
 - MacOS
 - great_expectations, version 0.13.45

**Additional context**
None
