### ISSUE TITLE
The Prefix setting for doc domain not work

### ISSUE THREAD

**Issue by damon09273** [fivetran/great_expectations#3847]
**Describe the bug**
I want the great exception doc can be access in a custom path of my domain (e.g `http.mydomain.com/ge/index.html`),
I use the `prefix` in data_docs_sites, but not work.

It’s able to get index.html at: http.mydomain.com/ge/index.html,
but I got 404 when I click the links that listing in the index page, because the link miss the `ge` in path: `http.mydomain.com/validations/x/x.html`

**To Reproduce**
1. set a config
```
gcs_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleGCSStoreBackend
      project: ${GOOGLE_CLOUD_PROJECT}
      bucket: bucket
      prefix: ge
      base_public_path: https://mydomain.com/ge
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```

2. Access the `index.html` directly on browser e.g http.mydomain.com/ge/index.html
3. Click the links that listing in the `index.html` e.g Expectation list.

**Expected behavior**
After click the link, return 200, and link value is ` http.mydomain.com/ge/validations/x/x.html`.
The `/ge/` must same as the `prefix` setting in doc_site.

**Environment (please complete the following information):**
 - Linux, MacOS
 - Great Expectations Version: 0.13.41
 - airflow-provider-great-expectations: 0.0.8
 - pybigquery: 0.10.2
 - Gcloud SDK: 258.0.0
 
**Additional context**
I follow this [official article](https://legacy.docs.greatexpectations.io/en/stable/guides/how_to_guides/configuring_data_docs/how_to_host_and_share_data_docs_on_gcs.html) to setup my server.

**Comment by cdkini** [comment]
Hey @damon09273 thanks for opening up this issue! Would you mind providing us with your configuration details (making sure to omit any sensitive information)?

**Comment by damon09273** [comment]
@cdkini ok!

GCS file paths

```
gs://ge/index.html
gs://ge/validations/
gs://ge/static/
```


app.py
```
import logging
import os

from flask import Flask, request
from google.cloud import storage

app = Flask(__name__)
# Configure this environment variable via app.yaml
CLOUD_STORAGE_BUCKET = os.environ["CLOUD_STORAGE_BUCKET"]


@app.route("/", defaults={"path": "ge/index.html"})
@app.route("ge/<path:path>")
def index(path):
    gcs = storage.Client()
    bucket = gcs.get_bucket(CLOUD_STORAGE_BUCKET)
    try:
        blob = bucket.get_blob(path)
        content = blob.download_as_string()
        if blob.content_encoding:
            resource = content.decode(blob.content_encoding)
        else:
            resource = content
    except Exception as e:
        logging.exception("couldn't get blob")
        resource = "<p></p>"
    return resource


@app.route("/healthcheck")
def healthcheck():
    return ""


@app.errorhandler(500)
def server_error(e):
    logging.exception("An error occurred during a request.")
    return (
        """
    An internal error occurred: <pre>{}</pre>
    See logs for full stacktrace.
    """.format(
            e
        ),
        500,
    )


if __name__ == "__main__":
    app.run(host="0.0.0.0", port="8080")
```

checkpoint.py
```
def run(context):
    context = ge.data_context.DataContext(
        context_root_dir="xx/great_expectations"
    )


    suite_name = ""
    suite = find_or_create_suite(context, suite_name, expectations)
    sql = ""

    batch_request = RuntimeBatchRequest(
        datasource_name="bigquery",
        data_connector_name="default_runtime_data_connector_name",
        data_asset_name="default_name",
        runtime_parameters={"query": sql},
        batch_identifiers={"default_identifier_name": "default_identifier"},
        batch_spec_passthrough={
            "bigquery_temp_table": suite_name,
        },
    )

    checkpoint_config = {
        "run_name_template": f"%Y%m%d-%H%M%S-{suite_name}",
        "class_name": "SimpleCheckpoint",
        "validations": [
            {
                "batch_request": batch_request.to_json_dict(),
                "expectation_suite_name": suite_name,
            }
        ],
    }
    checkpoint = SimpleCheckpoint("realtime validation", context, **checkpoint_config)
    results = checkpoint.run()

```


great_expectations.yml
```
config_version: 3.0
datasources:
  bigquery:
    class_name: Datasource
    module_name: great_expectations.datasource
    data_connectors:
      default_runtime_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
      default_inferred_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        class_name: InferredAssetSqlDataConnector
    execution_engine:
      connection_string: bigquery://${BIGQUERY_PROJECT}/great_exceptions
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
  gcs_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleGCSStoreBackend
      project: ${GOOGLE_CLOUD_PROJECT}
      prefix: ge
      bucket: dcard-great-expectation
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  enabled: false
notebooks:
concurrency:
  enabled: false
```
