### ISSUE TITLE
DataDocs under uncommitted folder

### ISSUE THREAD

**Issue by eduardagoulart** [fivetran/great_expectations#3848]
**Is your feature request related to a problem? Please describe.**
The tool right now has a great visualization inside the dataDocs. However, the dataDocs is getting created under the uncommitted folder, that is ignored by a .gitignore.

This makes the understanding and sharing visualization in a pipeline that uses GreatExpectation a bit harder. I'm wondering why the DataDocs has to be created inside an uncommitted folder.

**Describe the solution you'd like**
Have the datadocs visualization getting created outside the uncommitted folder

**Describe alternatives you've considered**
-

**Additional context**
N/A

**Comment by cdkini** [comment]
Hey @eduardagoulart thanks for opening up this issue. We default to that location to protect against the possibility of leaking sensitive information. If you'd like to change the path, please alter your configuration in your `great_expectations.yml`.

Here's the relevant snippet to change:
```yaml
data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/en/latest/reference/core_concepts/data_docs.html
  local_site:
    class_name: SiteBuilder
    # set to false to hide how-to buttons in Data Docs
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```

Please note that you may have to create the directory and any subdirectories in advance. I'll go ahead and close this issue down for now but please feel free to reopen if you're running into issues. Thanks!
