### ISSUE TITLE
weird config error for gcs connector

### ISSUE THREAD

**Issue by TiansuYu** [fivetran/great_expectations#3937]
**Describe the bug**
I have encounterred the following bug while trying to setup a suite for my data in GCS: 
```
InvalidConfigError: Your current configuration uses one or more keys in a data connector that are required only by a
filesystem type of the data connector (your data connector is "ConfiguredAssetGCSDataConnector").  Please update your
configuration to continue.
```

I find the error message is rather hard to understand, hope here someone could help pointing out what is the real issue. 

**To Reproduce**

The config that I have used is the following: 
```
datasources:
  wikitext-103:
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: SparkDFExecutionEngine
    data_connectors:
      default_inferred_data_connector_name:
        class_name: ConfiguredAssetGCSDataConnector
        base_directory: gs://<mu-bucket>/<my-dataset>/
        glob_directive: "*/*.json.gz"
        assets:
            train:
                pattern: "*.json.gz"
            valid:
                pattern: "*.json.gz"
            test:
                pattern: "*.json.gz"
        module_name: great_expectations.datasource.data_connector
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
    module_name: great_expectations.datasource
    class_name: Datasource
```
The file structure is that under `<my-dataset>` there are three "folders" named `train`, `valid`, and `test`, each containing several `json.gz` files. 

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 3
