### ISSUE TITLE
Silent overwrites of validation results stored in database when actions have the same name 

### ISSUE THREAD

**Issue by eculicny** [fivetran/great_expectations#3966]
**Describe the bug**
Identically named actions should have their configuration updated or appended as mentioned [here](https://docs.greatexpectations.io/docs/reference/checkpoints_and_actions/#configuration-defaults-and-parameter-override-behavior). However, the action will fire off for each config occurrence _with_ the updated configuration as opposed to a single action with the latest version of the configuration or two actions with different configurations.

This seems to possibly be expected behavior due to the `action_list` also being in the `Appended` section, but the following text in both places of "actions that share the same user-defined name will be updated, otherwise a new action will be appended" would indicate "Appended" and "Updated" states are mutually exclusive and would only ever end up in the "Updated" state.

A side effect of the same name Appending and Updating the actions is the potential loss of data in a database validation store since the second action against the datastore will update the records that match the `expectation_suite_name` while ignoring the other key columns located [here](https://github.com/great-expectations/great_expectations/blob/98a8ad23652eb2633f11026d51a00802ced8499b/great_expectations/data_context/store/database_store_backend.py#L260-L262)

**To Reproduce**
1. Setup any basic checkpoint `test.checkpoint` (still using v2)
2. Have the following config for the `action_list`
```
validation_operators:
  action_list_operator:
    class_name: ActionListValidationOperator
    action_list:
    - name: store_validation_result
      action:
        class_name: StoreValidationResultAction
        target_store_name: validations_store_filesystem
    - name: store_validation_result
      action:
        class_name: StoreValidationResultAction
        target_store_name: validations_store_postgres
...
stores:
  validations_store_filesystem:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/
  validations_store_postgres:
    class_name: ValidationsStore
    store_backend:
      class_name: DatabaseStoreBackend
      credentials:
        drivername: postgresql
        username: postgres
        password: postgres
        host: data_warehouse  # running postgres container name
        database: postgres
        port: 5432
```
where `validations_store_filesystem` is a configured local filesystem store, and the `validations_store_postgres` is a configured DB store.
3. Execute `great_expectations checkpoint run test.checkpoint`
4. No file should be written to the local filesystem. An insert statement followed by an update statement should be issued to the DB store (insert a row and then update all matching rows with the same data)
5. Execute `great_expectations checkpoint run test.checkpoint` again
6. No file should be written to the local filesystem. An insert statement followed by an update statement should be issued to the DB store.
7. The original entry from step (3) will have been updated by the update statement issued from step (5) resulting in the loss of the original validation data.

**Expected behavior**
In the above case, we should expect the Action to only fire off _once_ against the DB store since the actions have the same name which would result in the item in the `action_list` being updated and not appended.

I would also expect that the case of the action being updated and appended to _not_ update all DB store records matching the name by default resulting in data loss in a valid (although confusing and contrived) configuration.

**Environment (please complete the following information):**
 - Operating System: Debian (python3.7 docker image)
 - Great Expectations Version: 0.13.43

**Additional context**
Nothing at the moment. Can add more if needed.
