### ISSUE TITLE
Sampling of data batches configuration is ignored for Athena tables

### ISSUE THREAD

**Issue by houqi2018** [fivetran/great_expectations#4030]
**Describe the bug**
Sampling configurations for Athena tables are ignored or don't help improve the performance when generating a validator.

**To Reproduce**
1. Use the following YAML config (Replace `test_table_name` and `test_schema_name` with valid names)
**IMPORTANT**: Please use a large table to see the difference.
```
config_version: 3.0

datasources:
  my_athena:
    data_connectors:
      default_configured_data_connector_name:
        class_name: ConfiguredAssetSqlDataConnector
        assets:
          test_table_name:
            class_name: Asset
            module_name: great_expectations.datasource.data_connector.asset
            include_schema_name: True
            schema_name: test_schema_name
            tables:
              test_table_name:
                partitioners:
                  whole_table:
                  include_schema_name: True
                  schema_name: test_schema_name
                  splitter_method: _split_on_column_value
                  splitter_kwargs:
                    column_name: test_column_name
                    sampling_method: _sample_using_random
                    sampling_kwargs:
                      p: 1.0e-1
        module_name: great_expectations.datasource.data_connector
    execution_engine:
      connection_string: awsathena+rest://:@athena.us-east-1.amazonaws.com:445?work_group=primary
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
    class_name: Datasource
    module_name: great_expectations.datasource

config_variables_file_path: config_variables.yml

plugins_directory: plugins/

stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

```
2. Execute the following command on CLI
```
great_expectations suite new
```
3. Select option 2
How would you like to create your Expectation Suite?
    1. Manually, without interacting with a sample batch of data (default)
    2. Interactively, with a sample batch of data
    3. Automatically, using a profiler
4. Select option 1 (Expect to see the real table name instead of the placeholder)
Which data asset (accessible by data connector "default_configured_data_connector_name") would you like to use?
    1. test_table_name

5. Open the Jupyter Notebook
6. Run the first autogenerated code section
7. Observe the amount of time it takes to get the validator. You may get a time-out. Or alternatively go into Athena console to inspect the recent query
8. Expect to see the full table being scanned

**Expected behavior**
When using the `ConfiguredAssetSqlDataConnector` with sampling configs per this [How to configure a DataConnector for splitting and sampling tables in SQL tutorial](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql/), `get_validator()` is supposed to only scan part of the identified table instead of scanning the entire table.

**Environment:**
 - Operating System: MacOS
 - Great Expectations Version: 0.14.1

**Additional context**
The `get_validator()` method by default scans the entire table using the below query constructed by [this _build_selectable_from_batch_spec method](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/execution_engine/sqlalchemy_execution_engine.py#L1060-L1066).
```
SELECT * FROM <schema_name>.<table_name> WHERE True
```
Another way to test it is to comment out the `table` attribute in YAML and rerun the steps. Expect the same amount of time needed to get the validator. This means the sampling config that we passed in earlier is not preventing Athena to query the entire table.
```
...
datasources:
  my_athena:
    data_connectors:
      default_configured_data_connector_name:
        class_name: ConfiguredAssetSqlDataConnector
        assets:
          test_table_name:
            class_name: Asset
            module_name: great_expectations.datasource.data_connector.asset
            include_schema_name: True
            schema_name: test_schema_name
            # tables:
            #   test_table_name:
            #     partitioners:
            #       whole_table:
            #       include_schema_name: True
            #       schema_name: test_schema_name
            #       splitter_method: _split_on_column_value
            #       splitter_kwargs:
            #         column_name: test_column_name
            #         sampling_method: _sample_using_random
            #         sampling_kwargs:
            #           p: 1.0e-1
...
```

**Comment by AFineDayFor** [comment]
Howdy @houqi2018, thanks for reaching out. Can you compare the number of rows returned in each batch; where you are and where you are not using the splitter.

**Comment by houqi2018** [comment]
Hi @AFineDayFor, I've run the notebook using different data assets (different schema names and table names). I noticed when I used a small table, the `getValidator()` method was executed quickly and the numbers of rows scanned were the same, i.e., the entire table. However, when I tried the same with a large table, the method timed out and I couldn't compare the results. Let me know if this is what you were looking for and if you need any additional context. Thanks!

**Comment by Shinnnyshinshin** [comment]
Hi @houqi2018 thank you for bringing this up. You are using a `ConfiguredAssetSqlDataConnector`, which currently does not support sampling and splitting, so the lack of speed gain may be from the splitting and sampling directive not being recognized / executed. This a known bug that we are working on resolving. 

The [documentation on splitting and sampling](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql) uses an `SimpleSqlalchemyDatasource` in the example, and I was able to confirm that the following configuration works on our end: 

```yaml

datasources:
  my_simple_athena:
    class_name: SimpleSqlalchemyDatasource
    connection_string: **your_connection_string**
    tables:
      **your_table**:
        partitioners:
          by_num_riders_random_sample:
            include_schema_name: True
            schema_name: **your_schema_name**
            splitter_method: _split_on_column_value
            splitter_kwargs:
              column_name: **your_column_name**
            sampling_method: _sample_using_random
            sampling_kwargs:
              p: 1.0e-1
```
 
Would you be able to test it on your table and see if the `_split_on_column_value` gives the expected result?
