### ISSUE TITLE
Cannot initialize datasource: Could not parse rfc1738 URL from string

### ISSUE THREAD

**Issue by Akselkv** [fivetran/great_expectations#4037]
**Describe the bug**
I get the following error when trying to initialize an MSSQL Server database as an datasource with release 0.14.1, which I didn't get with the old version (0.13.35) i was using: 
```
DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn(f"Cannot initialize datasource {datasource_name}: {e}")
Cannot initialize datasource riskdb: Cannot initialize datasource riskdb, error: Could not parse rfc1738 URL from string '{'url': 'mssql+pyodbc://@<server>/<database>?trusted_connection=yes&driver=ODBC Driver 17 for SQL Server&charset=utf&autocommit=true'}'
```
**To Reproduce**
Using following datasource config:
```
# Welcome to Great Expectations! Always know what to expect from your data.
#
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/en/latest/how_to_guides/spare_parts/data_context_reference.html#configuration
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 3.0

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/en/latest/reference/core_concepts/datasource_reference.html
datasources:
  riskdb:
    module_name: great_expectations.datasource
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
    class_name: Datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
      connection_string: ${riskdb}
  data:
    module_name: great_expectations.datasource
    data_connectors:
      default_inferred_data_connector_name:
        class_name: InferredAssetFilesystemDataConnector
        default_regex:
          group_names:
            - data_asset_name
          pattern: (.*)
        module_name: great_expectations.datasource.data_connector
        base_directory: ..\data
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
    class_name: Datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: PandasExecutionEngine
# config_variables_file_path: uncommitted/config_variables.yml
# We can safely commit connection string since we do not use passwords.
config_variables_file_path: config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
  # Stores are configurable places to store things like Expectations, Validations
  # Data Docs, and more. These are for advanced users only - most users can simply
  # leave this section alone.
  #
  # Three stores are required: expectations, validations, and
  # evaluation_parameters, and must exist with a valid store entry. Additional
  # stores can be configured for uses such as data_docs, validation_operators, etc.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      # base_directory: uncommitted/validations/
      base_directory: ../docs/validations

  evaluation_parameter_store:
    # Evaluation Parameters enable dynamic expectations. Read more here:
    # https://docs.greatexpectations.io/en/latest/reference/core_concepts/evaluation_parameters.html
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: checkpoints/
expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/en/latest/reference/core_concepts/data_docs.html
  local_site:
    class_name: SiteBuilder
    # set to false to hide how-to buttons in Data Docs
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: ../docs
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```

The `${riskdb}`-variable is found in `config_variables.yml`, which contains the following:
```
riskdb:
  url: mssql+pyodbc://@<server>/<database>?trusted_connection=yes&driver=ODBC
    Driver 17 for SQL Server&charset=utf&autocommit=true
```

**Expected behavior**
Being able to initialize a datasource connecting me to the database in the url.

**Environment (please complete the following information):**
 - Operating System: Windows 10 Enterprise
 - Great Expectations Version: 0.14.1
 - Python: 3.7.9
 - SQLAlchemy version: 1.4.29
 - pyodbc: 4.0.32

**Additional context**
