### ISSUE TITLE
OperationalError when running Checkpoint with MySQL 5.7.19

### ISSUE THREAD

**Issue by hy951221** [fivetran/great_expectations#4168]
**Describe the bug**
I am new to the project. I was able to go through the tutorials without problems until I tried to run checkpoint with my data asset  from MySQL database, it prompted the following error:

`OperationalError: (pymysql.err.OperationalError) (1787, 'Statement violates GTID consistency: CREATE TEMPORARY TABLE and DROP TEMPORARY TABLE can only be executed outside transactional context.  These statements are also not allowed in a function or trigger because functions and triggers are also considered to be multi-statement transactions.')
[SQL: CREATE TEMPORARY TABLE ge_temp_f1ed722a AS SELECT * 
FROM deploy.dw_userneed 
WHERE true = 1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)` 

I have been searching for a solutions all around but to no avail. Please help :( 

**To Reproduce**
1.Run Checkpoint with MySQL 5.7.19 datasource

**Expected behavior**
A validation result of the Checkpoint presents.

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: 0.14.0

**Comment by austiezr** [comment]
Hey @hy951221 ! Thanks for reaching out about this. MySQL doesn't allow the creation of temp tables in this context until v8.0.13; see [their docs here](https://dev.mysql.com/blog-archive/temporary-tables-are-now-allowed-in-transactions-when-gtids-are-enabled/). 

If you aren't able to come up to at least MySQL 8.0.13, you should also be able to pass `create_temp_table` as `False` as part of a `batch_spec_passthrough` in your Batch Request.

For example, here is a modification of the `yaml_config` used in the [Getting Started tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_validate_data), with a `batch_spec_passthrough` and the `create_temp_table` key:

```
yaml_config = f"""
name: getting_started_checkpoint
config_version: 1.0
class_name: SimpleCheckpoint
run_name_template: "%Y%m%d-%H%M%S-my-run-name-template"
validations:
  - batch_request:
      datasource_name: getting_started_datasource
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: yellow_tripdata_sample_2019-02.csv
      data_connector_query:
        index: -1
      batch_spec_passthrough:
        create_temp_table: False
    expectation_suite_name: getting_started_expectation_suite_taxi.demo
"""
```
