### ISSUE TITLE
Operators not working with URNs

### ISSUE THREAD

**Issue by cameronezell** [fivetran/great_expectations#4296]
**Describe the bug**
When calling a URN as an evaluation parameter, the code is correctly parsing the URN to get the value. But when an operator is applied, great_expectations returns the error `Error while evaluating evaluation parameter expression: could not convert string to float`

**To Reproduce**
1. Create a query store such as
```
 my_query_store:
   class_name: SqlAlchemyQueryStore
   credentials: 
    url: snowflake://${SNOWFLAKE_USER}:${SNOWFLAKE_PASSWORD}@acct.us-east-1/db-name/schema?warehouse=warehouse&role=role
   queries:
     current_max_spend:
       query: "SELECT MAX(spend_amt_usd)::integer from schema.spend_table;"
       return_type: "scalar"
```
2. Create an expectation config referencing the URN with some math operation following the URN:
```
{
        "expectation_context": {
          "description": "spend should not exceed 5% above max"
        },
        "expectation_type": "expect_column_values_to_be_between",
        "ge_cloud_id": null,
        "kwargs": {
          "column": "spend_amt_usd",
          "max_value": {"$PARAMETER": "urn:great_expectations:stores:my_query_store:current_max_spend * 1.05"},
          "min_value": 0
        },
        "meta": {}
      }
```
3. Evaluate against this expectation to see the error `Error while evaluating evaluation parameter expression: could not convert string to float: 'urn:great-expectations:stores:my_query_store:current_max_spend'`

**Expected behavior**
The URN should be evaluated as a numeric value

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.14.7

**Additional context**
[Slack discussion](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1645655413812009)
