### ISSUE TITLE
Miss configured AssetConfigSchema

### ISSUE THREAD

**Issue by MajorDaxx** [fivetran/great_expectations#4402]
**Describe the bug**
To instantiate a Data Source theres the possibility via [`context.test_yaml_config(yaml_config)`](https://github.com/great-expectations/great_expectations/blob/f867baf041a4c06517b3cd843bd3624205aad6af/great_expectations/data_context/data_context.py#L3384)

This function leads to a [schema check ](https://github.com/great-expectations/great_expectations/blob/f867baf041a4c06517b3cd843bd3624205aad6af/great_expectations/data_context/data_context.py#L1936).
If you wanna use a [ConfiguredAssetSqlDataConnector](https://github.com/great-expectations/great_expectations/blob/ebce61654d4bc1882d9f6db5b13ace07142977b3/great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py#L27) you need to configure Assets. 
The config of these assets is used to [config sampling_method ](https://github.com/great-expectations/great_expectations/blob/ebce61654d4bc1882d9f6db5b13ace07142977b3/great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py#L110) for example. 

Unfortunately the [schema of Assets](https://github.com/great-expectations/great_expectations/blob/f867baf041a4c06517b3cd843bd3624205aad6af/great_expectations/data_context/types/base.py#L181) as well as the [class](https://github.com/great-expectations/great_expectations/blob/74b51e78baccc66d55cf844a9c00991a0dd5267b/great_expectations/datasource/data_connector/asset/asset.py#L7) are not ment to store any config related to splitting. 
So in the Schema Check the fields related to splitting get removed.
https://github.com/great-expectations/great_expectations/blob/f867baf041a4c06517b3cd843bd3624205aad6af/great_expectations/data_context/data_context.py#L1936

Also it looks like the  ConfiguredAssetSqlDataConnector dont even store the Data Asses As Asset Class Objects. 
https://github.com/great-expectations/great_expectations/blob/ebce61654d4bc1882d9f6db5b13ace07142977b3/great_expectations/datasource/data_connector/configured_asset_sql_data_connector.py#L48-L50

**To Reproduce**
Sample yaml as input:
```
name: {datasource_name}
class_name: Datasource
execution_engine:
  class_name: SqlAlchemyExecutionEngine
  connection_string: {connection_string}
data_connectors:
  asset_based_connections:
    class_name: ConfiguredAssetSqlDataConnector
    assets:
        dummy_asset:
            table_name: baluuu
            schema_name: foo
            splitter_method: _split_on_column_value
            splitter_kwargs:
                column_name: pickup_datetime 
```

but lead to this configuration in the `great_expectations.yml`

```
datasources:
  asset_based_datasource:
    module_name: great_expectations.datasource
    data_connectors:
      asset_based_connections:
        module_name: great_expectations.datasource.data_connector
        class_name: ConfiguredAssetSqlDataConnector
        assets:
          dummy_asset:
            class_name: Asset
            module_name: great_expectations.datasource.data_connector.asset
            schema_name: foo
            table_name: baluuu
    class_name: Datasource
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
      connection_string: bigquery://project/temporary
```

**Expected behaviour**
The ConfiguredAssetSqlDataConnector need to be instantiate correct and store correct. 

**Environment (please complete the following information):**
 - Great Expectations Version: [0.14.9]

**Additional context**
