### ISSUE TITLE
InferredAssetDataConnector can't infer data_asset_name using regex

### ISSUE THREAD

**Issue by akmorrow13** [fivetran/great_expectations#4555]
**Describe the bug**
In the [documentation](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_choose_which_dataconnector_to_use/), it states that InferredAssetDataConnector can infer `data_asset_name` using regex. However, when implementing InferredAssetDataConnector in a checkpoint on a filesystem, `data_asset_name` must be set to a file name to run, and fails with regex.

**To Reproduce**
1. Create a directory `data` with two files: "first_annotations.tsv.gz" and "second_annotations.tsv.gz"
2. Create a datasource for pandas:
```
oligo_pools_datasource:
    data_connectors:
      default_inferred_data_connector_name:
        base_directory: ../data
        class_name: InferredAssetFilesystemDataConnector
        default_regex:
          group_names:
            - data_asset_name
          pattern: (.*annotations.tsv.gz)
        module_name: great_expectations.datasource.data_connector
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
    class_name: Datasource
    module_name: great_expectations.datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: PandasExecutionEngine
```
4. Create a checkpoint with connector `default_inferred_data_connector_name`
```
name: my_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-my-run-name-template'
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: oligo_pools_datasource
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: "*annotations.tsv.gz"
      batch_spec_passthrough:
        reader_options:
          sep: "\t"
    expectation_suite_name: my_expectation_suite
profilers: []
```
5. Run the checkpoint and observe error `list index out of range`:
```
> great_expectations checkpoint run my_checkpoint
Using v3 (Batch Request) API
list index out of range
```

**Expected behavior**
great_expectations should run the checkpoint on two files.
**Environment:**
 - Operating System: MacOS 11.5.1
 - Great Expectations Version: 0.14.11
