### ISSUE TITLE
Returns a TypeError when configuring notebooks generated by suite-edit

### ISSUE THREAD

**Issue by Josephmaclean** [fivetran/great_expectations#4588]
**Describe the bug**
In the [documentation](https://docs.greatexpectations.io/docs/guides/miscellaneous/how_to_configure_notebooks_generated_by_suite_edit/#overwriting-a-section), it states that to overwrite a header or footer code, you'll need to create a python file containing the code you want to overwrite it with.

The problem is that, when the code is provided, an error is thrown which states that `TypeError: render_to_disk() got an unexpected keyword argument 'batch_request'`. This is because, when calling `SuiteEditNotebookRenderer.from_data_context`
which generates a renderer, the module name still points to `great_expectations.render.renderer.suite_edit_notebook_renderer` which is v2 instead of the v3 module hence causing  the parameters passed to the generated renderer when calling `renderer.render_to_disk` to fail.

**To Reproduce**
1. Create a new expectation suite or use an existing one
2. Create a file in `great_expectations/plugins/notebook_assets/suite_edit/footer.py` 
```
batch.save_expectation_suite(discard_failed_expectations=False)
run_id = {
    "run_name": "some_string_that_uniquely_identifies_this_run",  # insert your own run_name here
    "run_time": datetime.datetime.now(datetime.timezone.utc),
}
results = context.run_validation_operator(
    "{{ validation_operator_name }}", assets_to_validate=[batch], run_id=run_id
)
validation_result_identifier = results.list_validation_result_identifiers()[0]
context.build_data_docs(site_names=["{{ site_name }}"])
context.open_data_docs(validation_result_identifier, site_name="{{ site_name }}")
``` 
4. Update the notebooks key in `great_expectations.yml` with
```
notebooks:
    suite_edit:
        custom_templates_module: notebook_assets.suite_edit
        footer_code:
            file_name: footer.py
            template_kwargs:
                site_name: site_local
                validation_operator_name: local
```
5. Run great_expectations new suite and observe error
`TypeError: render_to_disk() got an unexpected keyword argument 'batch_request'`

**Expected behavior**
Great expectations should replace the footer code in the jupyter notebook with the code provided in the footer.py file

**Environment (please complete the following information):**
 - Operating System:  MacOS
 - Great Expectations Version: [e.g. 0.14.12]
