### ISSUE TITLE
batch_spec_passthrough on Data Asset causes TypeError

### ISSUE THREAD

**Issue by error418** [fivetran/great_expectations#4826]
Configuring `batch_spec_passthrough` in Data Assets causes a

```
TypeError: 'Asset' object is not subscriptable
```

The configured Asset looks like this:

```yml
example_datasource:
  [ ... ]
  execution_engine:
    module_name: great_expectations.execution_engine
    class_name: PandasExecutionEngine
    boto3_options:
       [ ... ]
  data_connectors:
    s3_asset_connector:
      class_name: ConfiguredAssetS3DataConnector
      [ ... ]
      assets:
        first_asset:
          batch_spec_passthrough:
            reader_method: read_csv
            reader_options:
              on_bad_lines: skip
          [ ... ]
```

The following line is the exception root:

https://github.com/great-expectations/great_expectations/blob/ac192f821fd78297c2e302824f33ae7ff91229b5/great_expectations/datasource/data_connector/configured_asset_file_path_data_connector.py#L245

This needs to be referenced like the following (but I am unsure of the implications of this change on other components):

```diff
- self.assets[data_asset_name]["batch_spec_passthrough"]
+ self.assets[data_asset_name].batch_spec_passthrough
```
