### ISSUE TITLE
Support for DeltaLake Delta Tables

### ISSUE THREAD

**Issue by dnlbunting** [fivetran/great_expectations#5004]
**Is your feature request related to a problem? Please describe.**
The Delta table format https://docs.delta.io/latest/index.html is commonly used with Spark/Databricks, there is some support for it currently via the `reader_method` configuration in SparkDFExecutionEngine.  However this is of limited use because it's not possible to construct meaningful batches using the regex file name matching used in the existing DataConnectors.
A typical use case would be mapping partitions of the a delta table eg ingest date to Batches in GE.

**Describe the solution you'd like**
A new DataConnector that would allow for creating Batches from a delta table using the partition structure metadata, ie the partition columns would be the batch_identifiers.

**Describe alternatives you've considered**
Using one of the file name regex DataConnectors doesn't work because directly accessing the parquet files underlying the delta table is unsupported and can lead to data corruption

**Additional context**
I've put together a prototype data connector as a plugin so some discussions/feedback from the community would be great to help me get this to a PR :) 

**Example Config**

For a delta table OrderBooked with a single partition column called `partitionDate`
Note that the partition columns/batch_identifiers don't have to be explicitly set because they are defined in the delta table metadata
```yaml
name: spark_datasource
class_name: Datasource
module_name: great_expectations.datasource
execution_engine:
  class_name: SparkDFExecutionEngine
  module_name: great_expectations.execution_engine
data_connectors:
  test_project:
    module_name: configured_asset_delta_table_connector
    class_name: ConfiguredAssetDeltaTableDataConnector
    assets:
      OrderBooked:
        base_directory: data/OrderBooked/
``` 

Self-test result:
<img width="1099" alt="image" src="https://user-images.githubusercontent.com/5089993/166450416-f6b50fe9-60f5-4e14-971b-f66923a7f3bf.png">
