### ISSUE TITLE
Azure Blob Storage: Multiple data assets

### ISSUE THREAD

**Issue by psxmc6** [fivetran/great_expectations#5025]
Hello,

I have been trying to follow [this guidline](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/how_to_configure_a_configuredassetdataconnector/) to define multiple data assets for a given data source (Azure Blob Storage container). This tutorial relies on ConfiguredAssetFileSystem and so, glob_directive option is available to define data assets on multiple levels within a directory, however, ConfiguredAsset**Azure**DataConnector, does not have this flag within its class definition.

My goal would be to firstly ingest all parquet files within a container my-container/base_directory/my_table across three partitions (e.g. type=A, type=B, type=C) as one data asset called **flat,** and secondly, define **partitioned** data assets with names corresponding to **type** partition i.e. A, B and C:

```
base_directory/my_table/:
   type=A/
   type=B/
   type=C/
```

I was able to achieve singular and partitioned views but only in two separate configurations using **InferredAssetAzureDataConnector**:

**Partitioned view using InferredAssetAzureDataConnector**

```
datasource_yaml = rf"""
name: my_azure_datasource
class_name: Datasource
execution_engine:
    class_name: SparkDFExecutionEngine
    azure_options:
        account_url: <SA>.blob.core.windows.net
        credential: <KEY>
data_connectors:
    default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
            - default_identifier_name
    default_inferred_data_connector_name:
        class_name: InferredAssetAzureDataConnector
        azure_options:
            account_url: <SA>.blob.core.windows.net
            credential: <KEY>
        container: great-expectations
        name_starts_with: base_directory/my_table/
        default_regex:
            pattern: base_directory/my_table/type=(.*)/(.*)\.parquet
            group_names:
                - data_asset_name
                - parquet_id
"""

context.test_yaml_config(yaml_config=datasource_yaml)

Data Connectors:
	default_inferred_data_connector_name : InferredAssetAzureDataConnector

	Available data_asset_names (3 of 3):
		A (3 of 14): [...]
		B (1 of 1): [...]
		C (1 of 1): [...]
```

**Singular view using InferredAssetAzureDataConnector**

```
datasource_yaml = rf"""
name: my_azure_datasource
class_name: Datasource
execution_engine:
    class_name: SparkDFExecutionEngine
    azure_options:
        account_url: <SA>.blob.core.windows.net
        credential: <KEY>
data_connectors:
    default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
            - default_identifier_name
    default_inferred_data_connector_name:
        class_name: InferredAssetAzureDataConnector
        azure_options:
            account_url: <SA>.blob.core.windows.net
            credential: <KEY>
        container: great-expectations
        name_starts_with: base_directory/my_table/
        default_regex:
            pattern: (.*)\.parquet
            group_names:
                - parquet_id
"""

context.test_yaml_config(yaml_config=datasource_yaml)

Data Connectors:
	default_inferred_data_connector_name : InferredAssetAzureDataConnector

	Available data_asset_names (1 of 1):
		DEFAULT_ASSET_NAME (3 of 16): [...]
```

I would like to achieve described ingestion from ABS container (resulting in four data assets) using **ConfiguredAssetAzureDataConnector** in one setting:

```
datasource_yaml = rf"""
name: my_azure_datasource
class_name: Datasource
execution_engine:
    class_name: SparkDFExecutionEngine
    azure_options:
        account_url: <SA>.blob.core.windows.net
        credential: <KEY>
data_connectors:
    default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
            - default_identifier_name
    default_configured_data_connector_name:
        class_name: ConfiguredAssetAzureDataConnector
        azure_options:
            account_url: <SA>.blob.core.windows.net
            credential: <KEY>
        container: great-expectations
        name_starts_with: base_directory/my_table/
        assets:
            A:
                pattern: base_directory/my_table/type=A/(.*)\.parquet
                group_names:
                    - parquet_id
            B:
                pattern: base_directory/my_table/type=B/(.*)\.parquet
                group_names:
                    - parquet_id
            C:
                pattern: base_directory/my_table/type=C/(.*)\.parquet
                group_names:
                    - parquet_id
            flat:
                pattern: (.*)\.parquet
                group_names:
                    - parquet_id
"""

context.test_yaml_config(yaml_config=datasource_yaml)

****************************
*** EXPECTED OUTPUT ***
****************************

Data Connectors:
	default_configured_data_connector_name : ConfiguredAssetAzureDataConnector

	Available data_asset_names (4 of 4):
		A (3 of 14): [...]
		B (1 of 1): [...]
		C (1 of 1): [...]
                flat (3 of 16): [...]
```

The rationale behind this approach is that I would like to define some expectations across partitions as well as within the entire dataset when ingested as one "flat" table.

I will greatly appreciate your help.

Kind regards
