### ISSUE TITLE
Invalid behaviour of "Result Format" for validator

### ISSUE THREAD

**Issue by milosz-dm** [fivetran/great_expectations#5220]
**Describe the bug**
Invalid behaviour of "Result Format" for validator. Below example shows that it works well for PandasDataset, but it does not work for a validator. I tried to have only success/false information but unfortunately it does not work.

**To Reproduce**
The "Result Format" works well for PandasDataset
```
import pandas as pd
import datetime
import great_expectations as ge
from great_expectations import DataContext
from great_expectations.core import ExpectationSuite
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.validator.validator import Validator
from great_expectations.checkpoint import SimpleCheckpoint

# ################### DOES WORK ######################################
df = pd.DataFrame({"some_col": pd.Series([1,2,None], dtype="object")})
gdf = ge.from_pandas(df)
gdf.expect_column_distinct_values_to_equal_set(column="some_col", value_set=[], result_format={"result_format": "BOOLEAN_ONLY"})
```
Output:
```
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "success": false,
  "meta": {},
  "result": {},
  "expectation_config": {
    "ge_cloud_id": null,
    "meta": {},
    "expectation_type": "expect_column_distinct_values_to_equal_set",
    "kwargs": {
      "column": "some_col",
      "value_set": [],
      "result_format": {
        "result_format": "BOOLEAN_ONLY"
      }
    }
  }
}
```

Unfortunately for a validator it does not work the same way, it produces too much output.
```
import pandas as pd
import datetime
import great_expectations as ge
from great_expectations import DataContext
from great_expectations.core import ExpectationSuite
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.validator.validator import Validator
from great_expectations.checkpoint import SimpleCheckpoint

# ################### DOES NOT WORK ###################################
# Load GE context
context = DataContext(context_root_dir="YourPath")

# Define data to be tested
batch_request = {
    "datasource_name":"pandas_datasource",
    "data_connector_name": "runtime_data_connector",
    "data_asset_name":"insert_your_data_asset_name_here",
    "runtime_parameters":{
      "batch_data": df
    },
    "batch_identifiers": {
        "pipeline_step": "ingestion step 1",
        "job_id": "run_18"
    }
}
runtime_batch_request = RuntimeBatchRequest(**batch_request)

# Provide Expectation Suite name
expectation_suite_name = "empty.warn"

if expectation_suite_name in context.list_expectation_suite_names():
    # Load Expectation Suite already exists
    suite: ExpectationSuite = context.get_expectation_suite(expectation_suite_name)
else:
    # Create Expectation Suite if not exists
    suite: ExpectationSuite = context.create_expectation_suite(expectation_suite_name)

# Build a data validator
my_validator: Validator = context.get_validator(
    batch_request=runtime_batch_request,
    expectation_suite=suite
    )

my_validator.expect_column_distinct_values_to_equal_set(column="some_col", value_set=[], result_format={"result_format": "BOOLEAN_ONLY"})
```
Output:
```
{
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "success": false,
  "meta": {},
  "result": {
    "observed_value": [
      1,
      2
    ],
    "details": {
      "value_counts": [
        {
          "value": 1,
          "count": 1
        },
        {
          "value": 2,
          "count": 1
        }
      ]
    }
  },
  "expectation_config": {
    "ge_cloud_id": null,
    "meta": {},
    "expectation_type": "expect_column_distinct_values_to_equal_set",
    "kwargs": {
      "column": "some_col",
      "value_set": [],
      "result_format": {
        "result_format": "BOOLEAN_ONLY"
      },
      "batch_id": "190f3b361167b438768715c45890fd2b"
    }
  }
}
```

Additional data source in `great_expectations.yml`:
```
config_version: 3

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/en/latest/reference/core_concepts/datasource.html
datasources:
  pandas_datasource:
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: PandasExecutionEngine
    module_name: great_expectations.datasource
    class_name: Datasource
    data_connectors:
      runtime_data_connector:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - pipeline_step
          - job_id
```

**Expected behavior**
I would expect that in both casesthe output results are similar.

**Environment:**
I run it on `Linux` on version `0.13.41` & `0.15.6`
