### ISSUE TITLE
Data docs html files are not created while using azure blob as a validation store

### ISSUE THREAD

**Issue by chalond** [fivetran/great_expectations#5364]
**Describe the bug**
While using azure blob as a validation store, html files under data_docs/local_site/validations are not created.
The same issue appears if the data docs are configured to be stored in blob.

**To Reproduce**
1. Initialize great_expectations
2. Change great_expectations.yml config according to the code below.
3. Create and run a new expectation suite
4. Create and run a new checkpoint
5. See that docs html files for validation results are not created

**Expected behavior**
While using blob storage for validation storage docs html files are produced while running checkpoint.

**Environment (please complete the following information):**
 - Operating System: [Windows]
 - Great Expectations Version: [0.15.10]

**Additional context**
azure-storage-blob==12.12.0

```

config_version: 3.0

datasources:
  my_datasource_name:
    class_name: Datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: PandasExecutionEngine
      azure_options:
        account_url: BLOB_ACC_URL
        credential: CREDENTIAL
    module_name: great_expectations.datasource
    data_connectors:
      configured_data_connector_name:
        class_name: InferredAssetAzureDataConnector
        module_name: great_expectations.datasource.data_connector
        name_starts_with: FILES_PREFIX/
        container: BLOB_CONTAINER
        azure_options:
          account_url: BLOB_ACC_URL
          credential: CREDENTIAL
        default_regex:
          pattern: (.*)\.csv
          group_names:
            - data_asset_name


config_variables_file_path: uncommitted/config_variables.yml

plugins_directory: plugins/

stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  #validations_store:
  #  class_name: ValidationsStore
  #  store_backend:
  #    class_name: TupleFilesystemStoreBackend
  #    base_directory: uncommitted/validations/

  validations_AZ_store:
      class_name: ValidationsStore
      store_backend:
          class_name: TupleAzureBlobStoreBackend
          container: BLOB_CONTAINER
          connection_string: ${AZURE_STORAGE_WEB_CONNECTION_STRING}
          prefix: great_expectations/validations

  evaluation_parameter_store:
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_AZ_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: false
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
  #az_site:  # this is a user-selected name - you may select your own
  #  class_name: SiteBuilder
  #  store_backend:
  #     class_name: TupleAzureBlobStoreBackend
  #     container: \$web
  #     connection_string: ${AZURE_STORAGE_WEB_CONNECTION_STRING}
  #  site_index_builder:
  #    class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  enabled: True


```
