### ISSUE TITLE
`UpdateDataDocsAction` takes too long

### ISSUE THREAD

**Issue by sp1thas** [fivetran/great_expectations#5378]
**Describe the bug**
I was wondering why `UpdateDataDocsAction` takes so long. In my case, it takes ~20min to run this action. Currently, there are ~1200 runs already stored in the GCS bucket. Is this somehow related to the HTML re-indexing?

**To Reproduce**
1. Create DataDocs with more than 1K run records.
2. Add `UpdateDataDocsAction` in the action list.
3. Run any checkpoint.

**Expected behavior**
Update the DataDocs quicker

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: `0.15.4`

**Additional context**
**great_expectations.yml:**

```
[...]
stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleGCSStoreBackend
      project: ****
      bucket: ****
      prefix: validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: false
    store_backend:
      class_name: TupleGCSStoreBackend
      project: ****
      bucket: ****
      prefix:
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
[...]
```
**a random checkpoint file:**

```
[...]
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
  - name: send_slack_notification_on_validation_result
    action:
      class_name: SlackNotificationAction
      slack_webhook: ${GE_SLACK_WEBHOOK}
      notify_on: failure
      notify_with:
      renderer:
        module_name: great_expectations.render.renderer.slack_renderer
        class_name: SlackRenderer
[...]
```
