### ISSUE TITLE
Missing unexpected_index_list in expectation results for ge_validator.validate() command

### ISSUE THREAD

**Issue by milosz-dm** [fivetran/great_expectations#5379]
**Describe the bug**
unexpected_index_list is missing in expectation results for `ge_validator.validate()` command. It works for `ge_validator.expect_multicolumn_sum_to_equal` command, but later on it does not work for `ge_validator.validate()` command.

**To Reproduce**
```
import pandas as pd
from great_expectations import DataContext
from great_expectations.core.batch import RuntimeBatchRequest

ge_context = DataContext(context_root_dir="YOUR_PATH")
my_df = pd.DataFrame(
    {
        "flaot_as_obj": pd.Series([1.], dtype="object"),
        "flaot_as_obj 80%": pd.Series([1.], dtype="object"),
        "some_float": pd.Series([15.0], dtype="float64"),
    }
)
my_df.index = ["row0"]


my_type_list =  [
    "FLOAT",
    "FLOAT4",
    "FLOAT8",
    "FLOAT64",
    "DOUBLE",
    "DOUBLE_PRECISION",
    "NUMERIC",
    "FloatType",
    "DoubleType",
    "float_",
    "float16",
    "float32",
    "float64",
    "number",
    "DECIMAL",
    "REAL"
]

batch_request: dict = {
    "datasource_name": "pandas_datasource",
    "data_connector_name": "runtime_data_connector",
    "data_asset_name": "not_relevant_for_pandas_datasource",
    "runtime_parameters": {"batch_data": my_df},
    "batch_identifiers": {"pipeline_step": None, "job_id": None},
}

runtime_batch_request: RuntimeBatchRequest = RuntimeBatchRequest(**batch_request)
empty_suite = ge_context.get_expectation_suite("empty.error")


ge_validator = ge_context.get_validator(batch_request=runtime_batch_request, expectation_suite=empty_suite)
# unexpected_index_list available in results
ge_validator.expect_multicolumn_sum_to_equal(
    column_list=["flaot_as_obj 80%", "flaot_as_obj"],
    sum_total=0, result_format={"result_format": "COMPLETE"}
)

# unexpected_index_list NOT available in results
ge_validator.validate()

```

`empty_error.json` file:
```
{
  "data_asset_type": null,
  "expectation_suite_name": "empty.error",
  "expectations": [],
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.13.35"
  }
}
```

Additional data source in `great_expectations.yml`:
```
config_version: 3

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/en/latest/reference/core_concepts/datasource.html
datasources:
  pandas_datasource:
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: PandasExecutionEngine
    module_name: great_expectations.datasource
    class_name: Datasource
    data_connectors:
      runtime_data_connector:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - pipeline_step
          - job_id
```

**Expected behavior**
I would expect that in both version of the validation we have the same outputs (unexpected_index_list available in the results).

**Environment (please complete the following information):**
 - Operating System: `Linux`
 - Great Expectations Version: `0.13.41`

**Additional context**
It may be connected with https://github.com/great-expectations/great_expectations/issues/4658
