### ISSUE TITLE
Athena Batch Request fails with MetricResolutionError: 'Select' object has no attribute '_simple_int_clause'

### ISSUE THREAD

**Issue by francoiswessels** [fivetran/great_expectations#5395]
**Describe the bug**
After following the tutorials to create an Athena Data Source, when I work through the Expectation Suite tutorial notebook, the first cell of code fails with:

```
File "c:\\Dev\\great-expectations\\venv\\lib\\site-packages\\great_expectations\\validator\\validator.py", line 1291, in resolve_validation_graph\n    runtime_configuration=runtime_configuration,\n  File "c:\\Dev\\great-expectations\\venv\\lib\\site-packages\\great_expectations\\validator\\validator.py", line 2202, in _resolve_metrics\n    runtime_configuration=runtime_configuration,\n  File "c:\\Dev\\great-expectations\\venv\\lib\\site-packages\\great_expectations\\execution_engine\\execution_engine.py", line 391, in resolve_metrics\n    message=str(e), failed_metrics=(metric_to_resolve,)\ngreat_expectations.exceptions.exceptions.MetricResolutionError: \'Select\' object has no attribute \'_simple_int_clause\'\n', 'exception_message': "'Select' object has no attribute '_simple_int_clause'", 'raised_exception': True}}}}
occurred while resolving metrics.
```
... raising a KeyError exception as follows:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_8668\1643758935.py in <module>
     22 column_names = [f'"{column_name}"' for column_name in validator.columns()]
     23 print(f"Columns: {', '.join(column_names)}.")
---> 24 validator.head(n_rows=5, fetch_all=False)

c:\Dev\great-expectations\venv\lib\site-packages\great_expectations\validator\validator.py in head(self, n_rows, domain_kwargs, fetch_all)
   2143                 metric_value_kwargs={
   2144                     "n_rows": n_rows,
-> 2145                     "fetch_all": fetch_all,
   2146                 },
   2147             )

c:\Dev\great-expectations\venv\lib\site-packages\great_expectations\validator\validator.py in get_metric(self, metric)
    889     def get_metric(self, metric: MetricConfiguration) -> Any:
    890         """return the value of the requested metric."""
--> 891         return self.get_metrics(metrics={metric.metric_name: metric})[
    892             metric.metric_name
    893         ]

c:\Dev\great-expectations\venv\lib\site-packages\great_expectations\validator\validator.py in get_metrics(self, metrics)
    856         return {
    857             metric_configuration.metric_name: resolved_metrics[metric_configuration.id]
--> 858             for metric_configuration in metrics.values()
    859         }
    860 

c:\Dev\great-expectations\venv\lib\site-packages\great_expectations\validator\validator.py in <dictcomp>(.0)
    856         return {
    857             metric_configuration.metric_name: resolved_metrics[metric_configuration.id]
--> 858             for metric_configuration in metrics.values()
    859         }
    860 

KeyError: ('table.head', 'batch_id=a4d23b6d51228c70a7a9a183f5669b18', '04166707abe073177c1dd922d3584468')
```

**To Reproduce**
1. Follow the Setup process: https://docs.greatexpectations.io/docs/guides/setup/setup_overview, create a new data context.
2. Add an Athena Data Source, cf https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/database/athena/, context yml now shows:
```
# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
datasources:
  my_datasource:
    module_name: great_expectations.datasource
    execution_engine:
      connection_string: awsathena+rest://@athena.us-east-1.amazonaws.com/?s3_staging_dir=s3%3A//mosaic-bo-datalake/temp/developer/
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
    class_name: Datasource
    data_connectors:
      default_runtime_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        class_name: InferredAssetSqlDataConnector
        include_schema_name: true
```
4. Start Tutorial, Step 3: Create Expectations, found here: https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_create_expectations, selecting "3. Automatically, using a profiler". I chose the first data asset in my data source, just for sake of testing, which then launches a notebook with the first code cell containing:

```
import datetime

import pandas as pd

import great_expectations as ge
import great_expectations.jupyter_ux
from great_expectations.core.batch import BatchRequest
from great_expectations.profile.user_configurable_profiler import UserConfigurableProfiler
from great_expectations.checkpoint import SimpleCheckpoint
from great_expectations.exceptions import DataContextError

context = ge.data_context.DataContext()

batch_request = {'datasource_name': 'my_datasource', 'data_connector_name': 'default_inferred_data_connector_name', 'data_asset_name': 'borrowing_base.accruals', 'limit': 1000}

expectation_suite_name = "my_suite"

validator = context.get_validator(
    batch_request=BatchRequest(**batch_request),
    expectation_suite_name=expectation_suite_name
)
column_names = [f'"{column_name}"' for column_name in validator.columns()]
print(f"Columns: {', '.join(column_names)}.")
validator.head(n_rows=5, fetch_all=False)
```

5. Run the first code cell. Error is raised.

**Expected behavior**
Honestly, I don't know what to expect here, I am just getting started with Great Expectations and I want to see that basic functionality works.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Package Versions:
> great-expectations==0.15.7
> pyathena==2.8.0
> SQLAlchemy==1.3.24

**Additional context**
In addition to the above, which is the simplest way to trigger the error, I have everything set up to run containerised in a cluster too. When trying to run a checkpoint on Athena, I see the same error when inspecting the pod logs.
