### ISSUE TITLE
Data Docs hosting on Azure Blob fails 

### ISSUE THREAD

**Issue by juliankeppel** [fivetran/great_expectations#5422]
**Describe the bug**
I tried to upload Data Docs on an Azure Blob storage container as documented [here](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage).

When I run `poetry run great_expectations docs build --site-name az_site`, I get the following error:
```
ErrorCode:AuthenticationFailed
Content: <?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthenticationFailed</Code><Message>Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
```

**To Reproduce**
1. Init GE project: `poetry run great_expectations init`
2. Put example data somewhere (simply CSV file in my case)
3. Add datasource: `poetry run great_expectations datasource new`
4. Create checkpoint: `poetry run great_expectations checkpoint new my_checkpoint`
5. Configure Azure blob storage according to the [GE documentation](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_docs/how_to_host_and_share_data_docs_on_azure_blob_storage)
6. Try to build data docs: `poetry run great_expectations docs build --site-name az_site`

**Expected behavior**
The static website for data docs are generated and uploaded to the Blob storage container.

**Environment (please complete the following information):**
MacOS 12.4
Poetry version 1.1.11
Python version 3.8.12
GE version 0.15.11

**Additional context**
I'm now sure if this is relevant to this issue, but first I faced this error: `ModuleNotFoundError: No module named 'azure'`. Then I added the following dependencies to my virtual env (according to [this requirements file](https://github.com/great-expectations/great_expectations/blob/develop/requirements-dev-azure.txt)):
azure-identity = ">=1.0.0"
azure-keyvault-secrets = ">=4.0.0"
azure-storage-blob = ">=12.5.0"

**Comment by adrixp** [comment]
Hi, same issue here

**Comment by adrixp** [comment]
For me, this fixed the issue:
pip install azure-functions
pip install azure-storage-blob

**Comment by juliankeppel** [comment]
@adrixp Thank's for this comment. But for me this doesn't fix the issue. I use poetry as dependency manager and added those dependencies to my virtual environment, but the error stays the same as before. 

Any advice from the developer team?

**Comment by talagluck** [comment]
Hi @juliankeppel - thanks for raising. We haven't tested this at all with `poetry`. I'd be curious whether or not you're able to get this working with `pip`. If this is an issue with `poetry` specifically, that would be good for us to know.

**Comment by juliankeppel** [comment]
Hi @talagluck thanks for your repsonse!

I just pip-installed great expectations and (as @adrixp mentioned) also needed to install azure-functions and azure-storage-blob. But then, I got the exact same error message as with my poetry installation.

This is how my `great_expectations.yml` configuration for the data_docs_sites looks like:
```
data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  az_site: # this is a user-selected name - you may select your own
    class_name: SiteBuilder
    store_backend:
      class_name: TupleAzureBlobStoreBackend
      container: \$web
      connection_string: ${AZURE_STORAGE_WEB_CONNECTION_STRING}
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
```

This is how my `config_variables.yml` looks like: 
```
# This config file supports variable substitution which enables: 1) keeping
# secrets out of source control & 2) environment-based configuration changes
# such as staging vs prod.
#
# When GE encounters substitution syntax (like `my_key: ${my_value}` or
# `my_key: $my_value`) in the great_expectations.yml file, it will attempt
# to replace the value of `my_key` with the value from an environment
# variable `my_value` or a corresponding key read from this config file,
# which is defined through the `config_variables_file_path`.
# Environment variables take precedence over variables defined here.
#
# Substitution values defined here can be a simple (non-nested) value,
# nested value such as a dictionary, or an environment variable (i.e. ${ENV_VAR})
#
#
# https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials

instance_id: cd18c94b-0d72-49d6-84a3-386c694350c6
AZURE_STORAGE_WEB_CONNECTION_STRING: "DefaultEndpointsProtocol=https;AccountName=<my_acount_name>;AccountKey=<my_account_key>;EndpointSuffix=core.windows.net"
```

I copied the connection string right from the Azure web UI, like described in the documentation (replaced some content by placeholders).
