### ISSUE TITLE
StoreValidationResultAction / UpdateDataDocsAction takes too long

### ISSUE THREAD

**Issue by flaneur-ml** [fivetran/great_expectations#5433]
**Description**
I run application with great_expectations in docker container. While running ge saves the results of validations and updates the docs in `uncommited` folder. When the amount of ge runs becomes significant with time the validations results saving and docs refreshing takes a lot of time which is much longer than my application run. However, I don't use these validations results and don't need the docs updates. Can the validations results saving / docs updating be disabled or the performance of these actions increased?

**Context**
`great_expectations.yml`: 
```
config_version: 3.0

datasources:
  inference_datasource:
    module_name: great_expectations.datasource
    data_connectors:
      default_inferred_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        default_regex:
          group_names:
            - data_asset_name
          pattern: (.*)
        base_directory: ../data/inference
        class_name: InferredAssetFilesystemDataConnector
      default_runtime_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
    execution_engine:
      class_name: PandasExecutionEngine
      module_name: great_expectations.execution_engine
    class_name: Datasource
config_variables_file_path: /tmp/uncommitted/config_variables.yml

plugins_directory: plugins/

stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: /tmp/uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: /tmp/profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: /tmp/uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: 5f8c5196-4e9a-4092-b62b-fdabcc96dfea
  enabled: true
notebooks:
```

`checkpoint.yml`:
```
name: universal_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: "%Y%m%d-%H%M%S-run"
expectation_suite_name:
batch_request:
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
evaluation_parameters: {}
runtime_configuration: {}
validations: []
profilers: []
ge_cloud_id:
```

**Environment**
 - python: 3.8.12
 - macOS Monterey 12.4
 - great-expectations 0.15.0

**Comment by viplazylmht** [comment]
Hello @youth-quaker,

Yes, you can skip both StoreValidationResult, and UpdateDataDocs as well. 

To do that, in checkpoint.yml, you just need to leave argument `action_list` empty. For example in your case:

```yaml
name: universal_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: "%Y%m%d-%H%M%S-run"
expectation_suite_name:
batch_request:
action_list:
evaluation_parameters: {}
runtime_configuration: {}
validations: []
profilers: []
ge_cloud_id:
```

If GE still perform these actions, please mention me again. 

However, I recommend you to store at least validation results for future use. When working with Docker, you can create a Volume Mount to mount directly to the container, or you can take the advantage of external store/bucket (GCS, S3,... for example). 

Hope this can help.

**Comment by talagluck** [comment]
Thanks for the question @youth-quaker, and thank you for the response, @viplazylmht! 

I also wanted to add that you can use `validation_result_limit` in your DataContext to limit the rendered ValidationResult to the n most recent per Expectation Suite like this:
```yaml
data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
      validation_results_limit: 5
```

I'm going to close this for now since I think there are a number of possible solutions here, but please feel free to reopen if you have any additional updates.
