### ISSUE TITLE
expect_table_row_count_to_equal_other_table does not work properly with AWS Athena data source

### ISSUE THREAD

**Issue by adam-staros** [fivetran/great_expectations#5534]
**Describe the bug**
Expectation `expect_table_row_count_to_equal_other_table` does not work properly with AWS Athena, because query for counting other table rows runs in `default` database. 

**To Reproduce**
Datasource configuration:
```yaml
datasources:
  athena:
    class_name: Datasource
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      connection_string: awsathena+rest://...
      module_name: great_expectations.execution_engine
    module_name: great_expectations.datasource
config_variables_file_path: uncommitted/config_variables.yml
```

Let's assume that I want to make following checks:
- number of columns of `dev.users` is between 8 and 10
- number of rows of `dev.users` equals number of rows of `dev.address`:

Expectation suite:
```json
{
  "data_asset_type": null,
  "expectation_suite_name": "users.expecation",
  "expectations": [
    {
      "expectation_type": "expect_table_column_count_to_be_between",
      "kwargs": {
        "max_value": 10,
        "min_value": 8
      },
      "meta": {}
    },
    {
      "expectation_type": "expect_table_row_count_to_equal_other_table",
      "kwargs": {
        "other_table_name": "dev.address"
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "citations": [
      {
        "batch_request": {
          "data_asset_name": "dev.users",
          "data_connector_name": "default_inferred_data_connector_name",
          "datasource_name": "athena",
          "limit": 1000
        },
        "citation_date": "2022-07-18T16:52:58.149668Z",
        "comment": "Created suite added via CLI"
      }
    ],
    "great_expectations_version": "0.15.13"
  }
}
```

When I execute validation, then `expect_table_column_count_to_be_between` passes (so query runs in correct db), but `expect_table_row_count_to_equal_other_table` fails with "_Table awsdatacatalog.**default**.dev.address does not exist_". 

**Expected behavior**
Query should be executed in `dev` database (`awsdatacatalog.dev.address`).

**Environment**
 - Operating System: MacOS
 - Great Expectations Version: 0.15.13

**Additional context**
I've tried to set `include_schema_name` to `false` but problem still exists.

Also it would be good to have possibility to check if number of rows of `dev.users` equals number of rows of `test.users` (between databases), it should work with Athena and it may be useful in cases when ETL's move data between multiple layers.
