### ISSUE TITLE
Lowercase table and column names in Snowflake are unreachable using BatchRequest API

### ISSUE THREAD

**Issue by cKennnedy** [fivetran/great_expectations#5535]
**Description**
Lowercase table and column names in Snowflake are unreachable using the BatchRequest API, as the identifiers are not wrapped in quotation marks.

any queries trying to access these columns or tables will fail with the following error

`(snowflake.connector.errors.ProgrammingError) 000904 (42000): SQL compilation error: error invalid identifier '<some column>'`

**To Reproduce**
1. Connect to a snowflake database with lowercase column or table names
2. Run anything that will query the db (profiler, checkpoint etc...)
3. look at output of data docs

**Expected behavior**
There should be a way to specify that identifiers should be wrapped in quotes. similar to the `use_quoted_name` kwarg in the v2 BatchKwargs API.

There is an optional argument on the `great_expectations.execution_engine.sqlalchemy_batch_data.SqlAlchemyBatchData` initializer to use quoted_name but it defaults to false, and there is no way to pass True up to it from a batch request as it is called without **kwargs   when fetching a Batch.

**Environment:**
 - Windows
 - Great Expectations version 0.15.3

**Comment by rdodev** [comment]
Hey @cKennnedy 👋 

Thanks for reporting. Can you provide code example of your use case?

**Comment by cKennnedy** [comment]
Sure.

The problem comes when checkpoint.run() is called and the database is queried. This responds with the error detailed above.

The datasource and expectation suites were both configured and generated using the CLI.

The specifics of the expectation suite are unimportant as any `SELECT <column_name> FROM ...` fails due to the lack of quotes.

The python script that is failing is as follows:

```python
context = ge.DataContext()

batch_request = {'datasource_name': 'my_snowflake_data_source', 'data_connector_name': 'default_inferred_data_connector_name', 'data_asset_name': '<table_name>'}

checkpoint_config = {
    "class_name": "SimpleCheckpoint",
    "validations": [
        {
            "batch_request": batch_request,
            "expectation_suite_name": "test"
        }
    ]
}
checkpoint = SimpleCheckpoint(
    "test",
    context,
    **checkpoint_config
)
checkpoint_result = checkpoint.run()
```

with the datasource configured as follows: 

```yaml
datasources:
  my_snowflake_data_source:
    class_name: Datasource
    module_name: great_expectations.datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
      connection_string: snowflake://${USER_NAME}:${PASSWORD}@${ACCOUNT_NAME}/${DATABASE}/${SCHEMA}?warehouse=${WAREHOUSE}&role=${ROLE}&application=great_expectations_oss
      
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        batch_identifiers:
          - default_identifier_name
        module_name: great_expectations.datasource.data_connector
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
```

And an expectation suite looking something like:

```json
{
  "data_asset_type": null,
  "expectation_suite_name": "test",
  "expectations": [
    {
      "expectation_type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "ingest_time",
        "value_set": [
          "2022-05-11 10:46:54.077000+00:00"
        ]
      },
      "meta": {}
    }
  ]
}
```

**Comment by cKennnedy** [comment]
Just as a very quick bodge, I have tried editing the great_expectations package code to set the `use_quoted_name` kwarg on the `great_expectations.execution_engine.sqlalchemy_batch_data.SqlAlchemyBatchData` initializer to default to `True`.

This is naturally not a permanent fix, but it has made the error I was seeing go away, so the Issue is definitely the inability to pass this argument up to the `SqlAlchemyBatchData` class from a `BatchRequest`.

**Comment by rdodev** [comment]
Hey @cKennnedy 👋 

After speaking to the team about this team, it was mentioned you can use `batch_spec_passthrough` to pass `use_quoted_name` set to true so that table name casing is respected. Please let us know if this works for you.

**Comment by cKennnedy** [comment]
Hi @rdodev,

Thanks for your response.

Having updated the batch request to look like:
```python
batch_request = {
    'datasource_name': 'my_snowflake_data_source',
    'data_connector_name': 'default_inferred_data_connector_name',
    'data_asset_name': '<table_name>',
    'batch_spec_passthrough': {
        'use_quoted_name': True
    }
}
```

I'm afraid I still see the same error.

**Comment by rdodev** [comment]
@cKennnedy I see. That should work. Given it's not working, I'll escalate this issue as a bug for fixing.

**Comment by cKennnedy** [comment]
@rdodev Many thanks indeed :).

**Comment by talagluck** [comment]
Hi @cKennnedy - I wanted to let you know that we are working on this. [I also wanted to point to the workaround indicated here in the meantime.](https://github.com/great-expectations/great_expectations/pull/2023#issuecomment-1210192307)

**Comment by kyleaton** [comment]
Surfacing a related issue here: #5834

**Comment by minhuipath** [comment]
Hi @talagluck , do you know when the fix for this would go out?

Im seeing thee work around of wrapping cols name with `sqlalchemy.sql.quoted_name` but not sure how I could do that with the json expectation?

Once of our sample:
```
{
  "data_asset_type": "Dataset",
  "expectation_suite_name": "event_log.raw",
  "expectations": [
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "case_id"
      },
      "meta": {
        "notes": {
          "content": "Ensure case_id is not null",
          "format": "markdown"
        }
      }
    }
  ],
  "meta": {
    "columns": {
      "case_id": {
        "description": "Case ID"
      }
    },
    "great_expectations_version": "0.15.32"
  }
}
```

**Comment by alexsherstinsky** [comment]
Hello, @cKennnedy -- my name is Alex Sherstinsky, and I am now working on troubleshooting this issue.  Please feel free to reach out to me in the Great Expectations Community Slack (`@AlexSherstinsky`) for a faster and more interactive process.

For starters, I have tried to reproduce the issue, but have not yet been able to do so.  Historically, and given the Snowflake preference for capitalized entity names, I do believe that there may be corner cases that do not work properly.  Having said that, I wanted to reproduce the error you encountered first and foremost, before drilling deeper.  To that effect, I have created my own version of your `datasource` configuration, which I am including below:
```
  my_snowflake_datasource:
    module_name: great_expectations.datasource
    data_connectors:
      default_inferred_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        include_schema_name: true
        class_name: InferredAssetSqlDataConnector
      default_runtime_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        assets:
          'pipeline_stage_123':
            module_name: great_expectations.datasource.data_connector.asset
            batch_identifiers:
              - default_identifier_name
            class_name: Asset
        class_name: RuntimeDataConnector
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
      connection_string: snowflake://${USER_NAME}:${PASSWORD}@${ACCOUNT_NAME}/${DATABASE}/${SCHEMA}?warehouse=${WAREHOUSE}&role=${ROLE}&application=great_expectations_oss
    class_name: Datasource
```

Please note that -- for what it is worth -- my test datasource configuration is slightly different than the one you provided above (specifically, there is an `assets` section in the "default_runtime_data_connector_name" configuration); however, we are not using the "default_runtime_data_connector_name" in our experiments, so this should not matter immediately (only potentially in the future, more detailed troubleshooting experiments).

My Snowflake environment contains a schema named "TEST_CI" with a table named "my_lowercase_taxi_data_table" inside (the case specificity is exactly as written in this sentence).  This table also contains the column named "total_amount" (again, the case specificity is as written).  The queries that pass the syntax check are either of the following two formats:

* `SELECT SUPERCONDUCTIVE.TEST_CI."my_lowercase_taxi_data_table"."total_amount" from SUPERCONDUCTIVE.TEST_CI."my_lowercase_taxi_data_table";`
* `SELECT "total_amount" from SUPERCONDUCTIVE.TEST_CI."my_lowercase_taxi_data_table";`

Both of these formats work as expected (they return the contents of the "total_amount" column of this `10`-row example table) -- the key aspect is the exact capitalization and double-quoting (as required; syntax errors are reported otherwise).

With this configuration, I created a `Jupyter` notebook, whose first cell contains the following code:
```
import datetime

import pandas as pd

import great_expectations as ge
import great_expectations.jupyter_ux
from great_expectations.core.batch import BatchRequest
from great_expectations.exceptions import DataContextError

context = ge.data_context.DataContext()

batch_request = {
    "datasource_name": "my_snowflake_datasource",
    "data_connector_name": "default_inferred_data_connector_name",
    "data_asset_name": 'test_ci.my_lowercase_taxi_data_table',
}

expectation_suite_name = "AlexTest10"

validator = context.get_validator(
    batch_request=BatchRequest(**batch_request),
    expectation_suite_name=expectation_suite_name,
)
column_names = [f'"{column_name}"' for column_name in validator.columns()]
print(f"Columns: {', '.join(column_names)}.")
validator.head(n_rows=5, fetch_all=False)
```

Executing this cell produced expected results -- `5` rows of the table were returned, with all columns listed in lower-case.

Please note that I have not needed to rely on `batch_spec_passthrough` (the safety valve of last resort) in the above `batch_request` -- the operations thus far worked using just the standard options.

I then ran the following expectation:
```
min_value = 9
max_value = 11
result = validator.expect_table_row_count_to_be_between(
    min_value=min_value,
    max_value=max_value,
    result_format='SUMMARY',
    include_config=True,
    catch_exceptions=None,
    meta=None
)
print(result, 'Success: {0}'.format(result.success), str(type(result)))
```

and it also worked as expected, producing the following output:
```
{
  "result": {
    "observed_value": 10
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "success": true,
  "expectation_config": {
    "expectation_type": "expect_table_row_count_to_be_between",
    "meta": {},
    "kwargs": {
      "min_value": 9,
      "max_value": 11,
      "result_format": "SUMMARY",
      "include_config": true,
      "catch_exceptions": null,
      "batch_id": "be71d0b07a2aa9c17f5706b23cd2d503"
    }
  }
} Success: True <class 'great_expectations.core.expectation_validation_result.ExpectationValidationResult'>
```

So the question is: does the above configuration and usage miss the specific use case that is relevant to you?  If so, could you please elaborate?  I would also like to request that you execute the following operations (with your configuration and environment specifics substituted into the appropriate arguments below, in the place of the ones I used, where appropriate):
```
source = context.get_datasource(datasource_name="my_snowflake_datasource")
connector = source.data_connectors["default_inferred_data_connector_name"]
connector.get_available_data_asset_names()
```

The last line should print the available data assets, and then you can use one of them as part of the batch request to see if the approach, described above, will be effective for your use-case scenario.

In any case, please get back to me with any follow up, and then we can continue troubleshooting this further as needed.

Thank you very much. /cc @talagluck
