### ISSUE TITLE
ValueError: 'ibm_db_sa' is not a valid GESqlDialect

### ISSUE THREAD

**Issue by Adenmin** [fivetran/great_expectations#5579]
Hello there!

So I faced an issue with integration GE and IBM Db2:

**Environment (please complete the following information):**
 - Operating System: Linux Ubuntu 22.04
 - Great Expectations Version: 0.15.14
 - ibm-db Version: 3.1.2
 - ibm-db-sa Version: 0.3.8
 - SQLAlchemy Version: 1.4.39

**Config**

```
datasources:
  db2_test_datasource:
    class_name: Datasource
    data_connectors:
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
      default_inferred_data_connector_name:
        class_name: InferredAssetSqlDataConnector
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
    module_name: great_expectations.datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
      connection_string: ibm_db_sa://admin:admin@127.0.0.1:50000/TEST
```

**run it**

```
context = ge.data_context.DataContext()

batch_request = RuntimeBatchRequest(
    datasource_name="db2_test_datasource",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="default_name",  # this can be anything that identifies this data
    runtime_parameters={"query": "SELECT * FROM TEST_TABLE LIMIT 10"},
    batch_identifiers={"default_identifier_name": "default_identifier"},
)
context.create_expectation_suite(
    expectation_suite_name="test_suite", overwrite_existing=True
)
validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="test_suite"
)
print(validator.head())
```
**and I got**

`ValueError: 'ibm_db_sa' is not a valid GESqlDialect`

**Does GE work correctly with IBM Db2?**
_I didn't find any documentation around it._
