### ISSUE TITLE
split_on_year_and_month_and_day on Redshift datasource throws sqlalchemy.exc.ProgrammingError

### ISSUE THREAD

**Issue by heather-dice** [fivetran/great_expectations#5598]
**Describe the bug**
Specifying a splitter method of `split_on_year_and_month_and_day` on a datetime column for a redshift datasource throws an sqlalchemy error:
```
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedFunction) function concat(integer, integer, integer) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type casts.

[SQL: SELECT distinct(concat(EXTRACT(year FROM _batched_at), EXTRACT(month FROM _batched_at), EXTRACT(day FROM _batched_at))) AS concat_distinct_values, CAST(EXTRACT(year FROM _batched_at) AS INTEGER) AS year, CAST(EXTRACT(month FROM _batched_at) AS INTEGER) AS month, CAST(EXTRACT(day FROM _batched_at) AS INTEGER) AS day 
FROM schema_name.table_name]
(Background on this error at: http://sqlalche.me/e/13/f405)
```
Possible reason: Redshift concat only takes two arguments whereas GE /sql alchemy creates a concat with more than two args passed.

**To Reproduce**
Datasource config
```
name: my_redshift_datasource
class_name: SimpleSqlalchemyDatasource
connection_string: postgresql+psycopg2://XXX
tables:
    schema_name.table_name:
        partitioners:
            split_by_year_month_day:
                include_schema_name: true
                schema_name: schema_name
                splitter_method: split_on_year_and_month_and_day
                splitter_kwargs:
                    column_name: _batched_at
```
In this example _batched_at has datetime format of: 2019-11-10 00:47:16.291000

```
context = ge.get_context()
datasource = context.get_datasource('my_redshift_datasource')

batch_request_dict = {
    "datasource_name": 'my_redshift_datasource',
    "data_connector_name": 'split_by_year_month_day',
    "data_asset_name": 'schema_name.table_name'
}
batch_request = BatchRequest(**batch_request_dict)
batch_list = datasource.get_batch_list_from_batch_request(batch_request)

Produces error above
```

**Expected behavior**
Batch list should consist of daily batches.

**Environment (please complete the following information):**
 - MacOS
 - Great Expectations Version: 0.15.14

**Additional context**
Thread link: https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1658410364807039
