### ISSUE TITLE
Memory leak when using GE within a docker container

### ISSUE THREAD

**Issue by saadkh225** [fivetran/great_expectations#5686]
**Describe the bug**
I am using GE inside a container with API requests triggering checkpoints.
Every time I run a checkpoint, there is a permanent increase in the memory usage of the container, GE does not release some memory.

**To Reproduce**
1. Setup GE to run in a dedicated container.
2. Setup an API model using Flask. The API call triggers a checkpoint.
3. GE configuration:
    1. Postgres backend for expectation and validation stores
    2.  Use `RuntimeDataConnector` with data access via file path or pass in memory dataframe
    3. Datasource setup:      
        ```
        datasources:
          common:
            module_name: great_expectations.datasource
            class_name: Datasource
            data_connectors:
              default_runtime_data_connector_name:
                module_name: great_expectations.datasource.data_connector
                batch_identifiers:
                  - default_identifier_name
                class_name: RuntimeDataConnector
            execution_engine:
              class_name: PandasExecutionEngine
              module_name: great_expectations.execution_engine
        ```

4. Make multiple requests
5. Observe container memory stats (I used Portainer)
6. Memory usage goes up with every request but never comes back to the same level (GE does not release some memory)

**Expected behavior**
Memory usage should go up during the processing and then memory should be released 

**Environment (please complete the following information):**
 - Operating System: Ubuntu 20.04.2 LTS (GNU/Linux 5.4.0-96-generic x86_64)
 - Great Expectations Version: 0.15.16
 - Flask version: 2.1.3
 - Docker version: 5.0.3

**Additional context**

*Memory profiling*
I have also done memory profiling on my code and ensured that the memory issue does not arise from my code. I have added the profiling results from the concerned function, the only increment happens during `run_checkpoint` and its not released completely.  
```
Mem usage    	Increment  	Occurrences   		Line Contents
===========================================================
...
342.8359 MiB   0.0000 MiB           1               validations = self.create_validations_list(files)
465.6328 MiB 122.7969 MiB           2               results = context.run_checkpoint(
342.8359 MiB   0.0000 MiB           1                   checkpoint_name="",
342.8359 MiB   0.0000 MiB           1                   run_name_template="",
342.8359 MiB   0.0000 MiB           1                   validations=validations
...
``` 
*Portainer screenshot*
The memory usage climbs up by 20-30 mb on every request made.
![image](https://user-images.githubusercontent.com/7899518/183017014-9556754b-c9e3-4e75-b819-058858781783.png)
