### ISSUE TITLE
Creating an Expectation Suite With an Automated Profiler Great Expectation

### ISSUE THREAD

**Issue by bachhavdipak** [fivetran/great_expectations#5781]
I am a newbie to great expectations and trying to set up but facing the below issue while creating an expectation Suite with an Automated Profiler.

```
C:\Users\user\great_expectations>great_expectations --v3-api suite new
Using v3 (Batch Request) API

How would you like to create your Expectation Suite?
    1. Manually, without interacting with a sample batch of data (default)
    2. Interactively, with a sample batch of data
    3. Automatically, using a profiler
: 3

A batch of data is required to edit the suite - let's help you to specify it.

Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\great_expectations.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\great_expectations\cli\cli.py", line 190, in main
    cli()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\great_expectations\cli\suite.py", line 151, in suite_new
    _suite_new_workflow(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\great_expectations\cli\suite.py", line 335, in _suite_new_workflow
    raise e
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\great_expectations\cli\suite.py", line 268, in _suite_new_workflow
    suite: ExpectationSuite = toolkit.get_or_create_expectation_suite(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\great_expectations\cli\toolkit.py", line 82, in get_or_create_expectation_suite
    default_expectation_suite_name: str = get_default_expectation_suite_name(
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\great_expectations\cli\toolkit.py", line 131, in get_default_expectation_suite_name
    suite_name = f"batch-{BatchRequest(**batch_request).id}"
TypeError: BatchRequest.__init__() missing 1 required positional argument: 'data_asset_name'
```

C:\Users\user\great_expectations>

**Comment by talagluck** [comment]
Hi @bachhavdipak - have you set up a Datasource yet? You would see this error when running `great_expectations suite new` from the CLI without a properly configured Datasource. If you haven't already, I'd recommend going through the [Getting Started Tutorial](https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_overview) which will walk you through the process of setting up a GX project from start to finish.

I'm going to close this in the meantime since this is a configuration issue rather than a bug (and we have some planned CLI improvement work in the not-too-distant future), but if you have further questions, please feel free to ask in our Slack.

**Comment by bachhavdipak** [comment]
@talagluck : 

I am facing the below issue while setting up the data source. Also not allow me to perform the below step

```
Enter the path of the root directory where the data files are stored. If files are on local disk
enter a path relative to your current working directory or an absolute path.
:data 
```
Error : 
```
What data would you like Great Expectations to connect to?
    1. Files on a filesystem (for processing with Pandas or Spark)
    2. Relational database (SQL)
: 1

What are you processing your files with?
1. Pandas
2. PySpark
: 1

Enter the path of the root directory where the data files are stored. If files are on local disk enter a path relative to your current working directory or an absolute path.
: 1
Please install the optional dependency 'black' to enable linting. Returning input with no changes.
Because you requested to create a new Datasource, we'll open a notebook for you now to complete it!


[I 09:17:54.930 NotebookApp] Serving notebooks from local directory: C:\Users\dipak.bachhav\ge_webinar_demo\great_expectations\uncommitted
[I 09:17:54.930 NotebookApp] Jupyter Notebook 6.4.12 is running at:
[I 09:17:54.933 NotebookApp] http://localhost:8888/?token=cddc4c0730f8b457bd93886220d84ed1f98c3c768196f0f0
[I 09:17:54.934 NotebookApp]  or http://127.0.0.1:8888/?token=cddc4c0730f8b457bd93886220d84ed1f98c3c768196f0f0
[I 09:17:54.940 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 09:17:55.041 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/dipak.bachhav/AppData/Roaming/jupyter/runtime/nbserver-2224-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=cddc4c0730f8b457bd93886220d84ed1f98c3c768196f0f0
     or http://127.0.0.1:8888/?token=cddc4c0730f8b457bd93886220d84ed1f98c3c768196f0f0
[W 09:18:00.598 NotebookApp] Notebook datasource_new.ipynb is not trusted
[I 09:18:01.544 NotebookApp] Kernel started: d84ca72a-4ac1-4af1-8301-a6db8b45f612, name: python3
[IPKernelApp] ERROR | No such comm target registered: jupyter.widget.control
[IPKernelApp] WARNING | No such comm: f32feba4-ded6-46ad-aa0e-42efb6f55efe
```
referring official document :https://docs.greatexpectations.io/docs/tutorials/getting_started/tutorial_connect_to_data

**Comment by bachhavdipak** [comment]
@talagluck : I have already setup Datasource but can't see the data folder under great_expectations folder after running Jupyter Notebook


```
[{'class_name': 'Datasource',
  'data_connectors': {'default_inferred_data_connector_name': {'base_directory': '..\\data',
    'class_name': 'InferredAssetFilesystemDataConnector',
    'default_regex': {'group_names': ['data_asset_name'], 'pattern': '(.*)'},
    'module_name': 'great_expectations.datasource.data_connector'},
   'default_runtime_data_connector_name': {'class_name': 'RuntimeDataConnector',
    'assets': {'my_runtime_asset_name': {'batch_identifiers': ['runtime_batch_identifier_name'],
      'class_name': 'Asset',
      'module_name': 'great_expectations.datasource.data_connector.asset'}},
    'module_name': 'great_expectations.datasource.data_connector'}},
  'module_name': 'great_expectations.datasource',
  'execution_engine': {'class_name': 'PandasExecutionEngine',
   'module_name': 'great_expectations.execution_engine'},
  'name': 'getting_started_datasource'},
 {'class_name': 'Datasource',
  'data_connectors': {'default_inferred_data_connector_name': {'base_directory': '..\\data',
    'class_name': 'InferredAssetFilesystemDataConnector',
    'default_regex': {'group_names': ['data_asset_name'], 'pattern': '(.*)'},
    'module_name': 'great_expectations.datasource.data_connector'},
   'default_runtime_data_connector_name': {'class_name': 'RuntimeDataConnector',
    'assets': {'my_runtime_asset_name': {'batch_identifiers': ['runtime_batch_identifier_name'],
      'class_name': 'Asset',
      'module_name': 'great_expectations.datasource.data_connector.asset'}},
    'module_name': 'great_expectations.datasource.data_connector'}},
  'module_name': 'great_expectations.datasource',
  'execution_engine': {'class_name': 'PandasExecutionEngine',
   'module_name': 'great_expectations.execution_engine'},
  'name': 'my_datasource'}] 
```



great_expectations.yml

```
# Welcome to Great Expectations! Always know what to expect from your data.
#
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview/#2-configure-your-datasource
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 3.0

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
datasources:
  getting_started_datasource:
    class_name: Datasource
    module_name: great_expectations.datasource
    execution_engine:
      class_name: PandasExecutionEngine
      module_name: great_expectations.execution_engine
    data_connectors:
      default_inferred_data_connector_name:
        base_directory: ..\data
        class_name: InferredAssetFilesystemDataConnector
        module_name: great_expectations.datasource.data_connector
        default_regex:
          group_names:
            - data_asset_name
          pattern: (.*)
      default_runtime_data_connector_name:
        assets:
          my_runtime_asset_name:
            class_name: Asset
            module_name: great_expectations.datasource.data_connector.asset
            batch_identifiers:
              - runtime_batch_identifier_name
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
  my_datasource:
    class_name: Datasource
    module_name: great_expectations.datasource
    execution_engine:
      class_name: PandasExecutionEngine
      module_name: great_expectations.execution_engine
    data_connectors:
      default_inferred_data_connector_name:
        base_directory: ..\data
        class_name: InferredAssetFilesystemDataConnector
        module_name: great_expectations.datasource.data_connector
        default_regex:
          group_names:
            - data_asset_name
          pattern: (.*)
      default_runtime_data_connector_name:
        assets:
          my_runtime_asset_name:
            class_name: Asset
            module_name: great_expectations.datasource.data_connector.asset
            batch_identifiers:
              - runtime_batch_identifier_name
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
#
# Three stores are required: expectations, validations, and
# evaluation_parameters, and must exist with a valid store entry. Additional
# stores can be configured for uses such as data_docs, etc.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    # Evaluation Parameters enable dynamic expectations. Read more here:
    # https://docs.greatexpectations.io/docs/reference/evaluation_parameters/
    class_name: EvaluationParameterStore

  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    # set to false to hide how-to buttons in Data Docs
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: 7f0914de-a1f2-4f42-acae-572baf64a57f
  enabled: true
notebooks:
```
