### ISSUE TITLE
[BUG] Using Trino with runtime data connector produce invalid query

### ISSUE THREAD

**Issue by itaise** [fivetran/great_expectations#5827]
We are using Trino successfuly using Configured data connector, but when trying to use it with Runtime data connector we encountered a possible bug. 
The query that is produced is missing parentheses in the subquery, so the query fails on invalid syntax in Trino. 
the query looks like the following in Trino, seems like GE treats it as a table instead of a sub query:
```
SELECT count(*) AS "table.row_count"
FROM SELECT * from iprod.daily_actions.my_table LIMIT 10
```

instead of the required result: 
```
SELECT count(*) AS "table.row_count"
FROM (SELECT * from iprod.daily_actions.my_table LIMIT 10)
```

This is how we configured the **checkpoint**:
```
name: my_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: SimpleCheckpoint
run_name_template:
expectation_suite_name: test_suite

validations:
  - batch_request:
      datasource_name: my_trino_datasource
      data_connector_name: default_runtime_data_connector_name
      runtime_parameters: { 'query': 'SELECT * from iprod.daily_actions.my_table LIMIT 10' }
      data_asset_name: default_name
      batch_identifiers: {"default_identifier_name": "default_identifier" }

    expectation_suite_name: test_suite
    action_list:
      - name: store_validation_result
        action:
          class_name: StoreValidationResultAction
      - name: store_evaluation_params
        action:
          class_name: StoreEvaluationParametersAction
      - name: update_data_docs
        action:
          class_name: UpdateDataDocsAction
evaluation_parameters: {}
runtime_configuration: {}
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
```

and our **data source** in the great_expectation.yml file: 
```
datasources:
  my_trino_datasource:
    data_connectors:
      default_runtime_data_connector_name:
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
    class_name: Datasource
    module_name: great_expectations.datasource
    execution_engine:
      module_name: great_expectations.execution_engine
      connection_string: trino://great_expectations@bi-was-presto-master0a.42.wixprod.net:8181/daily_actions/dwh_sanity_tests?source=great_expectations_tests
      class_name: SqlAlchemyExecutionEngine
```

**Environment (please complete the following information):**
 - MacOS Monterey
 - Great Expectations Version: 0.15.19
