### ISSUE TITLE
BigQuery expect_column_values_to_be_unique fails for String values

### ISSUE THREAD

**Issue by cah-jamey-weyenberg** [fivetran/great_expectations#5865]
Using a BigQuery datasource, with the following batch_request in a checkpoint: 
```
  - batch_request:
      datasource_name: bigquery_l0
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: l0_icd.icd_sg
      batch_spec_passthrough:
        create_temp_table: False
      data_connector_query:
        index: -1
    expectation_suite_name: rfrnc_bq_icd_sg_suite
```
I get the result that there were "800250 unexpected values found. 100% of 800250 total rows.". Which is obviously incorrect as this would imply that every value is the same. The values in this column are strings. I ran the same expectation against a much smaller table in GCS (also with strings) and got the correct, expected, result. I'm not sure if the issue is with BigQuery specifically, but the issue was not present in my small test with GCS. 

For reference, this is the exact expectation I have: 
```
{
      "expectation_type": "expect_column_values_to_be_unique",
      "kwargs": {
        "column": "ICD_ID"
      },
      "meta": {}
    },
```

**Expected behavior**
The expectation should identify any duplicate values present and fail if there are any. Otherwise, the expectation should pass.

**Environment (please complete the following information):**
 - Operating System: Linux virtual machine
 - Great Expectations Version: 0.14.13
