### ISSUE TITLE
Batch Request returns empty list with InferredAssetAzureDataConnector

### ISSUE THREAD

**Issue by pfuerste** [fivetran/great_expectations#6308]
**Describe the bug**
I am intending to set up an Azure Blob storage data source for great expectations. The setup is done with the following string and seems to work, given it lists some files in my blob storage. But when trying to connect to my data source, the Batch request yields an empty list.

```
example_yaml = f"""
name: {datasource_name}
class_name: Datasource
execution_engine:
    class_name: PandasExecutionEngine
    azure_options:
        account_url: MYURL
        credential: MYKEY
data_connectors:
  default_runtime_data_connector_name:
    class_name: RuntimeDataConnector
    batch_identifiers:
        - default_identifier_name
  default_inferred_data_connector_name:
    class_name: InferredAssetAzureDataConnector
    azure_options:
        account_url: MYURL
        credential: MYKEY
    container: machinelearning
    name_starts_with: waermeprognose/output_neuralnet/FVS/FERNWAERME.1
    default_regex:
        pattern: (.*)\_FVS_FERNWAERME.1_waermeprognose.parquet
        group_names:
            - date
"""
```
Context.test_yaml_config(yaml_config=example_yaml) then returns

``` 
Attempting to instantiate class from config...
	Instantiating as a Datasource, since class_name is Datasource
	Successfully instantiated Datasource


ExecutionEngine class name: PandasExecutionEngine
Data Connectors:
	default_inferred_data_connector_name : InferredAssetAzureDataConnector

	Available data_asset_names (1 of 1):
		DEFAULT_ASSET_NAME (3 of 354): ['waermeprognose/output_neuralnet/FVS/FERNWAERME.1/2021-12-01_FVS_FERNWAERME*1_waermeprognose*parquet', 'waermeprognose/output_neuralnet/FVS/FERNWAERME.1/2021-12-02_FVS_FERNWAERME*1_waermeprognose*parquet', 'waermeprognose/output_neuralnet/FVS/FERNWAERME.1/2021-12-03_FVS_FERNWAERME*1_waermeprognose*parquet']

	Unmatched data_references (0 of 0):[]

	default_runtime_data_connector_name:RuntimeDataConnector

	Available data_asset_names (0 of 0):
		Note : RuntimeDataConnector will not have data_asset_names until they are passed in through RuntimeBatchRequest

	Unmatched data_references (0 of 0): []
```
I then save the source to my context using sanitize_yaml_and_save_datasource(context, example_yaml, overwrite_existing=True), but when I try to set up some expectations, the Batch Request is empty:
```
context = DataContext(
    context_root_dir=r'C:\Users\Philip\Documents\Projekte\X\Python\tests\great_expectations'
)

batch_request_parameters = {
    "datasource_name": "dlsbeoptdev_machinelearning_waermeprognose_output_neuralnet",
    "data_connector_name": "default_inferred_data_connector_name",
    "data_asset_name": "DEFAULT_ASSET_NAME",
}

batch_request = BatchRequest(**batch_request_parameters)
print(context.get_batch_list(batch_request=batch_request))
```

Only return as empty list which I can't use to set up a validator.

**Expected behavior**
I would expect the Request to return all files matching the regex.

**Environment (please complete the following information):**
 - Operating System: Windows 11
 - Great Expectations Version:  0.15.30
