### ISSUE TITLE
[BUG] S3 Reports keep overwriting themselves

### ISSUE THREAD

**Issue by adam-mrozik** [fivetran/great_expectations#6314]
**Describe the bug**
S3 reports overwrite themselves
**To Reproduce**
My configuration:

great-expectations.yaml
```
  # Welcome to Great Expectations! Always know what to expect from your data.
  #
  # Here you can define datasources, batch kwargs generators, integrations and
  # more. This file is intended to be committed to your repo. For help with
  # configuration please:
  #   - Read our docs: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview/#2-configure-your-datasource
  #   - Join our slack channel: http://greatexpectations.io/slack

  # config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
  # It is auto-generated and usually does not need to be changed.
config_version: 3.0

  # Datasources tell Great Expectations where your data lives and how to get it.
  # You can use the CLI command `great_expectations datasource new` to help you
  # add a new datasource. Read more at https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
datasources:
  imi_clickhouse:
    execution_engine:
      connection_string: clickhouse+native://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
    data_connectors:
      default_runtime_data_connector_name:
        name: default_runtime_data_connector_name
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
      default_inferred_data_connector_name:
        name: default_inferred_data_connector_name
        include_schema_name: true
        module_name: great_expectations.datasource.data_connector
        class_name: InferredAssetSqlDataConnector
    module_name: great_expectations.datasource
    class_name: Datasource
config_variables_file_path: uncommitted/config_variables.yml

  # The plugins_directory will be added to your python path for custom modules
  # used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
  # Stores are configurable places to store things like Expectations, Validations
  # Data Docs, and more. These are for advanced users only - most users can simply
  # leave this section alone.
  #
  # Three stores are required: expectations, validations, and
  # evaluation_parameters, and must exist with a valid store entry. Additional
  # stores can be configured for uses such as data_docs, etc.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_S3_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: ${DATA_QUALITY_BUCKET_NAME}
      prefix: ''

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
    # Data Docs make it simple to visualize data quality in your project. These
    # include Expectations, Validations & Profiles. The are built for all
    # Datasources from JSON artifacts in the local repo including validations &
    # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
  s3_site:
    class_name: SiteBuilder
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: ${DATA_QUALITY_BUCKET_NAME}
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
      show_cta_footer: true
anonymous_usage_statistics:
  enabled: true
  data_context_id: fba52fb7-dd96-4126-a160-76332927b887
include_rendered_content:
  expectation_validation_result: false
  expectation_suite: false
  globally: false
notebooks:
```

global_checkpoint.yaml
```
name: global_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template:
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
  - name: send_slack_notification_on_validation_result # name can be set to any value
    action:
      class_name: SlackNotificationAction
      # put the actual webhook URL in the uncommitted/config_variables.yml file or as env var
      slack_webhook: ${SLACK_URI}
      notify_on: failure # possible values: "all", "failure", "success"
      notify_with:
        - s3_site
      renderer:
        module_name: great_expectations.render.renderer.slack_renderer
        class_name: SlackRenderer
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: imi_clickhouse
      data_connector_name: default_runtime_data_connector_name
      data_asset_name: ${DB_NAME}.event
    expectation_suite_name: clickhouse_event
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:

```

Script running the code:
```
    now_str = datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%S")

    if sql_query_template:
        query = sql_query_template.format(cols=cols, asset_name=asset_name)
    else:
        query = build_initial_query(asset_name.split(".")[-1], expectations_suite_name, minutes_of_data=minutes)

    logger.info(f"Running checkpoint {checkpoint_name} against the data from query: {query}")

    run_name = f"{checkpoint_name}_quality_check_{now_str}"
    context.run_checkpoint(
        checkpoint_name=checkpoint_name,
        run_name=run_name,
        batch_request={
            "runtime_parameters": {"query": f"({query})"},
            "batch_spec_passthrough": {"create_temp_table": False},
            "batch_identifiers": {"default_identifier_name": run_name},
        },
    )
```

**Expected behavior**
Reports would be 
**Environment (please complete the following information):**
 - Alpine Docker
 - Great Expectations Version: 0.15.28

**Additional context**
Interestingly enough, I run the same script on my Ubuntu machine and it does not overwrite, it creates a new folder:
```
my-pc:~/ge/$ aws --profile data s3 ls s3://data-quality-reports-prod/validations/clickhouse_event/
                           PRE global_checkpoint_quality_check_2022-11-07T15:09:28/
                           PRE global_checkpoint_quality_check_2022-11-07T15:13:15/
```
But, on PROD, it deletes all and creates single folder every 15 minutes it runs(cronjob)

And there is no difference between my local run and the prod run, so I have no idea why it could be happening. Any ideas are gladly welcomed
