### ISSUE TITLE
Useless query before main checks with using RuntimeBatchRequest

### ISSUE THREAD

**Issue by donRumata83** [fivetran/great_expectations#6360]
I'm using GE with SQLAlchemy against tables in Vertica (one of the cases). I'm creating all the configurations inside the python code. For Batching the data for checking we decide to use SQL which selecting data by start and end date in timestamp columns. For this I was using: as Data connector RuntimeDataConnector and creating batch request as RuntimeBatchRequest in code like this:
```
def get_batch_request(self, runtime_config, expectations_context, query, run_identifier):
    return RuntimeBatchRequest(
        datasource_name=runtime_config.datasource_type.name,
        data_connector_name=runtime_config.data_connector_name,
        data_asset_name=f'{runtime_config.database_name}.{runtime_config.table_name}',
        runtime_parameters={'query': query},
        batch_identifiers={"batch_id": f'{runtime_config.database_name}'
                                       f'.{runtime_config.table_name}'
                                       f'.{datetime.datetime.now()}'},
        batch_spec_passthrough={'create_temp_table': False}
    )
```
And then using it in checkpoint like this:
```
return Checkpoint(name='checkpoint',
                  config_version=1.0,
                  action_list=actions,
                  data_context=expectations_context,
                  validations=[batch_request],
                  expectation_suite_name=runtime_config.suite_name)
```
So what is the problem: after some testing, I've noticed that we have an extra query before GE run their checks. F.ex. for checking suite with 2 expectations expect_column_values_to_not_be_null and expect_table_row_count_to_be_between Vertica query_requests table returns 4 query which were ran by my user
```
SELECT * FROM collection_acquired_mk2 WHERE is_sys_kafka_ts >= '2022-11-07 23:30:00' AND is_sys_kafka_ts < '2022-11-08 23:29:59'

SELECT sum(CASE WHEN (uuid IS NULL) THEN 1 ELSE 0 END) AS "column_values.nonnull.unexpected_count"  FROM (SELECT * FROM collection_acquired_mk2 WHERE is_sys_kafka_ts >= '2022-11-07 23:30:00' AND is_sys_kafka_ts < '2022-11-08 23:29:59') AS anon_1

SELECT uuid AS unexpected_values  FROM (SELECT * FROM collection_acquired_mk2 WHERE is_sys_kafka_ts >= '2022-11-07 23:30:00' AND is_sys_kafka_ts < '2022-11-08 23:29:59') AS anon_1  WHERE uuid IS NULL   LIMIT 20

SELECT count(*) AS "table.row_count"  FROM (SELECT * FROM collection_acquired_mk2 WHERE is_sys_kafka_ts >= '2022-11-07 23:30:00' AND is_sys_kafka_ts < '2022-11-08 23:29:59') AS anon_1
```

**To Reproduce**
1. Configure GE datasource ike this: 
```
datasources:
  vertica:
    execution_engine:
      credentials:
        drivername: vertica+vertica_python
        host: ${vertica.host}
        port: 5433
        username: ${vertica.username}
        password: ${vertica.password}
        database: ${vertica.database}
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
      create_temp_table: False
      supports_statement_cache: False
    module_name: great_expectations.datasource
    class_name: Datasource
    data_connectors:
      vertica_connector:
        module_name: great_expectations.datasource.data_connector
        class_name: RuntimeDataConnector
        batch_identifiers:
          - batch_id
 ```
Configuration is for Vertica, but I think it should be the same behavior for any other SQL like DB and SQLAlchemy as execution engine.
2. For batching data, use query:
`SELECT * FROM collection_acquired_mk2 WHERE is_sys_kafka_ts >= '2022-11-07 23:30:00' AND is_sys_kafka_ts < '2022-11-08 23:29:59'`
3. Create expectations suite with two expectations
4. Run Checkpoint
5. Select from table select * from query_requests where user_name='user_name' order by end_timestamp DESC ; (works in Vertica, but I didn't check other DB)
6. Check the result

**Expected behavior**
Fist query is useless in case when we are using SQL Alchemy as an execution engine.

**Environment (please complete the following information):**
 - Great Expectations Version: great_expectations==0.15.29
 - sqlalchemy-vertica-python==0.5.10
 - great_expectations_experimental==0.1.20221027072
 - SQLAlchemy==1.4.42

**Additional context**
As I could understand, it is a "generic" behavior of RuntimeBatchRequest. So can I somehow change the configuration to avoid this useless query? I was looking on  ConfiguredAssetSqlDataConnector, but I didn't find an appropriate method for splitting table data in a way like we do. Any ideas?
