### ISSUE TITLE
Unrecognized urn_type in ge_urn: must be ‘stores’ to use a metric store

### ISSUE THREAD

**Issue by cmck** [fivetran/great_expectations#6409]
**Describe the bug**
I could be missing a simple step here. After following the the guide at "How to create Expectations that span multiple Batches using Evaluation Parameters" at
https://docs.greatexpectations.io/docs/guides/expectations/advanced/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters/

I get the following error:

`Unrecognized urn_type in ge_urn: must be ‘stores’ to use a metric store`
`EvaluationParameterError: No value found for $PARAMETER urn:great_expectations:validations:<MY_DOWNSTREAM_EXPECTATION_SUITE>:expect_table_row_count_to_be_between.result.observed_value`

```
EvaluationParameterError                  Traceback (most recent call last)
Cell In [6], line 1
----> 1 results1 = context.run_checkpoint(
      2   checkpoint_name="<MY_CHECKPOINT>"
      3 )

File ~/path/to/.venv/lib/python3.8/site-packages/great_expectations/core/usage_statistics/usage_statistics.py:304, in usage_statistics_enabled_method.<locals>.usage_statistics_wrapped_method(*args, **kwargs)
    301     if args_payload_fn is not None:
    302         nested_update(event_payload, args_payload_fn(*args, **kwargs))
--> 304     result = func(*args, **kwargs)
    305     message["success"] = True
    306 except Exception:

File ~/path/to/.venv/lib/python3.8/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:1244, in AbstractDataContext.run_checkpoint(self, checkpoint_name, ge_cloud_id, template_name, run_name_template, expectation_suite_name, batch_request, action_list, evaluation_parameters, runtime_configuration, validations, profilers, run_id, run_name, run_time, result_format, expectation_suite_ge_cloud_id, **kwargs)
   1216 """
   1217 Validate against a pre-defined Checkpoint. (Experimental)
   1218 Args:
   (...)
   1238     CheckpointResult
   1239 """
   1240 checkpoint: Checkpoint = self.get_checkpoint(
   1241     name=checkpoint_name,
   1242     ge_cloud_id=ge_cloud_id,
   1243 )
...
    361     logger.debug(
    362         f"Parse exception while parsing evaluation parameter: {str(e)}"
    363     )

EvaluationParameterError: No value found for $PARAMETER urn:great_expectations:validations:<MY_DOWNSTREAM_EXPECTATION_SUITE>:expect_table_row_count_to_be_between.result.observed_value
```

**To Reproduce**

1. Follow the guide at  "How to create Expectations that span multiple Batches using Evaluation Parameters" at
https://docs.greatexpectations.io/docs/guides/expectations/advanced/how_to_create_expectations_that_span_multiple_batches_using_evaluation_parameters/

- I am using Postgres upstream and Postgres downstream data sources. 
- Project is very basic with nothing custom. Expectations were generated by GE profilers as per the getting started docs.
- I am using jupyter notebook as per the documentation at the web page.
- I am using in-memory evaluation parameter store
- Validations results exist for both the upstream and the downstream. At the upstream, a result for `expect_table_row_count_to_be_between` exists in a validation result.
- In the downstream expectation suite I can see the following was added which looks correct:
```
    {
      "expectation_type": "expect_table_row_count_to_equal",
      "kwargs": {
        "value": {
          "$PARAMETER": "urn:great_expectations:validations:<MY_DOWNSTREAM_EXPECTATION_SUITE>:expect_table_row_count_to_be_between.result.observed_value"
        }
      },
      "meta": {}
    }
```
- My checkpoint looks like this:
```
---
name: <NAME>
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-checkpoint'
expectation_suite_name:
batch_request: {}
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: <MY_DOWNSTREAM_DATASOURCE>
      data_connector_name: default_configured_data_connector_name
      data_asset_name: <MY_DATA_TABLE>
      data_connector_query:
        index: -1
    expectation_suite_name: <MY_DOWNSTREAM_EXPECTATION_SUITE>
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
```

**Expected behavior**
I'm expecting the downstream to read the expectation observed value from the upstream validation result.

**Environment (please complete the following information):**
 - Mac OS
 - Great Expectations Version: 0.15.34, 0.15.33, 0.15.32

**Additional context**
Edit: This issue is still unresolved, however as a workaround for anyone interested I am using Metric Store + dynamically loading eval params from the metric store using `SqlAlchemyQueryStore` as per: https://docs.greatexpectations.io/docs/guides/expectations/advanced/how_to_dynamically_load_evaluation_parameters_from_a_database
in order to compare values between batch requests.
