### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'config_variables_file_path'  when creating context with yaml only

### ISSUE THREAD

**Issue by pfuerste** [fivetran/great_expectations#6415]
**Describe the bug**
I am trying to validate my data without a great_expectations-folder, but I am having problems defining my context:
Trying to call ge.get_context(y) or ge.data_context.BaseDataContext(y) with y as either a path to a yaml or dict from that yaml throws
`AttributeError: 'dict' object has no attribute 'config_variables_file_path' ` . 
The dict contains that key though. If using ge.get_context without arguments in the folder with the yaml file in it, everything works fine. 
I tried passing y as different parameters (project_config, context_root_dir, runtime_environment) of get_context, but none work. The behaviour is the same in my project and the great expectations tutorial.

**To Reproduce**
1. Use the tutorial folder after completing it.
2. Run the following script:
```
with open("/tutorials/great_expectations/great_expectations.yml", "r") as file:
    cfg = yaml.safe_load(file)
context = ge.get_context(cfg)
```
3. See error above

**Expected behavior**
```
with open("/tutorials/great_expectations/great_expectations.yml", "r") as file:
    cfg = yaml.safe_load(file)
context = ge.get_context(cfg)
```
Should return a DataContext object.

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]: Ubuntu 20.04.5 LTS (under WSL2) & also on Windows 11
 - Great Expectations Version: [e.g. 0.13.2]: 0.15.30

**Additional Context**
Is this similar to https://github.com/great-expectations/great_expectations/issues/5663?

Edit: Here is my great_expectations.yml:

```
# Welcome to Great Expectations! Always know what to expect from your data.
#
# Here you can define datasources, batch kwargs generators, integrations and
# more. This file is intended to be committed to your repo. For help with
# configuration please:
#   - Read our docs: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview/#2-configure-your-datasource
#   - Join our slack channel: http://greatexpectations.io/slack

# config_version refers to the syntactic version of this config file, and is used in maintaining backwards compatibility
# It is auto-generated and usually does not need to be changed.
config_version: 3.0

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
datasources:
  waermeprognose_all:
    execution_engine:
      class_name: PandasExecutionEngine
      module_name: great_expectations.execution_engine
    data_connectors:
      default_inferred_data_connector_name:
        glob_directive: '*/*/*'
        name: default_inferred_data_connector_name
        base_directory: ../../../test/waermeprognose/sample_input/waermeprognose/input
        default_regex:
          group_names:
            - data_asset_name
          pattern: (.*)\.parquet
        class_name: InferredAssetFilesystemDataConnector
        module_name: great_expectations.datasource.data_connector
      default_runtime_data_connector_name:
        assets:
          my_runtime_asset_name:
            batch_identifiers:
              - runtime_batch_identifier_name
            class_name: Asset
            module_name: great_expectations.datasource.data_connector.asset
        name: default_runtime_data_connector_name
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
    class_name: Datasource
    module_name: great_expectations.datasource
  union_hist_wps:
    execution_engine:
      class_name: PandasExecutionEngine
      module_name: great_expectations.execution_engine
    data_connectors:
      default_inferred_data_connector_name:
        name: default_inferred_data_connector_name
        base_directory: ../../../test/waermeprognose/sample_input/waermeprognose
        default_regex:
          group_names:
            - data_asset_name
          pattern: (.*)\.csv
        class_name: InferredAssetFilesystemDataConnector
        module_name: great_expectations.datasource.data_connector
      default_runtime_data_connector_name:
        assets:
          my_runtime_asset_name:
            batch_identifiers:
              - runtime_batch_identifier_name
            class_name: Asset
            module_name: great_expectations.datasource.data_connector.asset
        name: default_runtime_data_connector_name
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
    class_name: Datasource
    module_name: great_expectations.datasource
  example_datasource:
    execution_engine:
      class_name: PandasExecutionEngine
      module_name: great_expectations.execution_engine
    data_connectors:
      default_runtime_data_connector_name:
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
    class_name: Datasource
    module_name: great_expectations.datasource
config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
#
# Three stores are required: expectations, validations, and
# evaluation_parameters, and must exist with a valid store entry. Additional
# stores can be configured for uses such as data_docs, etc.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  enabled: true
  data_context_id: a1ef88aa-57a1-4a6f-a0ab-6c649511f4d4
notebooks:
include_rendered_content:
  globally: false
  expectation_validation_result: false
  expectation_suite: false

```
