### ISSUE TITLE
Checkpoints are failing with RuntimeBatchRequest using trino

### ISSUE THREAD

**Issue by jarrobin** [fivetran/great_expectations#6591]
**Describe the bug**
 I am using trino Python api (trino[sqlalchemy]==0.319.0) in combination with great expectations (great_expectations==0.15.32). In great expectations when creating a RuntimeBatchRequest and accessing columns atrribute results in an empty list (I checked that table exists in schema and catalog). This has as consequence that running a simple checkpoint all tests are failing as they need column reference (not shown in reproduction example). However, `validator.head()` does show me the data with column headers.

**To Reproduce**
```
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.checkpoint.types.checkpoint_result import CheckpointResult

batch_request = RuntimeBatchRequest(
    datasource_name="trino_dev",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="dummyresult1",  # this can be anything that identifies this data
    runtime_parameters={"query": "SELECT * from schema.dummytable WHERE dummycol=1234"},
    batch_identifiers={"default_identifier_name": "default_identifier_name"},
)
validator = context.get_validator(
    batch_request=batch_request
)
column_names = [f'"{column_name}"' for column_name in validator.columns()]
print(column_names)

## Result
[]

## Expecs
validator.expect_column_max_to_be_between("sample_col", max_value=1, min_value=0)

## Result: MetricResolutionError: Error: The column "sample_col" in BatchData does not exist.
```
Note: Exchanging `RuntimeBatchRequest` with `BatchRequest` table columns get printed correctly.

**Expected behavior**
Result is not an empty list

**Environment (please complete the following information):**
 - Operating System: Docker image python:3.9
 - Great Expectations Version: 0.15.32

**Additional context**
Data Context:
```
datasources:
  trino_dev:
    data_connectors:
      default_runtime_data_connector_name:
        batch_identifiers:
          - default_identifier_name
        name: default_runtime_data_connector_name
        module_name: great_expectations.datasource.data_connector
        class_name: RuntimeDataConnector
    module_name: great_expectations.datasource
    class_name: Datasource
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      credentials:
        host: ${TRINO_URL}
        port: ${TRINO_PORT}
        username: ${TRINO_USER}
        password: ${TRINO_PASSWORD}
        database: ${TRINO_DATABASE}
        drivername: trino
      module_name: great_expectations.execution_engine
```
