### ISSUE TITLE
Portal Page Failure to Load (GE 0.15.41)

### ISSUE THREAD

**Issue by diveyseek** [fivetran/great_expectations#6701]
**Describe the bug**
After upgrading to 0.15.41 from 0.13.45 the GE Portal Page falls into an endless loop
This appears to related to a change in the code below

**To Reproduce**
With the latest version of GE (0.15.41), and the following configuration, the data doc is generating a dark version.
```
    class_name: SiteBuilder
    show_how_to_buttons: false
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: ${DATA_DOCS_S3_BUCKET}  # UPDATE the bucket name here to match the bucket you configured above.
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
      show_cta_footer: false
      validation_results_limit: 1600
```

With 1600 validation results the newer dark version page just keeps loading (the page hangs and I can’t click anywhere)  while the older white version used to load within seconds (we were using GE version 0.13.45 before). 

If I replace the following scripts in the index page generated by v 0.15.41 with older versions of these script, the page loads within seconds.

```
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>

    <link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap-table@1.19.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@forevolve/bootstrap-dark@1.1.0/dist/css/bootstrap-prefers-dark.css" />

<script src="https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
```

I replaced them with the following script link to make the page work without an issue

```
  <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"/>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.css">
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">

<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/bootstrap-table.min.js"></script>
<script src="https://unpkg.com/bootstrap-table@1.16.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.js"></script>
```

**Expected behavior**
Expected behavior is that the page would load quickly as it previously did

**Environment (please complete the following information):**
 - Operating System: Mac & Linux (Docker)
 - Great Expectations Version: 0.15.41

**Slack Discussion Link**
https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1672813510401399
