### ISSUE TITLE
MS Teams receiving no GE Notifications

### ISSUE THREAD

**Issue by Yamden** [fivetran/great_expectations#6710]
**Describe the bug**
Hello,
I've been trying to trigger GE notifications by a MS Teams webhook rather than Slack. I have set up the checkpoint config as follows (using a SimpleCheckpoint):
```
 {
   "name": "send_teams_notification_on_validation_result",
   "action": {
     "class_name": "MicrosoftTeamsNotificationAction",
     "microsoft_teams_webhook": "${teams_webhook}",
     "notify_on": "all",
     "renderer": {
       "module_name": "great_expectations.render.renderer.microsoft_teams_renderer",
       "class_name": "MicrosoftTeamsRenderer"
   }
 }
 }
```
And I have set the MS teams url in config_variables.yml as `teams_webhook`. 
I have verified that the webhook is functional, other actions work as intended, and that no error messages are being logged in command line or anywhere else. Yet when running an expectation I receive no notifications, am I missing a step somewhere?

**To Reproduce**
1. Follow the procedure to setup checkpoint config, config_variables.yml, and MS teams webhook: https://github.com/great-expectations/great_expectations/issues/3883
2. Run checkpoint

**Expected behavior**
Checkpoint notifications are pushed to MS Teams 

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.15.27

**Comment by austiezr** [comment]
Hey @Yamden ! Thanks for raising this. Are you able to share your `great_expectations.yml`? That will help us to better understand what may be happening here.

**Comment by Yamden** [comment]
Sure thing!
```
config_version: 3.0

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations datasource new` to help you
# add a new datasource. Read more at[ https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview)
datasources:
  postgresql_datasource:
    execution_engine:
      connection_string: postgresql+psycopg2://admin:adminpassword@localhost:5432/--redacted--
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
    name: postgresql_datasource
    module_name: great_expectations.datasource
    data_connectors:
      default_runtime_data_connector_name:
        batch_identifiers:
          - default_identifier_name
        name: default_runtime_data_connector_name
        module_name: great_expectations.datasource.data_connector
        class_name: RuntimeDataConnector
      default_inferred_data_connector_name:
        name: default_inferred_data_connector_name
        module_name: great_expectations.datasource.data_connector
        include_schema_name: true
       class_name: InferredAssetSqlDataConnector
    class_name: Datasource
  s3_datasource:
    execution_engine:
      class_name: PandasExecutionEngine
      module_name: great_expectations.execution_engine
    module_name: great_expectations.datasource
    data_connectors:
      InternalS3Connector:
        prefix: ''
        assets:
          lookup-bac-ads:
            pattern: lookup-bac-ads(?!_definition).json
            group_names:
              - bac-ads
            module_name: great_expectations.datasource.data_connector.asset
            --other assets redacted--
        boto3_options:
          endpoint_url: http://localhost:9001
          aws_access_key_id: redacted
          aws_secret_access_key: redacted
        module_name: great_expectations.datasource.data_connector
        bucket: redacted
        class_name: ConfiguredAssetS3DataConnector
    class_name: Datasource
config_variables_file_path: uncommitted/config_variables.yml

# The plugins_directory will be added to your python path for custom modules
# used to override and extend Great Expectations.
plugins_directory: plugins/

stores:
# Stores are configurable places to store things like Expectations, Validations
# Data Docs, and more. These are for advanced users only - most users can simply
# leave this section alone.
#
# Three stores are required: expectations, validations, and
# evaluation_parameters, and must exist with a valid store entry. Additional
# stores can be configured for uses such as data_docs, etc.
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  # Data Docs make it simple to visualize data quality in your project. These
  # include Expectations, Validations & Profiles. The are built for all
  # Datasources from JSON artifacts in the local repo including validations &
  # profiles from the uncommitted directory. Read more at https://docs.greatexpectations.io/docs/terms/data_docs
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder
      validation_results_limit: 30

anonymous_usage_statistics:
  enabled: true
  data_context_id: c31b7721-8d2d-4d73-9c60-fe8576e982f3
notebooks:
include_rendered_content:
  expectation_validation_result: false
  globally: false
  expectation_suite: false
```
