### ISSUE TITLE
Encountering runtime error when checkpoint tries NoOpAction

### ISSUE THREAD

**Issue by jamesngo** [fivetran/great_expectations#6847]
Using great expectations 0.15.41 throws runtime exception when running a skeleton checkpoint. 
Checkpoint configuration:
```
name: birthday_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-birthday-checkpoint'
expectation_suite_name:
batch_request: {}
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: test
      data_connector_name: test_connector
      data_asset_name: test_data
      data_connector_query:
        index: -1
    expectation_suite_name: birthday_suite
    action_list: 
      - name: no_op
        action:
          class_name: NoOpAction
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
```

expectations suite:
```
{
  "data_asset_type": null,
  "expectation_suite_name": "birthday_suite",
  "expectations": [
    {
      "expectation_type": "expect_table_row_count_to_be_between",
      "kwargs": {
        "max_value": {
          "$PARAMETER": "max_row_count",
          "$PARAMETER.max_row_count": 10
        },
        "min_value": {
          "$PARAMETER": "min_row_count",
          "$PARAMETER.min_row_count": 0
        }
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.15.41"
  }
}

```

Error:
```
TypeError: _run() got an unexpected keyword argument 'payload'
```
