### ISSUE TITLE
Data docs do not show set of expected values

### ISSUE THREAD

**Issue by SSchotten** [fivetran/great_expectations#7029]
**Describe the bug**
When using the `expect_column_distinct_values_to_equal_set` expectation, the ‘Expectation’ column in the resulting data docs is showing an empty set of values: 
![image](https://user-images.githubusercontent.com/16923510/216342086-d4bad5a0-41bf-48ee-8d40-b96222033f11.png)

Meanwhile, using another set-expectation (and same expected `value_set`), namely `expect_column_distinct_values_to_contain_set`, the full collection of expected values *is* shown: 
![image](https://user-images.githubusercontent.com/16923510/216342709-67c6421f-5ed8-4c80-8e2c-f833211ab5ac.png)

**To Reproduce**
1. Create an `expect_column_distinct_values_to_equal_set` expectation with value_set e.g. `["1", "2", "3"]`
2. Create an `expect_column_distinct_values_to_contain_set` expectation with the same `value_set` (e.g. `["1", "2", "3"]`)
3. Run both expectations against some data set and update the data docs
4. Observe the different results in the data docs

**Expected behavior**
I would expect both types of expectations (since both are on sets) to generate the same values in the 'Expectation' column in the data docs. 

**Environment**
 - Operating System: Linux (alpine latest)
 - Great Expectations Version: 0.15.41

**Comment by rdodev** [comment]
Hey @SSchotten 👋  thanks for reporting this issue.

Let me dig and see what could be going on. In the meanwhile could you please include relevant code/configs? Thanks!

**Comment by SSchotten** [comment]
I'm running my checkpoint with a `RunTimeBatchRequest` and Spark dataframe, using the below `datasource_name` and `expectation_suite_name` to create my validations and pass them to `data_context.run_checkpoint`. 

My expectation suite config:
```
{
  "data_asset_type": null,
  "expectation_suite_name": "yyyyy",
  "expectations": [
    {
      "expectation_type": "expect_column_distinct_values_to_equal_set",
      "kwargs": {
        "column": "garage_cde",
        "value_set": [
          "001",
          "002",
          "003",
          "004",
          "005",
          "006",
          "007",
          "008",
          "009",
          "010",
          "011",
          "012",
          "013",
          "014",
          "015"
        ]
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "great_expectations_version": "0.15.41"
  }
}
```


My checkpoint config: 

```
name: garage_cde_base_checkpoint
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template:
expectation_suite_name:  
batch_request: {}  
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names:
        - azure_site
  - name: send_slack_notification
    action:
      class_name: SlackNotificationAction
      # put the actual webhook URL in the uncommitted/config_variables.yml file
      slack_webhook: ${validation_notification_slack_webhook}
      notify_on: failure # possible values: "all", "failure", "success"
      notify_with:
        - azure_site
      renderer:
        module_name: great_expectations.render.renderer.slack_renderer
        class_name: SlackRenderer
evaluation_parameters: {}
runtime_configuration: {}
validations: []  
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
```

And parts of my `great_expectations.yml`:
```
datasources:
  garage_staging_datasource:
    data_connectors:
      default_runtime_data_connector_name:
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - default_identifier_name
        class_name: RuntimeDataConnector
    execution_engine:
      class_name: SparkDFExecutionEngine
      module_name: great_expectations.execution_engine
      force_reuse_spark_context: true  # see https://github.com/great-expectations/great_expectations/issues/4812
    module_name: great_expectations.datasource
    class_name: Datasource

...

expectations_store:
  class_name: ExpectationsStore
  store_backend:
    class_name: TupleFilesystemStoreBackend
    base_directory: expectations/

...

validations_azure_store:
  class_name: ValidationsStore
  store_backend:
    class_name: TupleAzureBlobStoreBackend
    container: '\$web'
    prefix: 'validations'
    connection_string: xxxxx

...

data_docs_sites:
  azure_site:
    class_name: SiteBuilder
    show_how_to_buttons: false
    store_backend:
        class_name: TupleAzureBlobStoreBackend
        container: '\$web'
        connection_string: xxxxx
    site_index_builder:
        class_name: DefaultSiteIndexBuilder
```
