### ISSUE TITLE
Checkpoints: Reimplement multiple expectations suites per batch request

### ISSUE THREAD

**Issue by luke321321** [fivetran/great_expectations#7140]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to specify multiple expectation suites per `batch_request` in a checkpoint.  This previously was possible in v2 of GX but has been removed by the way that checkpoints are now designed in v3.  I've noticed this gap whilst trying to upgrade.

Previously in v2 of GX I could specify the following
```yaml
name: forecast_output
module_name: great_expectations.checkpoint
class_name: LegacyCheckpoint
validation_operator_name: run_severity_levels_operator. # custom validation operator ✨
# Batches are a list of batch_kwargs paired with a list of one or more suite
# names. A checkpoint can have one or more batches....
batches:
  - batch_kwargs:
      query: select * from forecasts
      datasource: 'my_data_source'
    expectation_suite_names: # one or more suites may validate against a single batch
      - forecast.warning
      - forecast.error
  - batch_kwargs:
      query: select * from forecasts where cutoff >= current_timestamp
        - interval '7 days'
      datasource: 'my_data_source'
    expectation_suite_names: # one or more suites may validate against a single batch
      - forecast.recent-data-error
  - batch_kwargs:
      query: select * from forecast_metrics
      datasource: 'my_data_source'
    expectation_suite_names:
      - forecast_metrics.warning
      - forecast_metrics.error
```

As you can see, for small custom SQL filter queries etc, this allows multiple expectation suites to be run against each batch of data within a checkpoint.  In v3 you can do this a few ways but none of them satisfactory:

1. if you using just one batch of data within a checkpoint (nicked from [docs](https://docs.greatexpectations.io/docs/guides/validation/checkpoints/how_to_configure_a_new_checkpoint_using_test_yaml_config)):

```yaml
name: airflow_users_node_3
config_version: 1
class_name: Checkpoint
batch_request:
    datasource_name: my_datasource
    data_connector_name: my_special_data_connector
    data_asset_name: users
    data_connector_query:
        index: -1
validations:
  - expectation_suite_name: users.warning
  - expectation_suite_name: users.error
    action_list:
    - ...
action_list:
    - ...
```

2. Or multiple batches can be used with a single expectation suite:

```yaml
name: my_fancy_checkpoint
config_version: 1
class_name: Checkpoint
validations:
  - batch_request:
      datasource_name: my_datasource
      data_connector_name: my_special_data_connector
      data_asset_name: users
      data_connector_query:
        index: -1
  - batch_request:
      datasource_name: my_datasource
      data_connector_name: my_other_data_connector
      data_asset_name: users
      data_connector_query:
        index: -2
expectation_suite_name: users.delivery
action_list:
    - ...
```
3. You give a pair of expectation suites and batches of data (and so for the same batch of data have to copy it multiple times within a checkpoint):

```yaml
name: my_fancy_checkpoint_paried
config_version: 1
class_name: Checkpoint
validations:
  - batch_request:
      datasource_name: my_datasource
      data_connector_name: my_special_data_connector
      data_asset_name: users
      data_connector_query:
        index: -1
    expectation_suite_name: users.delivery.warning
  - batch_request:
      datasource_name: my_datasource
      data_connector_name: my_special_data_connector
      data_asset_name: users
      data_connector_query:
        index: -1
     expectation_suite_name: users.delivery.error
action_list:
    - ...
```

**Describe the solution you'd like**
I'd like the `expectation_suite_name` to be able to take in a list of expectation suites and generate the pairs of validations.  This is similar functionality to v2 of GX.  This will reduce the vebosity and copy and pasting needed in checkpoints.  This is more important when the `batch_request` might contain a brief SQL query.  If one updates that query one needs to remember to do it in all the `batch_request`s.

```yaml
name: my_fancy_checkpoint_paried
config_version: 1
class_name: Checkpoint
validations:
  - batch_request:
      datasource_name: my_datasource
      data_connector_name: my_special_data_connector
      data_asset_name: users
      data_connector_query:
        index: -1
    expectation_suite_name: 
      - users.delivery.warning
      - users.delivery.error
action_list:
    - ...
```

Note potentially renaming `expectation_suite_name` to ``expectation_suite_names` or allowing `expectation_suite_names` might make more semantic sense.  However, I care less about this (now).

**Describe alternatives you've considered**
1. Templating the checkpoint with jinja2
2. Creating multiple checkpoints so I don't have to repeat the `batch_request` boilerplate for multiple expectation suites per `batch_request`.  I often have 2-3 suites per batch of data.  This is a no-goer as it'll create multiple notifications for really the same checkpoint adding to the alerting noise.

**Additional context**
None
