### ISSUE TITLE
Allow parameterisation of SqlAlchemyQueryStore queries

### ISSUE THREAD

**Issue by mike-f50** [fivetran/great_expectations#7198]
**Is your feature request related to a problem? Please describe.**
We have a large number of queries in our query store, which are identical apart from the `where` clause.

**Describe the solution you'd like**
It would be advantageous if we could do something like this (to use the example from the GE guide):
```
my_query_store:
    class_name: SqlAlchemyQueryStore
    credentials: ${rds_movies_db}
    queries:
      current_ratings_max_by_genre:
        query: "SELECT MAX(rating) FROM ratings WHERE genre = '${genre}';"
        return_type: "scalar"
```
Ideally, `$genre` can then be specified at point of use in the Expectation Suite, to allow for multiple variations of the same query to be used in the same Expectation Suite, e.g. 
```
{ "$PARAMETER": "urn:great_expectations:stores:my_query_store:current_ratings_max_by_genre", { "genre": "documentary" } }
```

**Describe alternatives you've considered**
Currently, we simply have a large number of near-identical queries defined in our query store.  This works, but no-one likes code duplication.

Out of interest, substiution in the query definition does work now, if `$genre` is set as an environment variable - but this doesn't help our use case of referencing multiple variations of a the same query in a single Checkpoint/Expectation Suite.

**Additional context**
Thanks Tal for helping to explore this via Slack.
