### ISSUE TITLE
OpenLineage and Great Expectations integrated

### ISSUE THREAD

**Issue by jingyichen790** [fivetran/great_expectations#7248]
Hello team, we used OpenLineage and Great Expectations integrated. I want to use GE to verify the table in Snowflake. I found that the configuration I added OpenLineage into GE produced this error after running. Could someone please give me some answers?
`  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/great_expectations/validation_operators/validation_operators.py", line 469, in _run_actions
    action_result = self.actions[action["name"]].run(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/great_expectations/checkpoint/actions.py", line 106, in run
    return self._run(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openlineage/common/provider/great_expectations/action.py", line 156, in _run
    datasets = self._fetch_datasets_from_sql_source(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openlineage/common/provider/great_expectations/action.py", line 362, in _fetch_datasets_from_sql_source
    self._get_sql_table(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/openlineage/common/provider/great_expectations/action.py", line 395, in _get_sql_table
    if engine.connection_string:
AttributeError: 'Engine' object has no attribute 'connection_string'
'Engine' object has no attribute 'connection_string'
`

This is my package version list:
`openlineage-integration-common
great_expectations==0.15.44
sqlalchemy
psycopg2-binary
numpy
pandas
snowflake-connector-python
snowflake-sqlalchemy
black
`

This is my configuration:

name: 'openlineage_checkpoint'
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-my_checkpoint'
expectation_suite_name: EMAIL_VALIDATION
batch_request:
action_list:
  \- name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  \- name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  \- name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
  \- name: openlineage
    action:
      class_name: OpenLineageValidationAction
      module_name: openlineage.common.provider.great_expectations
      openlineage_host: http://localhost:5000/
      openlineage_namespace: ge_expectations # Replace with your job namespace; we recommend a meaningful namespace like `dev` or `prod`, etc.
      job_name: ge_validation
evaluation_parameters: {}
runtime_configuration: {}
validations:
  \- batch_request:
      datasource_name: LANDING_DEV
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: 'snowpipe.pii'
      data_connector_query:
        index: -1
    expectation_suite_name: EMAIL_VALIDATION
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:

**Comment by jingyichen790** [comment]
@denimalpaca

**Comment by rdodev** [comment]
Hey @jingyichen790 can you please provide more details about versions you're using? What version of SQLAlchemy, OpenLineage action, etc. Thanks!

**Comment by jingyichen790** [comment]
snowflake-connector-python     2.8.1
snowflake-sqlalchemy           1.4.6
SQLAlchemy                     1.4.46
openlineage-integration-common 0.20.6
openlineage-python             0.20.6
openlineage_sql                0.20.6

**Comment by alexsherstinsky** [comment]
Hello, @jingyichen790 -- my hypothesis is that the datasource configuration for your Snowflake Data Warehouse might need a closer look.  Could you please provide it here (ideally with the original formatting) exactly the way it appears in your `great_expectations.yml` file -- in fact, if you can provide that entire file (please be sure to put "*"s for any passwords and other sensitive information), then I would be happy to take a look.  The the message comes as `AttributeError: 'Engine' object has no attribute 'connection_string'`, examining the configuration might be a useful step.

Another area for investigation is the use of SQLAlchemy is in use by OpenLineage -- according to the `SQLAlchemy` API documentation, `connection_string` is not a property of the `Engine` class.  Hence, the code snippet:
```
        if engine.dialect.name.lower() == "snowflake":
            if engine.connection_string:
                datasource_url = engine.connection_string
            else:
                datasource_url = engine.url
            datasource_url = fix_snowflake_sqlalchemy_uri(datasource_url)
```

on line 394 in "https://github.com/OpenLineage/OpenLineage/blob/main/integration/common/openlineage/common/provider/great_expectations/action.py" would probably be useful to trace, whereby, perhaps some portions of it would need to be placed into a "try/except" block.

Thank you very much.

**Comment by jingyichen790** [comment]
```
config_version: 3.0
datasources:
  LANDING_DEV:
    class_name: Datasource
    module_name: great_expectations.datasource
    execution_engine:
      class_name: SqlAlchemyExecutionEngine
      module_name: great_expectations.execution_engine
      connection_string: *
    data_connectors:
      default_inferred_data_connector_name:
        include_schema_name: true
        class_name: InferredAssetSqlDataConnector
        module_name: great_expectations.datasource.data_connector
        name: default_inferred_data_connector_name
      default_runtime_data_connector_name:
        class_name: RuntimeDataConnector
        module_name: great_expectations.datasource.data_connector
        batch_identifiers:
          - table
          - query
        name: default_runtime_data_connector_name

config_variables_file_path: uncommitted/config_variables.yml

plugins_directory: plugins/

stores:
  expectations_store:
    class_name: ExpectationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: expectations/

  validations_store:
    class_name: ValidationsStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/validations/

  evaluation_parameter_store:
    class_name: EvaluationParameterStore
  checkpoint_store:
    class_name: CheckpointStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: checkpoints/

  profiler_store:
    class_name: ProfilerStore
    store_backend:
      class_name: TupleFilesystemStoreBackend
      suppress_store_backend_id: true
      base_directory: profilers/

expectations_store_name: expectations_store
validations_store_name: validations_store
evaluation_parameter_store_name: evaluation_parameter_store
checkpoint_store_name: checkpoint_store

data_docs_sites:
  local_site:
    class_name: SiteBuilder
    show_how_to_buttons: true
    store_backend:
      class_name: TupleFilesystemStoreBackend
      base_directory: uncommitted/data_docs/local_site/
    site_index_builder:
      class_name: DefaultSiteIndexBuilder

anonymous_usage_statistics:
  data_context_id: *
  enabled: true
notebooks:
include_rendered_content:
  expectation_suite: false
  expectation_validation_result: false
  globally: false

```

**Comment by jingyichen790** [comment]
Hi @alexsherstinsky, Thanks for your reply. This is my configuration in GE yaml. Could you have a check. Thank you very much.

**Comment by alexsherstinsky** [comment]
Hello, @jingyichen790 -- thank you for providing your configuration; it was very helpful!  Based on this, may I please suggest a couple of ideas for the next steps?  Here they are:
* Let us delete the `default_runtime_data_connector_name` section from your configuration; it is not used, so let us prevent any potential errors in it from hindering our progress.
* Here is the configuration section of `default_inferred_data_connector_name` in the dictionary format; for error checking purposes, please make sure that your `YAML` format is equivalent to this dictionary version (and vice versa).

```
"my_snowflake_inferred_data_connector": {
	"module_name": "great_expectations.datasource.data_connector",
	"class_name": "InferredAssetSqlDataConnector",
	# "data_asset_name_prefix": "test__",
	# "data_asset_name_suffix": "__asset",
	"include_schema_name": True,
	# "splitter_method": "split_on_year_and_month",
	# "splitter_kwargs": {
	# 	"column_name": "my_datetime_column",
	# },
	# "sampling_method": "sample_using_limit",
	# "sampling_kwargs": {
	#	"n": "10",
	#},
	#"excluded_tables": [
	#	"my_skip_schema.my_skip_table",
	#	"my_other_skip_schema.my_skip_table",
	#	"my_new_skip_schema.my_new_skip_table",
	#],
	#"included_tables": [
	#	"public.my_important_included_2023_table",
	#],
	"skip_inapplicable_tables": True,
	"introspection_directives": {
		"schema_name": "my_schema",
		"ignore_information_schemas_and_system_tables": True,
		"information_schemas": None,
		"system_tables": None,
		"include_views": True,
	},
}
```

You can delete the commented lines (or use them as examples for future needs), but please keep the lines that are not commented out.

For me, the YAML version looks like this:
```
my_snowflake_inferred_data_connector:
  class_name: InferredAssetSqlDataConnector
  include_schema_name: true
  introspection_directives:
    ignore_information_schemas_and_system_tables: true
    include_views: true
    information_schemas: null
    schema_name: my_schema
    system_tables: null
  module_name: great_expectations.datasource.data_connector
  skip_inapplicable_tables: true
```

For the `ExecutionEngine` portion of the Snowflake `datasource` configuration, please try the following first:
```
    execution_engine:
      connection_string: snowflake://<user_login_name>:<password>@<account_identifier>/<database_name>/<schema_name>?warehouse=<warehouse_name>&role=<role_name>'
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
```

I believe that this is what you are doing, just please be aware of the indentation and the fact that in Snowflake, all identifiers (account_identifier, database_name, schema_name, warehouse_name, role_name, and table and column names are by default specified in all capital letters).

If this approach does not work, please try the following alternative configuration format:
```
    execution_engine:
      credentials:
        host: account_identifier
        username: user_login_name
        database: database_name
        query:
          schema: schema_name
          warehouse: warehouse_name
          role: role_name
        password: password
        drivername: snowflake
      module_name: great_expectations.execution_engine
      class_name: SqlAlchemyExecutionEngine
```

The values in this configuration version correspond to those in the previous, again with the reminder about the YAML indentation and Snowflake identifier capitalization styles.

Please try these ideas and let me know your results.

Thank you very much for your time and for using GreatExpectations!

**Comment by jingyichen790** [comment]
Hi @alexsherstinsky, I followed your configuration. I change the my_schema to snowpipe. There is a new error which is 'data_asset_name snowpipe is not recognized.' This is my checkpoint:
```
name: 'openlineage_checkpoint'
config_version: 1.0
template_name:
module_name: great_expectations.checkpoint
class_name: Checkpoint
run_name_template: '%Y%m%d-%H%M%S-my_checkpoint'
expectation_suite_name: EMAIL_VALIDATION
batch_request:
action_list:
  - name: store_validation_result
    action:
      class_name: StoreValidationResultAction
  - name: store_evaluation_params
    action:
      class_name: StoreEvaluationParametersAction
  - name: update_data_docs
    action:
      class_name: UpdateDataDocsAction
      site_names: []
  - name: openlineage
    action:
      class_name: OpenLineageValidationAction
      module_name: openlineage.common.provider.great_expectations
      openlineage_host: x
      # openlineage_apiKey: x
      job_name: ge_validation
      openlineage_namespace: ge_expectations
evaluation_parameters: {}
runtime_configuration: {}
validations:
  - batch_request:
      datasource_name: LANDING_DEV
      data_connector_name: default_inferred_data_connector_name
      data_asset_name: 'snowpipe.pii'
      data_connector_query:
        index: -1
    expectation_suite_name: EMAIL_VALIDATION
profilers: []
ge_cloud_id:
expectation_suite_ge_cloud_id:
```
