### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:postgres

### ISSUE THREAD

**Issue by unkind58** [fivetran/great_expectations#7330]
![sqlalchemy_plugin_error](https://user-images.githubusercontent.com/56277583/224356110-168e79c0-853e-4ec2-98b2-c547d573a1e7.png)
**Describe the bug**
Validation results did not stored after initializing PostgreSQL validation store. If the same checkpoint run CLI with default validation store (uncommitted/validations)  - all good, getting validation results.

**To Reproduce**
Here is validation store snippet:
```
- name: validations_postgres_store
class_name: ValidationsStore
store_backend:
  class_name: DatabaseStoreBackend
  credentials:
      database: unkind58_db_postgres
      drivername: postgresql
      host: localhost
      password: *********
      port: '5432'
      username: unkind58
```
Getting error: **Can't load plugin: sqlalchemy.dialects:postgres**.

**Expected behavior**
Validation result table should be created in designated postgresql schema.

**Environment (please complete the following information):**
 - Operating System: Linux Ubuntu 
 - Great Expectations Version: 0.15.50
 - SQLAlchemy Version: 1.4.46

**Additional context**
Maybe it is still old call code for validation store in core GE code? (I mean _postgres://_, not _postgresql+psycopg2://_) 
Also, tried to downgrade SqLAlchemy to 1.3.6, at that point got two additional issues:
- getting error after running checkpoint: `table() got an unexpected keyword argument 'schema'. After rolling back to 1.4.46 no such error.
- connection error after specifing _validation_postgres_store_:  FATAL: Ident authentication failed for user 'unkind58' (but if taking out this new store - connection works with data source via connection string, seems issue only via credentials from config_variables.yml file).

**Comment by alexsherstinsky** [comment]
Hello, @unkind58 -- thank you very much for reporting this issue.  I believe that your assessment is correct in that the connection string should end up having the format of `"postgresql+psycopg2://username:my_password@host/db_name"`.  Could you please try using the `connection_string` as a way of specifying the store backend to verify that the suggestion above works?  Please also see https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/database/postgres for details of what the configuration should look like and let us know whether or not it worked for you.  Thank you.

**Comment by unkind58** [comment]
Hello,
`connection_string` worked well for me to connect my data source:

```
datasource_config = {
    "name": "unkind58_db_postgres",
    "class_name": "Datasource",
    "execution_engine": {
        "class_name": "SqlAlchemyExecutionEngine",
        "connection_string": "postgresql+psycopg2://:@:/",
```

but in GE documentation there is no example how to connect/adjust `connection_string` for validation store so I am connecting it via the code snippet above:

```
- name: validations_postgres_store
class_name: ValidationsStore
store_backend:
  class_name: DatabaseStoreBackend
  credentials:
      database: unkind58_db_postgres
      drivername: postgresql
      host: localhost
      password: *********
      port: '5432'
      username: unkind58

```
and it  did not work. 
Also, I tried to downgrade the SQLAlchemy to 1.3.6 but then getting error like: `table() got an unexpected keyword argument 'schema'`, and after rolling back to 1.4.46 such error disappeared.

**Comment by alexsherstinsky** [comment]
Hi @unkind58 -- I will notify the team to ensure that the documentation is updated -- thank you for pointing this out.  Could you please try to specify the `schema` name as part of the credentials?  I am not seeing it in your example above and would like to see if this could be the issue.  Also, please try the `port` setting without the quotes and/or using the double quotes.  (These attempts are just in case the settings' presence/values matter for your setup.)  Thank you.

**Comment by unkind58** [comment]
Hi, it still did not work for me, so decided try it with snowflake and created predefined table (was told to do so in the slack GE channel) : _**ge_validations_store**_ and connected with credentials in the same way as in postgres, and it worked - I mean table was populated with validation results.

**Comment by alexsherstinsky** [comment]
@unkind58 Thank you very much for letting me know.  So, is the outcome that using PostGreSQL did not work, but using Snowflake for ValidationStore worked?  Could you please share your configuration with me (excluding the sensitive information, such as passwords, by using asterisks instead of actual characters)?  I would like to better understand why (it is strange, and perhaps we are not seeing something simple, like a typographical error, or incorrect indentation).  Thanks!

**Comment by unkind58** [comment]
I used this construction (in `config_variables.yml`) for credentials for my Validation store (structure saw in old version of documentation for snowflake):
```
my_snowflake_db:
    drivername: snowflake
    username: unkind58
    password ****************
    host: ******.eu-central-1
    database: YELLOW_TAXI
    query:
        schema: TEST
        warehouse: COMPUTE_WH
        role: SYSADMIN
```
In `great_expectations.yml`:
```
validation_snowflake_store:
    class_name: ValidationStore
    store_backend:
        class_name: DatabaseStoreBackend
        credentials: ${my_snowflake_db}
		
validation_store_name: validation_snowflake_store
```

**Comment by NathanFarmer** [comment]
Hello @unkind58! I apologize for the delay in responding. I have been unable to reproduce this issue. It works for me with the configuration you have provided:
```
- name: validations_postgres_store
class_name: ValidationsStore
store_backend:
  class_name: DatabaseStoreBackend
  credentials:
      database: unkind58_db_postgres
      drivername: postgresql
      host: localhost
      password: *********
      port: '5432'
      username: unkind58
```

The only way I have been able to get the same error message is if I change the `drivername` to `postgres`.

Can you confirm - do you have `psycopg2` installed? What if you change the `drivername` to `postgresql+psycopg2`?
