### ISSUE TITLE
great_expectations.yml has broken links

### ISSUE THREAD

**Issue by ian-whitestone** [fivetran/great_expectations#854]
Working off the latest version:

```
→ great_expectations --version

great_expectations, version 0.8.4.post0
```

YAML file generated from `great_expectations init` has the following contents:

```yaml

# Welcome to Great Expectations! Always know what to expect from your data.
# 
# Here you can define datasources, generators, integrations and more. This file
# is intended to be committed to your repo. For help with configuration please:
#   - Read our docs: https://docs.greatexpectations.io/en/0_8_4_post0/reference/data_context_reference.html#configuration
#   - Join our slack channel: http://greatexpectations.io/slack
#
# NOTE: GE uses the names of configured `datasources` and `generators` to manage
# how `expectations` and other artifacts are stored in the `expectations/` and 
# `datasources/` folders. If you need to rename an existing `datasource` or 
# `generator`, be sure to also update the relevant directory names.

config_version: 1

# Datasources tell Great Expectations where your data lives and how to get it.
# You can use the CLI command `great_expectations add-datasource` to help you
# add a new datasource. Read more at https://docs.greatexpectations.io/en/0_8_4_post0/features/datasource.html
datasources:
  test:
    class_name: PandasDatasource
    data_asset_type:
      class_name: PandasDataset
    generators:
      default:
        class_name: SubdirReaderGenerator
        base_directory: ../misc
        reader_options:
          sep:
          engine: python
```

All the docs linked throughout the yaml file, i.e. https://docs.greatexpectations.io/en/0_8_4_post0/features/datasource.html, do not exist.
